### ISSUE TITLE
GraphMLReader seems to be buggy when using it with JanusGraph

### ISSUE THREAD

**Issue by XComp** [JanusGraph/janusgraph#1035]
I tried to write a InputStream that can be used to load the academics data utilizing the GraphMLReader provided by JanusGraph. But there's seems to be a contradiction between the node ID attribute in GraphML which is always a String and the internal representation of the JanusGraph ID (which is a long value).

There is no way to make the GraphMLReader parsing the long value out of the XML id attribute's value, which is loaded as a String value.

I added a (@Ignored) testcase which fails right now but can be used for further investigation.

**Comment by pluradj** [comment]
Do you have an example GraphML that demonstrates the issue? Are you loading the file with `graph.io(graphml()).readGraph("mygraph.xml")` or some other way?

The GraphML files from TinkerPop found under the [`data`](https://github.com/JanusGraph/janusgraph/tree/v0.2.0/janusgraph-dist/src/assembly/static/data) directory all load fine.

**Comment by XComp** [comment]
I created a simple example with the [tinkerpop-modern.xml](https://github.com/JanusGraph/janusgraph/blob/v0.2.0/janusgraph-dist/src/assembly/static/data/tinkerpop-modern.xml) found in the janusgraph repository using the following code:
```java
import org.apache.tinkerpop.gremlin.structure.io.IoCore;
import org.janusgraph.core.JanusGraph;
import org.janusgraph.core.JanusGraphFactory;
import java.io.IOException;

public class TinkerpopGraphMLImportTest {
    public static void main(String[] args) throws IOException {
        JanusGraphFactory.Builder configBuilder = JanusGraphFactory.build();
        configBuilder
                .set("gremlin.graph", "org.janusgraph.core.JanusGraphFactory")
                .set("storage.backend", "inmemory")
                .set("graph.set-vertex-id", "true");
        try (JanusGraph graph = configBuilder.open()) {
            System.out.println("[Pre-import]  Node count: " + graph.traversal().V().count().next());
            graph.io(IoCore.graphml()).readGraph("core/src/test/resources/tinkerpop-modern.xml");
            System.out.println("[Post-import] Node count: " + graph.traversal().V().count().next());
        }
    }
}
```
The problem seems to be the `graph.set-vertex-id`. If disabled, the import succeeds and the expected number of vertices (6) is printed. If enabled, I get the same `IllegalArgumentException` being thrown having the following stacktrace:
```
Exception in thread "main" java.lang.IllegalArgumentException: Must provide vertex id
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:135)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.addVertex(StandardJanusGraphTx.java:515)
	at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsTransaction.addVertex(JanusGraphBlueprintsTransaction.java:123)
	at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph.addVertex(JanusGraphBlueprintsGraph.java:129)
	at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph.addVertex(JanusGraphBlueprintsGraph.java:47)
	at org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLReader.findOrCreate(GraphMLReader.java:310)
	at org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLReader.readGraph(GraphMLReader.java:177)
	at org.apache.tinkerpop.gremlin.structure.io.graphml.GraphMLIo.readGraph(GraphMLIo.java:92)
	at TinkerpopGraphMLImportTest.main(TinkerpopGraphMLImportTest.java:16)
```

This underlines the observed behavior of this issue. Probably, the tests on GraphML loads is not tested on custom vertex IDs?

**Comment by XComp** [comment]
I also grepped for the XML files in the JanusGraph repository. Non of the XML files seem to be loaded anywhere:
```bash
$ git clone git@github.com:JanusGraph/janusgraph.git
$ cd janusgraph
$ grep -R 'tinkerpop-[a-z]*.xml' .
Binary file ./.git/index matches
```
This looks like an indication that the GraphML is not checked anywhere. Or am I mislead here?
