### ISSUE TITLE
Flaky Solr test

### ISSUE THREAD

**Issue by YevIgn** [JanusGraph/janusgraph#1091]
There appeared several times a failure of the `SolrIndexText#testTTL` in
- https://travis-ci.org/JanusGraph/janusgraph/jobs/373477718 on solr6
- https://travis-ci.org/JanusGraph/janusgraph/jobs/385071158 on solr5
- https://travis-ci.org/JanusGraph/janusgraph/jobs/371272709 on solr5
- https://travis-ci.org/JanusGraph/janusgraph/jobs/368598831 on solr5

With no seemingly related changes that can affect this test case. Both of the failures looked identically:
```
org.janusgraph.diskstorage.solr.SolrIndexTest
testTTL(org.janusgraph.diskstorage.solr.SolrIndexTest)  Time elapsed: 6.187 sec  <<< FAILURE!
java.lang.AssertionError: expected:<2> but was:<4>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at org.janusgraph.diskstorage.indexing.IndexProviderTest.testTTL(IndexProviderTest.java:772)
        ...
```

**Comment by twilmes** [comment]
Thanks for reporting this @YevIgn. My guess is this is a timing issue and for whatever reason, the 6 second sleep isn't long enough. Perhaps we could refactor some of these that rely on a sleep to instead poll for the condition that is being asserted from up to a max amount of time instead of adding sleeps and relying on the index to converge.

**Comment by jerryjch** [comment]
There seem to other flaky tests in Solr in addition to the testTTL mentioned in the description of this issue.  We will add them here when we see them.

**Comment by porunov** [comment]
Looks like this one is a flaky test: https://travis-ci.org/JanusGraph/janusgraph/jobs/489592012
