### ISSUE TITLE
can not initialize ConfigurationManagementGraph

### ISSUE THREAD

**Issue by 807879561** [JanusGraph/janusgraph#1133]
Configurations:
host: 0.0.0.0
port: 8182
scriptEvaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphManager: org.janusgraph.graphdb.management.JanusGraphManager
graphs: {
  graph: conf/gremlin-server/janusgraph-cassandra-es-server.properties,
  graphtest: conf/gremlin-server/janusgraph-cassandra-es-server2.properties,
  ConfigurationManagementGraph: conf/gremlin-server/janusgraph-configurationmanagement.properties
}

gremlin.graph=org.JanusGraph.core.JanusGraphFactory
storage.backend=cassandrathrift
graph.graphname=ConfigurationManagementGraph

start gremlin-server:

stuck in
1900 [main] INFO  org.janusgraph.diskstorage.log.kcvs.KCVSLog  - Loaded unidentified ReadMarker start time 2018-06-21T02:28:30.371Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@7dd712e8
6/21/18 10:31:28 AM ============================================================

Caused by: org.janusgraph.diskstorage.locking.consistentkey.ExpiredLockException: Expired lock on KeyColumn [k=0x 16-165-160-103-105- 30- 71-114- 97-112-104- 95- 78- 97-109-101- 95- 73-110-100-101-248, c=0x  0]: lock timestamp 2018-06-20T12:36:51.883Z Micros is older than storage.lock.expiry-time=PT5M
	at org.janusgraph.diskstorage.locking.consistentkey.ConsistentKeyLocker.checkSingleLock(ConsistentKeyLocker.java:448)
	at org.janusgraph.diskstorage.locking.consistentkey.ConsistentKeyLocker.checkSingleLock(ConsistentKeyLocker.java:125)
	at org.janusgraph.diskstorage.locking.AbstractLocker.checkLocks(AbstractLocker.java:351)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.checkAllLocks(ExpectedValueCheckingTransaction.java:178)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingTransaction.prepareForMutations(ExpectedValueCheckingTransaction.java:157)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingStoreManager.mutateMany(ExpectedValueCheckingStoreManager.java:72)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:98)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:95)
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:69)
	... 21 more

**Comment by chupman** [comment]
One thing that jumps out to me is that
```gremlin.graph=org.JanusGraph.core.JanusGraphFactory```
should be 
```gremlin.graph=org.janusgraph.core.ConfiguredGraphFactory```

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.

**Comment by mikehowey1** [comment]
The current documentation is not clear on this and actually shows the use of JanusGraphFactory instance?
https://docs.janusgraph.org/latest/configuredgraphfactory.html

> One thing that jumps out to me is that
> `gremlin.graph=org.JanusGraph.core.JanusGraphFactory`
> should be
> `gremlin.graph=org.janusgraph.core.ConfiguredGraphFactory`

**Comment by FlorianHockmann** [comment]
That's true and we already have an issue for that: #1372 which should be fixed with the next release.
