### ISSUE TITLE
Tests failing in master (?)    v2

### ISSUE THREAD

**Issue by bukzor** [JanusGraph/janusgraph#1134]
```
$ mvn -version     
Apache Maven 3.5.4 (1edded0938998edf8bf061f1ceb3cfdeccf443fe; 2018-06-17T11:33:14-07:00)
Maven home: /home/buck/prefix/brew/Cellar/maven/3.5.4/libexec
Java version: 1.8.0_162, vendor: Oracle Corporation, runtime: /home/buck/prefix/brew/Cellar/jdk@8/1.8.0-162/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.13.0-43-lowlatency", arch: "amd64", family: "unix"

$ git log -1 --oneline
2a6072860 (HEAD -> 0.2, origin/0.2) Fixed the rest of the javadoc breaking errors and enabled linting [skip ci]

$ mvn clean install   
<trillions of log lines and three hours later>
Results :

Tests in error: 
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer
  CQLStoreTest>KeyColumnValueStoreTest.setUp:68 » NullPointer

Tests run: 230, Failures: 0, Errors: 13, Skipped: 1

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] JanusGraph: Distributed Graph Database 0.2.1-SNAPSHOT SUCCESS [  0.785 s]
[INFO] JanusGraph-Core: Core Library for JanusGraph ....... SUCCESS [ 25.108 s]
[INFO] JanusGraph-Test: Test Suite for JanusGraph ......... SUCCESS [30:22 min]
[INFO] JanusGraph CodePipelines CI: Distributed release testing. SUCCESS [ 17.619 s]
[INFO] JanusGraph-BerkeleyJE: Distributed Graph Database .. SUCCESS [09:36 min]
[INFO] JanusGraph-Cassandra: Distributed Graph Database ... SUCCESS [  02:15 h]
[INFO] JanusGraph-CQL: Distributed Graph Database ......... FAILURE [25:28 min]
[INFO] JanusGraph-ElasticSearch: Distributed Indexing Support SKIPPED
[INFO] JanusGraph-HBase: Parent Module .................... SKIPPED
[INFO] JanusGraph-HBase: Version-independent Core ......... SKIPPED
[INFO] JanusGraph-HBase: 0.98 Compatibility Shim .......... SKIPPED
[INFO] JanusGraph-HBase: 1.x Compatibility Shim ........... SKIPPED
[INFO] JanusGraph-HBase: Universal binary ................. SKIPPED
[INFO] JanusGraph-Hadoop: Parent Module ................... SKIPPED
[INFO] JanusGraph-Hadoop: Version-independent Core ........ SKIPPED
[INFO] JanusGraph-Hadoop: 2.x Compatibility Shim .......... SKIPPED
[INFO] JanusGraph-Hadoop: Universal binary ................ SKIPPED
[INFO] JanusGraph-Bigtable: Google Cloud Bigtable driver .. SKIPPED
[INFO] JanusGraph-Lucene: Indexing Support ................ SKIPPED
[INFO] JanusGraph-Solr: Distributed Indexing Support ...... SKIPPED
[INFO] JanusGraph-All: Complete JanusGraph Distribution ... SKIPPED
[INFO] JanusGraph-Dist: Tar and Zip Archives .............. SKIPPED
[INFO] JanusGraph-Dist: Archive with Hadoop 2 ............. SKIPPED
[INFO] JanusGraph-Doc: AsciiDoc Manual for JanusGraph ..... SKIPPED
[INFO] JanusGraph-Examples: Examples for JanusGraph ....... SKIPPED
[INFO] Example-Common: Common Graph Code for Examples ..... SKIPPED
[INFO] Example-BerkeleyJE: BerkeleyJE Storage, Lucene Index SKIPPED
[INFO] Example-Cassandra: Cassandra Thrift Storage, Elasticsearch Index SKIPPED
[INFO] Example-Cql: Cassandra CQL Storage, Elasticsearch Index SKIPPED
[INFO] Example-HBase: HBase Storage, Solr Index ........... SKIPPED
[INFO] Example-RemoteGraph: Example with RemoteGraph ...... SKIPPED
[INFO] Example-TinkerGraph: Example with TinkerGraph 0.2.1-SNAPSHOT SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:21 h
[INFO] Finished at: 2018-06-23T15:43:53-07:00
[INFO] ------------------------------------------------------------------------
```

I think this error is representative:
```
Running org.janusgraph.diskstorage.cql.CQLStoreTest
Tests run: 35, Failures: 0, Errors: 13, Skipped: 0, Time elapsed: 240.101 sec <<< FAILURE! - in org.janusgraph.diskstorage.cql.CQLStoreTest
deleteColumnsTest1(org.janusgraph.diskstorage.cql.CQLStoreTest)  Time elapsed: 0.013 sec  <<< ERROR!
java.lang.NullPointerException: null
	at org.janusgraph.diskstorage.cql.CQLStoreManager.clearStorage(CQLStoreManager.java:346)
	at org.janusgraph.diskstorage.KeyColumnValueStoreTest.setUp(KeyColumnValueStoreTest.java:68)
	at sun.reflect.GeneratedMethodAccessor3.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:24)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.mockito.internal.runners.JUnit45AndHigherRunnerImpl.run(JUnit45AndHigherRunnerImpl.java:37)
	at org.mockito.runners.MockitoJUnitRunner.run(MockitoJUnitRunner.java:62)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.createReqestAndRun(JUnitCoreWrapper.java:139)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.executeEager(JUnitCoreWrapper.java:111)
	at org.apache.maven.surefire.junitcore.JUnitCoreWrapper.execute(JUnitCoreWrapper.java:84)
	at org.apache.maven.surefire.junitcore.JUnitCoreProvider.invoke(JUnitCoreProvider.java:135)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
```

**Comment by pluradj** [comment]
I'm not clear why you would be hitting this problem still. It was reported with issue #1085 and fixed with PR #1090. Travis shows that the latest commit on `0.2` [builds successfully](https://travis-ci.org/JanusGraph/janusgraph/builds/394267251?utm_source=github_status&utm_medium=notification).

**Comment by pluradj** [comment]
Seems that you have an outdated build. `2a6072860` was merged on May 16. Try pulling the latest from `0.2` into your branch to make sure you get the latest fixes, including the one I mentioned above. Thanks.

**Comment by bukzor** [comment]
Thanks. You're correct that I was using outdated code. I'll try latest 0.2.

I notice that all parallelism is turned off in pom.xml. Do all devs run the tests serially? I tried cranking up the settings but perhaps I was too aggressive as the tests failed at an earlier spot with lock-held issues (I don't have the write on hand, sorry).

**Comment by pluradj** [comment]
I tend to only run specific modules locally, then once I'm satisfied I push the branch to GitHub to let Travis run all the tests in parallel.
