### ISSUE TITLE
Add support for Kerberized SOLR

### ISSUE THREAD

**Issue by blindenvy** [JanusGraph/janusgraph#1138]
Janus will fail to index data when using a kerberized SOLR as the indexing backend. For both modes: `CLOUD` and `HTTP` there is a need to set the appropriate configurations for kerberos in order for the SOLR client to successfully authenticate.

**Comment by blindenvy** [comment]
This is similar but different then #1056

**Comment by blindenvy** [comment]
The problematic code is in client creation starting around [line 242](https://github.com/JanusGraph/janusgraph/blob/6f7d300d8c739896eb4fb483d87535209353c9fc/janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java#L242) in the 0.2.0 release branch.

**Comment by hoda1369** [comment]
Any updates about this issue? I am trying to connect to kerberized Solr but it fails with:

Exception in thread "main" org.apache.solr.client.solrj.impl.HttpSolrClient$RemoteSolrException: Error from server at http://10.0.130.40:8983/solr: Expected mime type application/octet-stream but got text/html. <html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=utf-8"/>
<title>Error 401 require authentication</title>
</head>
<body><h2>HTTP ERROR 401</h2>
<p>Problem accessing /solr/admin/collections. Reason:
<pre>    require authentication</pre></p>
</body>
</html>

	at org.apache.solr.client.solrj.impl.HttpSolrClient.executeMethod(HttpSolrClient.java:591)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:253)
	at org.apache.solr.client.solrj.impl.HttpSolrClient.request(HttpSolrClient.java:242)
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.doRequest(LBHttpSolrClient.java:483)
	at org.apache.solr.client.solrj.impl.LBHttpSolrClient.request(LBHttpSolrClient.java:413)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.sendRequest(CloudSolrClient.java:1121)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.requestWithRetryOnStaleState(CloudSolrClient.java:862)
	at org.apache.solr.client.solrj.impl.CloudSolrClient.request(CloudSolrClient.java:793)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:178)
	at org.apache.solr.client.solrj.SolrRequest.process(SolrRequest.java:195)
	at org.janusgraph.diskstorage.solr.SolrIndex.createCollectionIfNotExists(SolrIndex.java:1085)
	at org.janusgraph.diskstorage.solr.SolrIndex.register(SolrIndex.java:314)
	at org.janusgraph.diskstorage.indexing.IndexTransaction.register(IndexTransaction.java:96)
	at org.janusgraph.graphdb.database.IndexSerializer.register(IndexSerializer.java:104)
	at org.janusgraph.graphdb.database.management.ManagementSystem.addIndexKey(ManagementSystem.java:529)
	at com.att.hypergraph.core.JanusGraphAdmin.addPropertyKeyToMixedIndex(JanusGraphAdmin.java:185)
	at com.att.hypergraph.core.JanusGraphAdmin.createSchemaMixedIndexes(JanusGraphAdmin.java:68)
	at com.att.hypergraph.core.CreateSchemaDriver.main(CreateSchemaDriver.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:750)
	at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:187)
	at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:212)
	at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:126)
	at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
