### ISSUE TITLE
: Could not find implementation class?

### ISSUE THREAD

**Issue by zhaochl** [JanusGraph/janusgraph#1186]
When I try to develop with Java as follows:

```java
JanusGraph graph = JanusGraphFactory.open("conf/janusgraph-hbase-es.properties");
GraphTraversalSource g = graph.traversal();

```

the following exception is thrown:

```
Exception in thread "main" java.lang.IllegalArgumentException: Could not find implementation class: org.janusgraph.diskstorage.es.ElasticSearchIndex
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:61)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:477)
	at org.janusgraph.diskstorage.Backend.getIndexes(Backend.java:464)
	at org.janusgraph.diskstorage.Backend.<init>(Backend.java:149)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1925)
	at org.janusgraph.graphdb.database.StandardJanusGraph.<init>(StandardJanusGraph.java:139)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:164)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:133)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:80)
```

Any Response will be welcome , thanks for reading my exceptions.

**Comment by pluradj** [comment]
Please provide the complete stack trace, in case there were other nested exceptions that you left out. Are you something like Apache Maven or Gradle for dependency management? If so, please provide the dependencies that you included.

**Comment by zhaochl** [comment]
Thanks 👍

**Comment by ZachMurray** [comment]
> @zhaochl please check the [version compatibility matrix](https://docs.janusgraph.org/latest/version-compat.html) and make sure you align the versions appropriately.
> 
> * JanusGraph 0.2.1 uses Apache TinkerPop 3.2.9
> * JanusGraph 0.3.0 uses Apache TinkerPop 3.3.3

This link is now broken. Is there a more recent standard-or-stable  link to use?

**Comment by porunov** [comment]
> > @zhaochl please check the [version compatibility matrix](https://docs.janusgraph.org/latest/version-compat.html) and make sure you align the versions appropriately.
> > 
> > * JanusGraph 0.2.1 uses Apache TinkerPop 3.2.9
> > * JanusGraph 0.3.0 uses Apache TinkerPop 3.3.3
> 
> This link is now broken. Is there a more recent standard-or-stable link to use?

https://docs.janusgraph.org/changelog/
