### ISSUE TITLE
SparkComputer serialization error with GeoShape and PageRank

### ISSUE THREAD

**Issue by jerryjch** [JanusGraph/janusgraph#1205]
In JanusGraph 0.3.0 SparkComputer has serialization error with GeoShape and PageRank.

```
gremlin> graph = GraphFactory.open('conf/hadoop-graph/read-hbase.properties')
==>hadoopgraph[hbaseinputformat->gryooutputformat]
gremlin> g = graph.traversal().withComputer(SparkGraphComputer)
==>graphtraversalsource[hadoopgraph[hbaseinputformat->gryooutputformat], sparkgraphcomputer]
gremlin> g.V().count()
==>12
```

But I was not able to get the pagerank to work. 
I tried to set  spark.kryo.registrator to different values, but neither worked for me.

```
spark.serializer=org.apache.spark.serializer.KryoSerializer
#spark.kryo.registrator=org.janusgraph.hadoop.serialize.JanusGraphKryoRegistrator
spark.kryo.registrator=org.apache.tinkerpop.gremlin.spark.structure.io.gryo.GryoRegistrator
```

```
gremlin> g.V().pageRank().valueMap()
22:42:32 WARN  org.apache.spark.storage.BlockManager  - Putting block rdd_2_0 failed due to an exception
22:42:32 WARN  org.apache.spark.storage.BlockManager  - Block rdd_2_0 could not be removed as it was not found on disk or in memory
22:42:32 ERROR org.apache.spark.executor.Executor  - Exception in task 0.0 in stage 1.0 (TID 1)
com.esotericsoftware.kryo.KryoException: java.lang.UnsupportedOperationException
Serialization trace:
readers (org.locationtech.spatial4j.io.SupportedFormats)
formats (org.locationtech.spatial4j.context.jts.JtsSpatialContext)
ctx (org.locationtech.spatial4j.shape.impl.PointImpl)
shape (org.janusgraph.core.attribute.Geoshape)
        at com.esotericsoftware.kryo.serializers.ObjectField.read(ObjectField.java:144)
...
```

When I have 
spark.kryo.registrator=org.janusgraph.hadoop.serialize.JanusGraphKryoRegistrator 

I got:
```
gremlin> g.V().pageRank().valueMap()
22:48:18 ERROR org.apache.spark.util.Utils  - Aborting task
java.lang.IllegalArgumentException: Class is not registered: org.janusgraph.core.attribute.Geoshape
Note: To register this class use: kryo.register(org.janusgraph.core.attribute.Geoshape.class);
        at org.apache.tinkerpop.shaded.kryo.Kryo.getRegistration(Kryo.java:484)
        at org.apache.tinkerpop.gremlin.structure.io.gryo.AbstractGryoClassResolver.writeClass(AbstractGryoClassResolver.java:110)
        at org.apache.tinkerpop.shaded.kryo.Kryo.writeClass(Kryo.java:514)
        at org.apache.tinkerpop.shaded.kryo.Kryo.writeClassAndObject(Kryo.java:619)
```
It can be easily re-producible with GraphOfGods that comes with JanusGraph.

It worked in JanusGraph 0.2.1 with spark.kryo.registrator=org.janusgraph.hadoop.serialize.JanusGraphKryoRegistrator

**Comment by jerryjch** [comment]
Related to #1194.

**Comment by LarryLp** [comment]
how can I deal with this probalem? use janusgraph 0.4.0  I need shortest path,and pagerank

**Comment by farodin91** [comment]
This solved by updating the documentation, see https://docs.janusgraph.org/advanced-topics/hadoop/.
