### ISSUE TITLE
Created index doesn't change it's status to REGISTERED in JanusGraph 0.3.0

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#1211]
I am trying to create an index with JanusGraph 0.3.0 but the status doesn't change to `REGISTERED`. If I use JanusGraph 0.2.1 or 0.2.0 index creation works, but with 0.3.0 it doesn't work.

After index creation I am waiting for the status of the index to be changed:
`ManagementSystem.awaitGraphIndexStatus(janusGraph, createdIndex.getIndexName()).call();
`
I am getting the next logs:
```
""2018-08-08 17:13:33 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index person_id_index do not currently have status(es) [REGISTERED]: real_id=INSTALLED
""2018-08-08 17:13:34 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index person_id_index do not currently have status(es) [REGISTERED]: real_id=INSTALLED
""2018-08-08 17:13:34 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index person_id_index do not currently have status(es) [REGISTERED]: real_id=INSTALLED
""2018-08-08 17:13:35 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index person_id_index do not currently have status(es) [REGISTERED]: real_id=INSTALLED
""2018-08-08 17:13:35 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index person_id_index do not currently have status(es) [REGISTERED]: real_id=INSTALLED
""2018-08-08 17:13:36 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index person_id_index do not currently have status(es) [REGISTERED]: real_id=INSTALLED
""2018-08-08 17:13:36 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index person_id_index do not currently have status(es) [REGISTERED]: real_id=INSTALLED
"Exception in thread "Thread-6" java.lang.NoClassDefFoundError: org/apache/tinkerpop/gremlin/server/GraphManager
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:467)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at org.janusgraph.graphdb.database.management.ManagementLogger$SendAckOnTxClose.run(ManagementLogger.java:240)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.ClassNotFoundException: org.apache.tinkerpop.gremlin.server.GraphManager
        at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at org.springframework.boot.loader.LaunchedURLClassLoader.loadClass(LaunchedURLClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 14 more
""2018-08-08 17:13:37 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index person_id_index do not currently have status(es) [REGISTERED]: real_id=INSTALLED
""2018-08-08 17:13:37 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index person_id_index do not currently have status(es) [REGISTERED]: real_id=INSTALLED
""2018-08-08 17:13:38 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index person_id_index do not currently have status(es) [REGISTERED]: real_id=INSTALLED

... // a lot of same logs

""2018-08-08 17:14:33 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index person_id_index do not currently have status(es) [REGISTERED]: real_id=INSTALLED
""2018-08-08 17:14:33 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Timed out (PT1M) while waiting for index person_id_index to converge on status(es) [REGISTERED]
```

If I try to reindex the created index after that I get an error. Reindexing:
`graphManagement.updateIndex(index, SchemaAction.REINDEX).get();`
An error:
`Exception was thrown when update index [person_id_index]`

Storage backend: ScyllaDB 2.2
Index backend: ElasticSearch 6.3.2

**Comment by porunov** [comment]
@pluradj sorry, but I think that this issue isn't a question and should be marked as `bug`.
New indexes do not change their status after their creation. I didn't ask "why" but rather showed that in the version 0.3.0 there was introduced a new bug which should be resolved. Also, I mentioned that there is no such bug in the earlier releases.

**Comment by porunov** [comment]
JanusGraph properties:
```
##############################################################
# General configuration
##############################################################
#gremlin.framedGraph=org.janusgraph.core.JanusGraphFactory
query.batch=true
query.fast-property=false
query.smart-limit=false
storage.batch-loading=true
storage.buffer-size=10240
#storage.cql.atomic-batch-mutate=true
storage.cql.batch-statement-size=200
schema.default = none
storage.connection-timeout=2400000
storage.read-time=2400000
storage.write-time=2400000
storage.cassandra.frame-size-mb=50
cassandra.thrift.framed.size_mb=50

##############################################################
# Storage configuration
##############################################################
storage.backend=cassandra
storage.hostname=graph.storage.com
storage.username=cassandra
storage.password=cassandra
storage.cassandra.astyanax.local-datacenter=USA_east_1

##############################################################
# Index search configuration
##############################################################
index.search.backend=elasticsearch
index.search.hostname=index.search.com
index.search.elasticsearch.create.sleep=10
index.search.elasticsearch.bulk-refresh=false

##############################################################
# Ids allocation configuration
##############################################################
ids.block-size=1000000
ids.flush=false
```

**Comment by pluradj** [comment]
Thanks for the properties, but what are your reproduce steps?

**Comment by porunov** [comment]
@pluradj Here are the steps to reproduce this issue with JanusGraph version 0.3.0 (versions 0.2.0 and 0.2.1 works with this test case but 0.3.0 fails):
```
JanusGraphManagement graphManagement = janusGraph.openManagement();

VertexLabelMaker vertexLabelMaker = graphManagement.makeVertexLabel("user");
vertexLabelMaker.make();

PropertyKeyMaker propertyKeyMaker = graphManagement.makePropertyKey("user_id");
propertyKeyMaker
        .dataType(Long.class)
        .cardinality(Cardinality.SINGLE)
        .make();

graphManagement.commit();

graphManagement = janusGraph.openManagement();

PropertyKey id = graphManagement.getPropertyKey("user_id");

VertexLabel vertexLabel = graphManagement.getVertexLabel("user");

graphManagement.buildIndex("my_id_index", Vertex.class).addKey(id).indexOnly(vertexLabel).buildCompositeIndex();

graphManagement.commit();

ManagementSystem.awaitGraphIndexStatus(janusGraph, "my_id_index").call();
```

**Comment by porunov** [comment]
Here is the error I am getting on ScyllaDB side when I use JanusGraph 0.3.0:
```
Aug 08 23:47:27 testvm scylla[2034]:  [shard 0] storage_proxy - Exception when communicating with 192.168.56.50: std::bad_alloc
Aug 08 23:47:27 testvm scylla[2034]:  [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_failure_exception (Operation failed for system.batchlog - received 0 responses and 1 failures from 1 CL=ONE.)
```

**Comment by pluradj** [comment]
I don't have a Scylla environment handy, but I don't think there were any major changes in the `cassandra` storage backend code.

**Comment by pluradj** [comment]
Have you tried using `cassandrathrift` or `cql` rather than `cassandra`?

**Comment by pluradj** [comment]
Is that a multi-DC Scylla? How many nodes in the cluster?

**Comment by porunov** [comment]
It is one node ScyllaDB cluster. No multi-DC.

I will try `cassandrathrift` and `cql` and will post results. But it is strange that 0.2.1 works with `cassandra` and 0.3.0 doesn't work. I do believe that there were some changes because I don't make any changes in my application except updating JanusGraph from `0.2.1` to `0.3.0`.

Could you try the above test case in your environment? Does it work with Cassandra?

**Comment by porunov** [comment]
The same problem with `cassandrathrift` as with `cassandra`.

**Comment by porunov** [comment]
If I try to use `cql` I get an error: 
`java.lang.IllegalArgumentException: Could not find implementation class: org.janusgraph.diskstorage.cql.CQLStoreManager`

**Comment by porunov** [comment]
This issue isn't connected with ScyllaDB. I tried to run the same test case in a different environment with Cassandra 3.0.9. Still I get the same problem. The index doesn't change its status to `REGISTERED` after index creation when we use JanusGraph 0.3.0. I believe that it is a bug on JanusGraph side.

**Comment by pluradj** [comment]
I ran this [example](https://github.com/pluradj/janusgraph-java-example/tree/issue-1211) using your code and properties on my local machine with Cassandra 3.11.3. I didn't include the Elasticsearch configuration since your example doesn't use mixed indexes.

It worked fine with either `cassandra` or `cassandrathrift`. If you want to try out `cql`, you'd need to include a dependency on `janusgraph-cql`.

```
14:59:57 INFO  org.janusgraph.core.util.ReflectiveConfigOptionLoader - Loaded and initialized config classes: 9 OK out of 13 attempts in PT0.012S
14:59:57 INFO  org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration - Set default timestamp provider MICRO
14:59:57 INFO  org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration - Generated unique-instance-id=091b61c371732-pluradj-mbp-2-raleigh-ibm-com1
14:59:57 INFO  org.janusgraph.diskstorage.Backend - Initiated backend operations thread pool of size 16
14:59:57 INFO  org.janusgraph.diskstorage.log.kcvs.KCVSLog - Loaded unidentified ReadMarker start time 2018-08-10T18:59:57.551Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@2611dd6b
14:59:58 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
14:59:59 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
14:59:59 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:00 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:00 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:01 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:01 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:02 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:02 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:03 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:03 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:04 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:04 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:05 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:05 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:06 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:06 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:07 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
15:00:07 INFO  org.janusgraph.graphdb.database.management.ManagementSystem$UpdateStatusTrigger - Set status REGISTERED on schema element my_id_index with property keys []
15:00:07 INFO  org.janusgraph.graphdb.database.management.ManagementLogger - Received all acknowledgements for eviction [1]
15:00:07 INFO  org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher - All 1 key(s) on index my_id_index have status(es) [REGISTERED]
```

**Comment by porunov** [comment]
@pluradj I've found a problem. To use JanusGraph 0.3.0 I should add an additional dependency:
`compile group: 'org.apache.tinkerpop', name: 'gremlin-server', version: '3.3.3'`

Thank you for helping!

**Comment by pluradj** [comment]
see also #1218

**Comment by sparshneel** [comment]
@porunov , 
I am getting this same issue. I am using Janusgraph 0.4.1.
These are the dependencies.
    compile group: 'org.janusgraph', name: 'janusgraph-core', version: '0.4.1'
    compile group: 'org.janusgraph', name: 'janusgraph-cql', version: '0.4.1'
    compile group: 'org.janusgraph', name: 'janusgraph-es', version: '0.4.1' 
    compile group: 'org.apache.tinkerpop', name: 'gremlin-driver', version: '3.4.4'

**Comment by porunov** [comment]
https://github.com/JanusGraph/janusgraph/issues/1211#issuecomment-412191673

**Comment by sparshneel** [comment]
@porunov 
i tried with same dependency it does not work, same issue. 

    compile group: 'org.janusgraph', name: 'janusgraph-core', version: '0.4.1'
    compile group: 'org.janusgraph', name: 'janusgraph-cql', version: '0.4.1'
    compile group: 'org.janusgraph', name: 'janusgraph-es', version: '0.4.1'
    compile group: 'org.apache.tinkerpop', name: 'gremlin-server', version: '3.4.1'

cn1EdgeIndexUnitTest           | Composite   | false     | internalindex  | pUnitTest1:  INSTALLED |
                               |             |           |                | pUnitTest2:  INSTALLED |
cn12EdgeIndexUnitTest          | Composite   | false     | internalindex  | pUnitTest1:  INSTALLED |
                               |             |           |                | pUnitTest2:  INSTALLED |
cn13EdgeIndexUnitTest          | Composite   | false     | internalindex  | pUnitTest1:  INSTALLED |
                               |             |           |                | pUnitTest2:  INSTALLED |

**Comment by porunov** [comment]
TinkerPop should be `3.4.4` for JanusGraph `0.4.1` : https://github.com/JanusGraph/janusgraph/blob/37b5291254067b8529f6a52d1dfd7d6145fff090/pom.xml#L72

Notice, this issue is talking about `ClassNotFoundException` which I believe is fixed for version `0.4.1` (notice, `0.4` branch isn't supported anymore). 

If you are getting the next `INFO` during index registration, it is totally fine:
```
""2018-08-08 22:31:09 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
```

**Comment by sparshneel** [comment]
i did try with 3.4.4 as well it did not work

**Comment by sparshneel** [comment]
> TinkerPop should be `3.4.4` for JanusGraph `0.4.1` :
> 
> https://github.com/JanusGraph/janusgraph/blob/37b5291254067b8529f6a52d1dfd7d6145fff090/pom.xml#L72
> 
> Notice, this issue is talking about `ClassNotFoundException` which I believe is fixed for version `0.4.1` (notice, `0.4` branch isn't supported anymore).
> 
> If you are getting the next `INFO` during index registration, it is totally fine:
> 
> ```
> ""2018-08-08 22:31:09 [main] INFO  o.j.g.d.m.GraphIndexStatusWatcher - Some key(s) on index my_id_index do not currently have status(es) [REGISTERED]: user_id=INSTALLED
> ```

okkk will

**Comment by KennFalcon** [comment]
@pluradj I've found a problem. To use JanusGraph 0.5.1. How to resolve it?

**Comment by HoangGiang28** [comment]
> @pluradj I've found a problem. To use JanusGraph 0.3.0 I should add an additional dependency:
> `compile group: 'org.apache.tinkerpop', name: 'gremlin-server', version: '3.3.3'`
> 
> Thank you for helping!

sorry but where should i add it into???

**Comment by phreed** [comment]
> @pluradj I've found a problem. To use JanusGraph 0.5.1. How to resolve it?
I am also having a similar problem with 0.5.3
I did not understand the solution to this issue.
