### ISSUE TITLE
Is this version conflict ?

### ISSUE THREAD

**Issue by wangzhubing** [JanusGraph/janusgraph#1224]
I met a problem，and  trouble  me for a long time. lots of people said it's version conflict. 
My install version:
spark-2.1.0-bin-hadoop2.7,
janusgraph-0.2.1-hadoop2,
hbase-1.2.6.1,
hadoop-2.6.5

when I operator like this:
graph = GraphFactory.open(/data/hadoop-graphson.properties')
writegraph='/data/janusgraph-test.properties'
 blvp = BulkLoaderVertexProgram.build().writeGraph(writegraph).create(graph)
graph.compute(SparkGraphComputer).program(blvp).submit().get()

problem:
Caused by: java.lang.NoSuchMethodError: org.apache.spark.api.java.JavaPairRDD.partitioner()Lcom/google/common/base/Optional;
	at org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputer.lambda$submitWithExecutor$0(SparkGraphComputer.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Comment by pluradj** [comment]
Most likely a version error. Refer to the [version compatibility matrix](https://docs.janusgraph.org/latest/version-compat.html) and also these updated docs on [configuring OLAP](https://docs.janusgraph.org/latest/hadoop-tp3.html).

@wangzhubing — please use GitHub only to report specific bugs or feature requests.

For general questions or open-ended discussion, please use either the Gitter channel or the `janusgraph-users@` mailing list: https://github.com/janusgraph/janusgraph/#community .
