### ISSUE TITLE
Use jBCrypt dependency from central

### ISSUE THREAD

**Issue by amcp** [JanusGraph/janusgraph#131]
I ran `mvn project-info-reports:dependencies` and got the following error a few times
Created ticket with sonatype to publish jBCrypt to central: https://issues.sonatype.org/browse/OSSRH-28388

Stack trace below

```
[INFO] Building JanusGraph-HBase: 0.98 Compatibility Shim 0.1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-project-info-reports-plugin:2.9:dependencies (default-cli) @ janusgraph-hbase-098 ---
[ERROR] Artifact com.github.jeremyh:jBCrypt:jar:jbcrypt-0.4 not found.
org.apache.maven.artifact.resolver.ArtifactNotFoundException: Failure to find com.github.jeremyh:jBCrypt:jar:jbcrypt-0.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

Try downloading the file manually from the project website.

Then, install it using the command: 
    mvn install:install-file -DgroupId=com.github.jeremyh -DartifactId=jBCrypt -Dversion=jbcrypt-0.4 -Dpackaging=jar -Dfile=/path/to/file

Alternatively, if you host your own repository you can deploy the file there: 
    mvn deploy:deploy-file -DgroupId=com.github.jeremyh -DartifactId=jBCrypt -Dversion=jbcrypt-0.4 -Dpackaging=jar -Dfile=/path/to/file -Durl=[url] -DrepositoryId=[id]


  com.github.jeremyh:jBCrypt:jar:jbcrypt-0.4

from the specified remote repositories:
  central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false),
  apache-snapshots (https://repository.apache.org/content/repositories/snapshots, releases=false, snapshots=true),
  sonatype-nexus-snapshots (https://oss.sonatype.org/content/repositories/snapshots, releases=false, snapshots=true),
  central (https://repo.maven.apache.org/maven2, releases=true, snapshots=false)

	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:221)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:154)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:555)
	at org.apache.maven.report.projectinfo.dependencies.RepositoryUtils.resolve(RepositoryUtils.java:153)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.resolveAtrifacts(DependenciesRenderer.java:1280)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderSectionDependencyFileDetails(DependenciesRenderer.java:513)
	at org.apache.maven.report.projectinfo.dependencies.renderer.DependenciesRenderer.renderBody(DependenciesRenderer.java:240)
	at org.apache.maven.reporting.AbstractMavenReportRenderer.render(AbstractMavenReportRenderer.java:83)
	at org.apache.maven.report.projectinfo.DependenciesReport.executeReport(DependenciesReport.java:201)
	at org.apache.maven.reporting.AbstractMavenReport.generate(AbstractMavenReport.java:255)
	at org.apache.maven.report.projectinfo.AbstractProjectInfoReport.execute(AbstractProjectInfoReport.java:234)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Failure to find com.github.jeremyh:jBCrypt:jar:jbcrypt-0.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
	at org.eclipse.aether.internal.impl.DefaultRepositorySystem.resolveArtifact(DefaultRepositorySystem.java:294)
	at org.apache.maven.artifact.resolver.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:215)
	... 32 more
Caused by: org.eclipse.aether.transfer.ArtifactNotFoundException: Failure to find com.github.jeremyh:jBCrypt:jar:jbcrypt-0.4 in https://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.newException(DefaultUpdateCheckManager.java:231)
	at org.eclipse.aether.internal.impl.DefaultUpdateCheckManager.checkArtifact(DefaultUpdateCheckManager.java:183)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.gatherDownloads(DefaultArtifactResolver.java:585)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:503)
	at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
	... 36 more
```

**Comment by pluradj** [comment]
This was fixed recently in Apache TinkerPop with https://issues.apache.org/jira/browse/TINKERPOP-1633

@dysmento would you like to submit a similar fix on JanusGraph?

**Comment by amcp** [comment]
@pluradj Good find. I will submit a PR for this

**Comment by amcp** [comment]
closed the sonatype jira

**Comment by amcp** [comment]
Appears to be fixed on TP master branch tracking 3.3 but not 3.2.3 nor 3.2.4 (the latest released versions). So depending on our release schedule and TP 3.3 release schedule, this may not get fixed in our first release. removing milestone from this issue

**Comment by amcp** [comment]
https://github.com/apache/tinkerpop/blame/master/gremlin-groovy/pom.xml#L69

**Comment by pluradj** [comment]
Ah, right. It came in immediately after the TP 3.2.4 release. In the meantime, we can add the JitPack repository https://jitpack.io/#jeremyh/jBCrypt/jbcrypt-0.4

**Comment by robertdale** [comment]
@amcp This issue should be resolved in master, 0.2-SNAPSHOT via #350 . Can you verify?

Then this should be removed from the pom.xml:
```
        <!-- the repositories below are included here for `mvn project-info-reports:dependencies` -->
        <repository>
            <!-- for com.github.jeremyh:jBCrypt:jar -->
            <id>jitpack.io</id>
            <name>JitPack Package Repository</name>
            <url>https://jitpack.io</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
```

**Comment by pluradj** [comment]
@robertdale I tested on master and verified it can be removed. Go ahead and open the pull request.

**Comment by kud1ing** [comment]
I am not sure: in the mean time is there a workaround for install JanusGraph 0.1.1 via MavenCentral until 0.2 is released?

**Comment by pluradj** [comment]
@kud1ing If you are using JanusGraph 0.1.1, the workaround is to include the jitpack repository (as shown above) in your application's Maven build if you need to include jBCrypt. See also [this thread](https://groups.google.com/d/msg/janusgraph-users/kGCfFcgE2Vs/50KgDvwcBwAJ) from janusgraph-users.

**Comment by kud1ing** [comment]
@pluradj Thank you.

 If anyone is using gradle, this worked for me: https://jitpack.io/p/jeremyh/JBCrypt
