### ISSUE TITLE
Use Client to run gremlin ->Note: To register this class use: kryo.register(org.janusgraph.graphdb.database.StandardJanusGraph.class);

### ISSUE THREAD

**Issue by lmcrazy** [JanusGraph/janusgraph#1325]
Please help to have a look, thanks!
I do not know how to config it with Cluster and  #Client.
my code is 
`
```
 GryoMapper.Builder builder = GryoMapper.build().addRegistry(JanusGraphIoRegistry.getInstance()).;
        MessageSerializer serializer = new GryoMessageSerializerV3d0(builder);
        Cluster cluster = Cluster.build().
                addContactPoint(contactPoint).
                maxWaitForConnection(300000).
                port(port).
                serializer(serializer).
                create();

        Client client = cluster.connect().init();
```
    client.submit("ConfiguredGraphFactory.open(\""+graph+"\");").all().get(10,TimeUnit.MINUTES).get(0).getObject();
`

![image](https://user-images.githubusercontent.com/9508140/49135085-a5be1100-f320-11e8-89df-f613e2733b24.png)

but it will bring an error:
`
2364178 [gremlin-server-exec-3] WARN  org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor  - The result [[standardjanusgraph[hbase:[172.16.161.115]]]] in the request a3af0d38-7be3-4881-85b7-ad788ed3df55 could not be serialized and returned.
org.apache.tinkerpop.gremlin.driver.ser.SerializationException: java.lang.IllegalArgumentException: Class is not registered: org.janusgraph.graphdb.database.StandardJanusGraph
Note: To register this class use: kryo.register(org.janusgraph.graphdb.database.StandardJanusGraph.class);
	at org.apache.tinkerpop.gremlin.driver.ser.AbstractGryoMessageSerializerV3d0.serializeResponseAsBinary(AbstractGryoMessageSerializerV3d0.java:193)
	at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.makeFrame(AbstractOpProcessor.java:266)
	at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.handleIterator(AbstractOpProcessor.java:146)
	at org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor.lambda$evalOpInternal$5(AbstractEvalOpProcessor.java:252)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:274)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.IllegalArgumentException: Class is not registered: org.janusgraph.graphdb.database.StandardJanusGraph
Note: To register this class use: kryo.register(org.janusgraph.graphdb.database.StandardJanusGraph.class);
	at org.apache.tinkerpop.shaded.kryo.Kryo.getRegistration(Kryo.java:484)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.AbstractGryoClassResolver.writeClass(AbstractGryoClassResolver.java:110)
	at org.apache.tinkerpop.shaded.kryo.Kryo.writeClass(Kryo.java:514)
	at org.apache.tinkerpop.shaded.kryo.Kryo.writeClassAndObject(Kryo.java:619)
	at org.apache.tinkerpop.shaded.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:100)
	at org.apache.tinkerpop.shaded.kryo.serializers.CollectionSerializer.write(CollectionSerializer.java:40)
	at org.apache.tinkerpop.shaded.kryo.Kryo.writeClassAndObject(Kryo.java:625)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.shaded.ShadedKryoAdapter.writeClassAndObject(ShadedKryoAdapter.java:49)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.shaded.ShadedKryoAdapter.writeClassAndObject(ShadedKryoAdapter.java:24)
	at org.apache.tinkerpop.gremlin.driver.ser.ResponseMessageGryoSerializer.write(ResponseMessageGryoSerializer.java:45)
	at org.apache.tinkerpop.gremlin.driver.ser.ResponseMessageGryoSerializer.write(ResponseMessageGryoSerializer.java:34)
	at org.apache.tinkerpop.gremlin.structure.io.gryo.kryoshim.shaded.ShadedSerializerAdapter.write(ShadedSerializerAdapter.java:44)
	at org.apache.tinkerpop.shaded.kryo.Kryo.writeObject(Kryo.java:531)
	at org.apache.tinkerpop.gremlin.driver.ser.AbstractGryoMessageSerializerV3d0.serializeResponseAsBinary(AbstractGryoMessageSerializerV3d0.java:177)
	... 10 more

`

**Comment by hefei1986** [comment]
Encountered same problem

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
