### ISSUE TITLE
an error when using janusgraph-0.3.0 + cdh5.14.2( hadoop2.6.0, hbase1.2.0) + spark2.2.0 for olap query

### ISSUE THREAD

**Issue by DongqingHan** [JanusGraph/janusgraph#1326]
Enviroment information: janusgraph-0.3.0 , hadoop2.6.0, hbase1.2.0, spark2.2.0;
spark run in Standalone mode with 1 master and 3 worker processes.
After necessary configuration as mention in [37.2.2. OLAP Traversals with Spark Standalone Cluster](https://docs.janusgraph.org/0.3.0/hadoop-tp3.html#_olap_traversals_with_spark_standalone_cluster), following Error occured when i executed the query:
```
gremlin> graph = GraphFactory.open('conf/hadoop-graphson-file.properties')
==>hadoopgraph[graphsoninputformat->nulloutputformat]
gremlin > g = graph.traversal().withComputer(SparkGraphComputer)
==>graphtraversalsource[hadoopgraph[graphsoninputformat->nulloutputformat], sparkgraphcomputer]
gremlin> g.V().count()
17:10:20 WARN  org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputer  - class org.apache.hadoop.mapreduce.lib.output.NullOutputFormat does not implement PersistResultGraphAware and thus, persistence options are unknown -- assuming all options are possible
[Stage 0:>                                    17:10:29 WARN  org.apache.spark.scheduler.TaskSetManager  - Lost task 41.0 in stage 0.0 (TID 41, 10.10.14.52, executor 0): java.lang.NoSuchMethodError: org.apache.hadoop.net.unix.DomainSocketWatcher.<init>(I)V
        at org.apache.hadoop.hdfs.shortcircuit.DfsClientShmManager.<init>(DfsClientShmManager.java:415)
        at org.apache.hadoop.hdfs.shortcircuit.ShortCircuitCache.<init>(ShortCircuitCache.java:379)
        at org.apache.hadoop.hdfs.ClientContext.<init>(ClientContext.java:96)
        at org.apache.hadoop.hdfs.ClientContext.get(ClientContext.java:145)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:627)
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:547)
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:139)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295)
        at org.apache.hadoop.mapreduce.lib.input.LineRecordReader.initialize(LineRecordReader.java:84)
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.graphson.GraphSONRecordReader.initialize(GraphSONRecordReader.java:57)
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.graphson.GraphSONInputFormat.createRecordReader(GraphSONInputFormat.java:42)
        at org.apache.spark.rdd.NewHadoopRDD$$anon$1.liftedTree1$1(NewHadoopRDD.scala:180)
        at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:179)
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:134)
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:69)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323)
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:87)
        at org.apache.spark.scheduler.Task.run(Task.scala:108)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:335)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
then i checked the log content of a spark worker, and get a more detailed error information as the flowing:
```
17:10:29.457 [Executor task launch worker for task 102] ERROR org.apache.spark.executor.Executor - Exception in task 49.3 in stage 0.0 (TID 102)
java.lang.NoSuchMethodError: org.apache.hadoop.net.unix.DomainSocketWatcher.<init>(I)V
        at org.apache.hadoop.hdfs.shortcircuit.DfsClientShmManager.<init>(DfsClientShmManager.java:415) ~[hbase-shaded-server-1.2.6.jar:1.2.6]
        at org.apache.hadoop.hdfs.shortcircuit.ShortCircuitCache.<init>(ShortCircuitCache.java:379) ~[hbase-shaded-server-1.2.6.jar:1.2.6]
        at org.apache.hadoop.hdfs.ClientContext.<init>(ClientContext.java:96) ~[hbase-shaded-server-1.2.6.jar:1.2.6]
        at org.apache.hadoop.hdfs.ClientContext.get(ClientContext.java:145) ~[hbase-shaded-server-1.2.6.jar:1.2.6]
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:627) ~[hbase-shaded-server-1.2.6.jar:1.2.6]
        at org.apache.hadoop.hdfs.DFSClient.<init>(DFSClient.java:547) ~[hbase-shaded-server-1.2.6.jar:1.2.6]
        at org.apache.hadoop.hdfs.DistributedFileSystem.initialize(DistributedFileSystem.java:139) ~[hbase-shaded-server-1.2.6.jar:1.2.6]
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2653) ~[hadoop-common-2.7.2.jar:na]
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92) ~[hadoop-common-2.7.2.jar:na]
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687) ~[hadoop-common-2.7.2.jar:na]
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669) ~[hadoop-common-2.7.2.jar:na]
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371) ~[hadoop-common-2.7.2.jar:na]
        at org.apache.hadoop.fs.Path.getFileSystem(Path.java:295) ~[hadoop-common-2.7.2.jar:na]
        at org.apache.hadoop.mapreduce.lib.input.LineRecordReader.initialize(LineRecordReader.java:84) ~[hbase-shaded-client-1.2.6.jar:1.2.6]
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.graphson.GraphSONRecordReader.initialize(GraphSONRecordReader.java:57) ~[hadoop-gremlin-3.3.3.jar:3.3.3]
        at org.apache.tinkerpop.gremlin.hadoop.structure.io.graphson.GraphSONInputFormat.createRecordReader(GraphSONInputFormat.java:42) ~[hadoop-gremlin-3.3.3.jar:3.3.3]
        at org.apache.spark.rdd.NewHadoopRDD$$anon$1.liftedTree1$1(NewHadoopRDD.scala:180) ~[spark-core_2.11-2.2.0.jar:2.2.0]
        at org.apache.spark.rdd.NewHadoopRDD$$anon$1.<init>(NewHadoopRDD.scala:179) ~[spark-core_2.11-2.2.0.jar:2.2.0]
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:134) ~[spark-core_2.11-2.2.0.jar:2.2.0]
        at org.apache.spark.rdd.NewHadoopRDD.compute(NewHadoopRDD.scala:69) ~[spark-core_2.11-2.2.0.jar:2.2.0]
        at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:323) ~[spark-core_2.11-2.2.0.jar:2.2.0]
        at org.apache.spark.rdd.RDD.iterator(RDD.scala:287) ~[spark-core_2.11-2.2.0.jar:2.2.0]
        at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38) 
        ...
```
as showing in the exception, all the relevent jars are comming from the lib fold of jansugraph0.3.0
```
[hdfs@cdh3 janusgraph_0.3.0_hadoop2/lib]$ grep 'DomainSocketWatcher' *
Binary file hadoop-common-2.7.2.jar matches
Binary file hbase-shaded-client-1.2.6.jar matches
Binary file hbase-shaded-server-1.2.6.jar matches
```
I suspect whether this is caused by the dismatch of hbase version, or some other conflict.
Expecting some one will give me a hint.

**Comment by liuyt-15** [comment]
I meet same trouble, but I use spark1.6.0. When I use spark1.6.1-assembly-hadoop2.6.0, it is normal.
I don't know the difference between spark1 and spark 2, but maybe JAR is wrong.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
