### ISSUE TITLE
Is there any limitations to load graphml data into janusGraph?

### ISSUE THREAD

**Issue by Miruoko** [JanusGraph/janusgraph#1355]
I exported my db from neo4j, and tried to load it in janusGraph. But an error throws out like this:
`org.apache.tinkerpop.gremlin.groovy.plugin.RemoteException: Illegal character ((CTRL-CHAR, code 11))
 at [row,col {unknown-source}]: [69309,751]
	at org.apache.tinkerpop.gremlin.console.groovy.plugin.DriverRemoteAcceptor.submit(DriverRemoteAcceptor.java:175)
at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.execute(GremlinGroovysh.groovy:99)
at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:122)
at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:95)
at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:152)
at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:124)
at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:59)
at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1213)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132)
at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:152)
at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:83)
at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:166)
at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:478)
`

and below is the row 69039: 

`<node id="n45532" labels=":Notes"><data key="labels">:Notes</data><data key="lastModified">2018-07-17T13:39:44Z</data><data key="lastModifiedUserId">VOEGELE@******.com</data><data key="name">Technical Decision Board</data><data key="attachments">[]</data><data key="_id">notes_SJxEgOsbOoQm</data><data key="content">Utilization of the IBM Global Network Peering Platform (IBM GNPP) is key to accomplish IBM overall strategy on cloud and hybrid cloud business. Utilization of the IBM GNPP drives standardization and innovation and is required to drive transformation for network environment and infrastructure. This is essential for propagating an environment for orchestration and automation capabilities. &lt;br&gt;&lt;br&gt;Technical Decision boardfor approval are the community of the IBM GNPP architects as also listed in the IBM GNPP Community Patricia Boerner, Mathias Diepelt, Gabor Klima, Marcel Koch, Robert Szabo, Markus Voegele, Matthias Weinreich (listed in alphabetic order).&lt;br&gt;&lt;br&gt;Technical Decision board meet as needed and regular once in each quarter Head and owner&lt;br&gt;of the meeting is Markus Voegele.&lt;br&gt;&lt;br&gt;Changes of the existing design and architecture IBM GNPP Platform design and architecture need to be mutually approved by lead architects Markus Voegele and Mathias Diepelt. The leader of MWS/GNPP Nadine von Schroeder must approve this decision and finally by Global Service Area Leader Integrated Networks Ulf-Carsten Geiser (in this order). &lt;br&gt;&lt;br&gt;The change is valid when both all approvals are given and the documentation is done. The documentation of change is with the lead architects mentioned above. Final decisions and decisions in case of clash between the architects is with “Global Service Area Leader Integrated Networks”. &lt;br&gt;&lt;br&gt;Documentation of architectural decisions are to be done in the IBM GNPP community https://apps.na.collabserv.com/wikis/home?lang=en- us#!/wiki/W16ce09b99707_4cf8_9ca3_f8c6b2f619ef/page/02%20Architectural%20Decisions &lt;br&gt;Decision who is going to be a strategic telecommunication provider partner (for MPLS peering)&lt;br&gt;for the Network Peering Points is a combined decision by:&lt;br&gt;&lt;br&gt;Ulf-Carsten Geiser&lt;br&gt;Rick Qualman&lt;br&gt;Nadine von Schroeders&lt;br&gt;&lt;font size="1"&gt;(listed in alphabetic order) &lt;br&gt;&lt;br&gt;&lt;/font&gt;The change is valid when both all approvals are given and the documentation is done.The documentation of change is with the Global Service Area Leader Integrated Networks.Current partner providers are to be found in the IBM GNPP community.Any changes need to be documented herehttps://apps.na.collabserv.com/wikis/home?lang=en- us#!/wiki/W2bab2515d866_4a90_934c_d9231a15c9e4/page/13.2.4%20MPLS%20Pr ovider%20Overview &lt;br&gt;&lt;br&gt;</data></node>
`

so I doubt if there is any limitations about the content? 
Or are there any other ways to migrate data from neo4j to janusGraph? Thanks for your help!

**Comment by jespersm** [comment]
First of all, judging from the error message, your XML file has been garbled (encoding). What are the characters at line 69309 around column 751?

Secondly, the error you're seeing isn't from JanusGraph, the GraphML support is part of Apache TinkerPop.

That being said, yes, there are limitations to how data is imported, where vertices should be imported before edges, or their labels won't get imported correctly. I read that somewhere, but I don't quite recall where...

**Comment by mingjinc** [comment]
@jespersm is there some native tool in janusgraph to import the graph data from other databases like neo4j?

**Comment by kevin-external** [comment]
@jespersm thanks for you advise! We will try the different options you provided.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
