### ISSUE TITLE
Error when connecting hbase and ES in java client

### ISSUE THREAD

**Issue by liuyt-15** [JanusGraph/janusgraph#1373]
when I run code：
```
        JanusGraph graph = JanusGraphFactory.build()
                                 .set("storage.backend", "hbase")
                                 .set("storage.hostname", "192.168.24.211")
                                 .set("storage.hbase.table", "janusgraph_test")
                                 .set("index.search.backend", "elasticsearch")
                                 .set("index.search.hostname", "192.168.24.211")
                                 .open();
        GraphTraversalSource g = graph.traversal();
        System.out.println(g.V().count());
```
I meet this error as belows.
I just need to connect cluster environment.
Do I need to set up a Hadoop Environment in my Desktop?
```
5:30:28.694 [main] INFO  o.j.d.hbase.HBaseCompatLoader - Instantiated HBase compatibility layer supporting runtime HBase version 1.2.0: org.janusgraph.diskstorage.hbase.HBaseCompat1_0
15:30:28.893 [main] DEBUG o.j.d.hbase.HBaseStoreManager - HBase configuration: set a total of 0 configuration values
15:30:28.893 [main] INFO  o.j.d.hbase.HBaseStoreManager - Copied host list from root.storage.hostname to hbase.zookeeper.quorum: 192.168.24.211
15:30:28.926 [main] DEBUG org.apache.hadoop.security.Groups -  Creating new Groups object
15:30:28.965 [main] DEBUG o.a.hadoop.util.NativeCodeLoader - Trying to load the custom-built native-hadoop library...
15:30:28.971 [main] DEBUG o.a.hadoop.util.NativeCodeLoader - Failed to load native-hadoop with error: java.lang.UnsatisfiedLinkError: no hadoop in java.library.path
15:30:28.971 [main] DEBUG o.a.hadoop.util.NativeCodeLoader - java.library.path=D:\setup\Java\jdk\bin;C:\WINDOWS\Sun\Java\bin;C:\WINDOWS\system32;C:\WINDOWS;D:\setup\scala12\bin;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;D:\setup\miktex\miktex\bin\x64\;D:\setup\java\jdk\bin;D:\setup\java\jdk\jre\bin;D:\setup\git\Git\cmd;D:\setup\git\Git\bin;D:\setup\bin;C:\WINDOWS\System32\OpenSSH\;D:\setup\nodejs\node_modules;D:\setup\nodejs\;D:\setup\scala\bin;D:\setup\python3;D:\setup\python3\Scripts\django-admin.exe;D:\setup\spark\spark-1.6.2-bin-hadoop2.6\bin;D:\setup\hadoop_base\hadoop-2.6.4\bin;D:\program\apache-maven-3.5.4-bin\apache-maven-3.5.4\bin;D:\setup\scala12\bin;D:\setup\python3\Scripts\;D:\setup\python3\;C:\Users\liuyt\AppData\Local\Microsoft\WindowsApps;C:\Users\liuyt\AppData\Roaming\npm;D:\setup\scala12\bin;D:\setup\scala12\bin;;.
15:30:28.971 [main] WARN  o.a.hadoop.util.NativeCodeLoader - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
15:30:28.971 [main] DEBUG o.a.h.s.JniBasedUnixGroupsMappingWithFallback - Falling back to shell based
15:30:28.972 [main] DEBUG o.a.h.s.JniBasedUnixGroupsMappingWithFallback - Group mapping impl=org.apache.hadoop.security.ShellBasedUnixGroupsMapping
15:30:29.086 [main] DEBUG org.apache.hadoop.util.Shell - Failed to detect a valid hadoop home directory
java.io.IOException: Hadoop home directory D:\setup\hadoop_base\hadoop-2.6.4 does not exist, is not a directory, or is not an absolute path.
	at org.apache.hadoop.util.Shell.checkHadoopHome(Shell.java:312) [hbase-shaded-client-1.2.0.jar:1.2.0]
	at org.apache.hadoop.util.Shell.<clinit>(Shell.java:327) [hbase-shaded-client-1.2.0.jar:1.2.0]
	at org.apache.hadoop.util.StringUtils.<clinit>(StringUtils.java:78) [hbase-shaded-client-1.2.0.jar:1.2.0]
	at org.apache.hadoop.security.Groups.parseStaticMapping(Groups.java:93) [hbase-shaded-client-1.2.0.jar:1.2.0]
	at org.apache.hadoop.security.Groups.<init>(Groups.java:77) [hbase-shaded-client-1.2.0.jar:1.2.0]
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:240) [hbase-shaded-client-1.2.0.jar:1.2.0]
	at org.apache.hadoop.security.Groups.getUserToGroupsMappingService(Groups.java:225) [hbase-shaded-client-1.2.0.jar:1.2.0]
	at org.apache.hadoop.hbase.security.UserProvider.<clinit>(UserProvider.java:56) [hbase-shaded-client-1.2.0.jar:1.2.0]
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:214) [hbase-shaded-client-1.2.0.jar:1.2.0]
	at org.apache.hadoop.hbase.client.ConnectionFactory.createConnection(ConnectionFactory.java:119) [hbase-shaded-client-1.2.0.jar:1.2.0]
	at org.janusgraph.diskstorage.hbase.HBaseCompat1_0.createConnection(HBaseCompat1_0.java:43) [janusgraph-hbase-0.2.2.jar:na]
	at org.janusgraph.diskstorage.hbase.HBaseStoreManager.<init>(HBaseStoreManager.java:326) [janusgraph-hbase-0.2.2.jar:na]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) [na:1.8.0_171]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) [na:1.8.0_171]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) [na:1.8.0_171]
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) [na:1.8.0_171]
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58) [janusgraph-core-0.2.2.jar:na]
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:477) [janusgraph-core-0.2.2.jar:na]
	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:409) [janusgraph-core-0.2.2.jar:na]
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1382) [janusgraph-core-0.2.2.jar:na]
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:164) [janusgraph-core-0.2.2.jar:na]
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:133) [janusgraph-core-0.2.2.jar:na]
```

**Comment by liuyt-15** [comment]
Actually, this problem does not influence result.
