### ISSUE TITLE
python client.submit

### ISSUE THREAD

**Issue by aofengli** [JanusGraph/janusgraph#1381]
this is my code 
```python
client = client.Client( 'ws://127.0.0.1:8182/gremlin',  'ConfigurationManagementGraph')
client.submit('ConfiguredGraphFactory.create("graph")')
```
this results is 
```shell
122838 [gremlin-server-exec-1] WARN  org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV2d0  - Response [ResponseMessage{requestId=fa6c3335-eebc-4978-a324-99797a004c5e, status=ResponseStatus{code=SUCCESS, message='', attributes={}}, result=ResponseResult{data=[standardjanusgraph[hbase:[172.16.102.195]]], meta={}}}] could not be serialized by org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV2d0.
org.apache.tinkerpop.shaded.jackson.databind.JsonMappingException: Could not find a type identifier for the class : class org.janusgraph.diskstorage.common.DistributedStoreManager$Deployment. Make sure the value to serialize has a type identifier registered for its class. (through reference chain: java.util.ArrayList[0]->org.janusgraph.graphdb.database.StandardJanusGraph["backend"]->org.janusgraph.diskstorage.Backend["storeManager"]->org.janusgraph.diskstorage.hbase.HBaseStoreManager["deployment"])
	at org.apache.tinkerpop.shaded.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:391)
	at org.apache.tinkerpop.shaded.jackson.databind.JsonMappingException.wrapWithPath(JsonMappingException.java:351)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.std.StdSerializer.wrapAndThrow(StdSerializer.java:316)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:727)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:604)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:729)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:604)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.BeanPropertyWriter.serializeAsField(BeanPropertyWriter.java:729)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.std.BeanSerializerBase.serializeFields(BeanSerializerBase.java:719)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.std.BeanSerializerBase.serializeWithType(BeanSerializerBase.java:604)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.impl.IndexedListSerializer.serializeTypedContents(IndexedListSerializer.java:181)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:92)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.impl.IndexedListSerializer.serializeContents(IndexedListSerializer.java:18)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.std.AsArraySerializerBase.serializeWithType(AsArraySerializerBase.java:261)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.impl.TypeWrappedSerializer.serialize(TypeWrappedSerializer.java:32)
	at org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV2d0$ResponseMessageSerializer.ser(AbstractGraphSONMessageSerializerV2d0.java:276)
	at org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV2d0$ResponseMessageSerializer.serializeWithType(AbstractGraphSONMessageSerializerV2d0.java:250)
	at org.apache.tinkerpop.gremlin.driver.ser.AbstractGraphSONMessageSerializerV2d0$ResponseMessageSerializer.serializeWithType(AbstractGraphSONMessageSerializerV2d0.java:235)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.impl.TypeWrappedSerializer.serialize(TypeWrappedSerializer.java:32)
	at org.apache.tinkerpop.shaded.jackson.databind.ser.Defau
```
but my hbase table is create success.
why?
I hope your can get help.

**Comment by aofengli** [comment]
@kedarmhaswade @tonit @sduskis @Lakedaemon

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.

**Comment by arneboe** [comment]
I have the same issue. Any hints?

**Comment by FabricioCabeca** [comment]
@arneboe you may try adding ;[] to the end of the query, so it will not try to serialize the database object returned
