### ISSUE TITLE
order().by() doesn't work with mixed index for String keys

### ISSUE THREAD

**Issue by mad** [JanusGraph/janusgraph#1396]
Janusgraph 0.3.1
```
graph = JanusGraphFactory.build().
set("storage.backend","inmemory").
set("index.search.backend","lucene").
set("index.search.directory","indexRootPath").
set("schema.default","none").
open()
g = graph.traversal()
mgmt = graph.openManagement()
stringProperty = mgmt.makePropertyKey('stringPropertyKey').cardinality(Cardinality.SINGLE).dataType(String.class).make()
mgmt.buildIndex("custom", Vertex.class).addKey(stringProperty, Mapping.STRING.asParameter()).buildMixedIndex("search")
mgmt.commit()
g.addV().property('stringPropertyKey','a')
g.addV().property('stringPropertyKey','b')
g.addV().property('stringPropertyKey','c')
g.tx().commit()
g.V().has("stringPropertyKey", "b").order().by("stringPropertyKey")
```

Cause to:

```
Caused by: java.lang.IllegalStateException: unexpected docvalues type NONE for field 'stringPropertyKey' (expected=SORTED). Re-index with correct docvalues type.
    at org.apache.lucene.index.DocValues.checkField(DocValues.java:340)
    at org.apache.lucene.index.DocValues.getSorted(DocValues.java:392)
    at org.apache.lucene.search.FieldComparator$TermOrdValComparator.getSortedDocValues(FieldComparator.java:709)
    at org.apache.lucene.search.FieldComparator$TermOrdValComparator.getLeafComparator(FieldComparator.java:714)
    at org.apache.lucene.search.FieldValueHitQueue.getComparators(FieldValueHitQueue.java:180)
    at org.apache.lucene.search.TopFieldCollector$SimpleFieldCollector.getLeafCollector(TopFieldCollector.java:100)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:649)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:462)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:581)
    at org.apache.lucene.search.IndexSearcher.searchAfter(IndexSearcher.java:566)
    at org.apache.lucene.search.IndexSearcher.search(IndexSearcher.java:493)
    at org.janusgraph.diskstorage.lucene.LuceneIndex.query(LuceneIndex.java:467)
    at org.janusgraph.diskstorage.indexing.IndexTransaction.queryStream(IndexTransaction.java:108)
    at org.janusgraph.diskstorage.BackendTransaction$6.call(BackendTransaction.java:417)
    at org.janusgraph.diskstorage.BackendTransaction$6.call(BackendTransaction.java:414)
    at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
    ... 73 more
```

related issue https://github.com/JanusGraph/janusgraph/issues/252

**Comment by porunov** [comment]
Fixed by #1469
