### ISSUE TITLE
JanusGraphTransaction#getVertex throws exception when vertex does not exist

### ISSUE THREAD

**Issue by mbbeaubi** [JanusGraph/janusgraph#1415]
According to the javadocs this method should return null if the vertex does not exist, instead it throws an exception due to an assertion error in the guava cache:

java.lang.AssertionError: Should not happen: CacheLoader returned null for key 82931045.
at org.janusgraph.graphdb.transaction.vertexcache.GuavaVertexCache.get(GuavaVertexCache.java:84)
at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.getVertex(StandardJanusGraphTx.java:394)

**Comment by mbbeaubi** [comment]
Even worse, if you enable batch loading StandardJanusGraphTx#getVertices(long...) will throw an exception because it skips the existence check.

Janus needs to handle this more gracefully. I had to disable batch loading for my entire application because of this. I see no reason why janus can't filter out cache misses for this API, which is the behavior when batch loading is disabled.

**Comment by farodin91** [comment]
Why are using not the gremlin?
StandardJanusGraphTx.getVertex should be only used internally.

Could you provide a better code example?

**Comment by mbbeaubi** [comment]
I was looking up a single vertex by its long id. The getVertex API is more convenient because I just want the single vertex back, not an iterable or iterator.

I switched to getVertices, which is what will be called internally if I go through gremlin. Is it the official recommendation that all janus calls go through gremlin? I prefer to use the janus APIs directly when they make sense as I feel that some of the gremlin query re-writing can be a little un-predictable. 

Anyways, there's 2 for sure bugs here that need to be addressed, using gremlin won't fix them:

1. The javadoc for getVertex is wrong as it states that it will return null if the vertex doesn't exist. Either we should fix the javadoc or we should fix the method. I would prefer fixing the method, but I'm not sure if anyone is relying on the exception throwing behavior, I would assume not as it's an undeclared assert error.
2. getVertices should not throw an exception when a vertex doesn't exist and batch loading is enabled. I get that we are skipping the existence check to help performance, but once we determine that the vertex doesn't exist, it should just be removed from the response. There's no good reason for having it behave differently when batch loading is enabled.

**Comment by farodin91** [comment]
> Is it the official recommendation that all janus calls go through gremlin?

https://groups.google.com/forum/#!topic/gremlin-users/V5vqs4wcjKQ -> Finally, with TinkerPop encouraging users to only write Gremlin when interacting with their graph
here is an issue to change the doc: https://github.com/JanusGraph/janusgraph/issues/1108

> Anyways, there's 2 for sure bugs here that need to be addressed, using gremlin won't fix them:

We shouldn't throw an exception. This changes the behaviour, so should put this into 0.4.0 release.

Do you like to contribute?

**Comment by mbbeaubi** [comment]
Sure, I'll make a patch, I just wanted to make sure that Janus folks agree with me that this is a bug.

**Comment by daefresh** [comment]
Yup. I'm getting the same issue. Any possibility this will be resolved in the upcoming release?

**Comment by li-boxuan** [comment]
@daefresh There is no concrete plan, but if you or @mbbeaubi wants to submit a PR, we would be happy to review.
