### ISSUE TITLE
Maximum limit of the size of the vertex's property?

### ISSUE THREAD

**Issue by xzdandy** [JanusGraph/janusgraph#1449]
I was storing images (base64 encoded to a UTF-8 string) as one of the vertex's property value. I found when I had a large image (the converted string was very long), Janusgraph threw exceptions and I was not able to add the vertex.

So does there exist a maximum limit of size/length of the vertex's property? Or is this caused by other reasons?

I am using withremote to write into a janusgraph server. Maybe socket level problems? The exception is below:

java.lang.IllegalStateException: java.io.IOException: Connection reset by peer
	at org.apache.tinkerpop.gremlin.process.remote.traversal.step.map.RemoteStep.processNextStart(RemoteStep.java:77)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.next(DefaultTraversal.java:200)

Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.write0(Native Method)
	at sun.nio.ch.SocketDispatcher.write(SocketDispatcher.java:47)
	at sun.nio.ch.IOUtil.writeFromNativeBuffer(IOUtil.java:93)
	at sun.nio.ch.IOUtil.write(IOUtil.java:51)
	at sun.nio.ch.SocketChannelImpl.write(SocketChannelImpl.java:471)
	at io.netty.channel.socket.nio.NioSocketChannel.doWrite(NioSocketChannel.java:288)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.flush0(AbstractChannel.java:879)
	at io.netty.channel.nio.AbstractNioChannel$AbstractNioUnsafe.forceFlush(AbstractNioChannel.java:319)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:640)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at java.lang.Thread.run(Thread.java:748)

**Comment by FlorianHockmann** [comment]
Please check the server side log (`gremlin-server.log`) for additional information about this problem. It should contain an exception with a stack trace.
I don't think that JanusGraph has a size limit for properties, but your backend could of course have one.

In the future, please use our [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) group to ask questions like this. We only use issues for bug reports or feature requests.
If a question leads to the discovery of a bug, then we can still create a bug report afterwards.

**Comment by wangxin12** [comment]
@xzdandy  Do you find the solution?

**Comment by xzdandy** [comment]
@wangxin12 Instead of storing images directly as an attribute of the vertex, I later stored them on disk and a pointer to them on each vertex.
