### ISSUE TITLE
TinkerPop tests failing due to Vertex equality check

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#1466]
Three TinkerPop tests are currently failing on `master`:

```java
[ERROR] Tests run: 929, Failures: 2, Errors: 1, Skipped: 264, Time elapsed: 145.955 s <<< FAILURE! - in org.janusgraph.blueprints.InMemoryJanusGraphStructureTest
[ERROR] shouldRemoveEdges  Time elapsed: 0.269 s  <<< FAILURE!
java.lang.AssertionError: expected:<199> but was:<200>
	at org.apache.tinkerpop.gremlin.structure.GraphTest.shouldRemoveEdges(GraphTest.java:895)
[ERROR] shouldCommitPropertyAutoTransactionByDefault  Time elapsed: 0.216 s  <<< ERROR!
java.lang.IllegalStateException: The property does not exist as the key has no associated value for the provided element: e[t8-3c0-t1-3c0][4320-l->4320]:name
	at org.apache.tinkerpop.gremlin.structure.TransactionTest.shouldCommitPropertyAutoTransactionByDefault(TransactionTest.java:319)
[ERROR] shouldRollbackPropertyAutoTransactionByDefault  Time elapsed: 0.117 s  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[yyy]> but was:<[xxx]>
	at org.apache.tinkerpop.gremlin.structure.TransactionTest.shouldRollbackPropertyAutoTransactionByDefault(TransactionTest.java:360)
```

This can be reproduced with:

```bash
mvn clean install -pl janusgraph-test -am -Dtest.skip.tp=false -DskipTests=true
```

I used [`git bisect`](https://git-scm.com/docs/git-bisect) to find the commit that introduced these failures and it was [this one](https://github.com/JanusGraph/janusgraph/commit/27e2c906439234f955a0df6276a647c18c0631fd).

The problematic change was the change of [this line](https://github.com/JanusGraph/janusgraph/pull/1118/files#diff-2cf9bf0eb13b598adc3706e714067159L43) from:

```java
if (v == v.it())
```

to:

```java
if (v.it().equals(v)) {
```

If that line is changed back, then the tests pass again.

**Comment by FlorianHockmann** [comment]
Fixed in #1505
