### ISSUE TITLE
Close transaction during execution lead to excetpion on berkeleyje backend

### ISSUE THREAD

**Issue by mad** [JanusGraph/janusgraph#1481]
I need to interrupt long running queries, and if I just rollback tx then getting exception:

```
Caused by: java.lang.IllegalStateException: Transaction 481 detected open cursors while aborting
	at com.sleepycat.je.txn.Txn.abortInternal(Txn.java:1256)
	at com.sleepycat.je.txn.Txn.abort(Txn.java:1160)
	at com.sleepycat.je.txn.Txn.abort(Txn.java:1133)
	at com.sleepycat.je.Transaction.abort(Transaction.java:220)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJETx.rollback(BerkeleyJETx.java:69)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.rollback(CacheTransaction.java:203)
	at org.janusgraph.diskstorage.BackendTransaction.rollback(BackendTransaction.java:170)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.rollback(StandardJanusGraphTx.java:1407)
	... 48 more
```

I think root cause is that BerkeleyJETx/BerkeleyJEKeyValueStore not proper handle openCursors fields, that field not updated instead cursors directly created in BerkeleyJEKeyValueStore

Sample of code to reproduce it
```
graph = JanusGraphFactory.open("berkeleyje:/tmp/jg")

mgmt = graph.openManagement()
a = mgmt.makePropertyKey('a').cardinality(Cardinality.SINGLE).dataType(String.class).make()
mgmt.buildIndex("composite", Vertex.class).addKey(a).buildCompositeIndex()
mgmt.commit()

g = graph.traversal()
clock(1000000) { g.addV().property("a", "2").next() }
g.tx().commit()

g = graph.tx().createThreadedTx().traversal()
Thread.start { g.V().has("a", "2").toList().size() }
sleep(100)
g.tx().rollback()
```

Result
```

         \,,,/
         (o o)
-----oOOo-(3)-oOOo-----
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/pavele/work/janusgraph-0.3.1-hadoop2/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/pavele/work/janusgraph-0.3.1-hadoop2/lib/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
plugin activated: janusgraph.imports
plugin activated: tinkerpop.server
plugin activated: tinkerpop.utilities
16:17:47 WARN  org.apache.hadoop.util.NativeCodeLoader  - Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
plugin activated: tinkerpop.hadoop
plugin activated: tinkerpop.spark
plugin activated: tinkerpop.tinkergraph
gremlin> graph = JanusGraphFactory.open("berkeleyje:/tmp/jg")
==>standardjanusgraph[berkeleyje:/tmp/jg]
gremlin> 
gremlin> mgmt = graph.openManagement()
==>org.janusgraph.graphdb.database.management.ManagementSystem@28f9fedd
gremlin> a = mgmt.makePropertyKey('a').cardinality(Cardinality.SINGLE).dataType(String.class).make()
==>a
gremlin> mgmt.buildIndex("composite", Vertex.class).addKey(a).buildCompositeIndex()
==>composite
gremlin> mgmt.commit()
==>null
gremlin> 
gremlin> g = graph.traversal()
==>graphtraversalsource[standardjanusgraph[berkeleyje:/tmp/jg], standard]
gremlin> clock(1000000) { g.addV().property("a", "2").next() }
16:18:19 WARN  org.janusgraph.diskstorage.idmanagement.ConsistentKeyIDAuthority  - Temporary storage exception while acquiring id block - retrying in PT0.6S: org.janusgraph.diskstorage.TemporaryBackendException: Wrote claim for id block [40001, 50001) in PT0.443S => too slow, threshold is: PT0.3S
==>0.062819593048
gremlin> g.tx().commit()
==>null
gremlin> 
gremlin> g = graph.tx().createThreadedTx().traversal()
==>graphtraversalsource[standardjanusgraphtx[0x30523ae6], standard]
gremlin> Thread.start { g.V().has("a", "2").toList().size() }
==>Thread[Thread-18,5,main]
gremlin> sleep(100)
==>null
gremlin> g.tx().rollback()
Exception in thread "Thread-18" org.janusgraph.core.JanusGraphException: Could not call index
	at org.janusgraph.graphdb.util.SubqueryIterator.<init>(SubqueryIterator.java:68)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$3.execute(StandardJanusGraphTx.java:1295)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$3.execute(StandardJanusGraphTx.java:1190)
	at org.janusgraph.graphdb.query.QueryProcessor$LimitAdjustingIterator.getNewIterator(QueryProcessor.java:194)
	at org.janusgraph.graphdb.query.LimitAdjustingIterator.hasNext(LimitAdjustingIterator.java:68)
	at org.janusgraph.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:54)
	at org.janusgraph.graphdb.query.ResultSetIterator.<init>(ResultSetIterator.java:44)
	at org.janusgraph.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:66)
	at com.google.common.collect.Iterables$7.iterator(Iterables.java:613)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.executeGraphCentryQuery(JanusGraphStep.java:156)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$null$1(JanusGraphStep.java:95)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$new$2(JanusGraphStep.java:95)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:142)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.fill(Traversal.java:179)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.toList(Traversal.java:117)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal$toList.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at groovysh_evaluate$_run_closure1.doCall(groovysh_evaluate:3)
	at groovysh_evaluate$_run_closure1.doCall(groovysh_evaluate)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:264)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1034)
	at groovy.lang.Closure.call(Closure.java:418)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.run(Closure.java:499)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent failure in storage backend
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.getSlice(BerkeleyJEKeyValueStore.java:148)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter.getSlice(OrderedKeyValueStoreAdapter.java:69)
	at org.janusgraph.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:77)
	at org.janusgraph.diskstorage.BackendTransaction$5.call(BackendTransaction.java:399)
	at org.janusgraph.diskstorage.BackendTransaction$5.call(BackendTransaction.java:396)
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
	at org.janusgraph.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:470)
	at org.janusgraph.diskstorage.BackendTransaction.indexQuery(BackendTransaction.java:396)
	at org.janusgraph.graphdb.query.graph.MultiKeySliceQuery.execute(MultiKeySliceQuery.java:51)
	at org.janusgraph.graphdb.database.IndexSerializer.query(IndexSerializer.java:512)
	at org.janusgraph.graphdb.util.SubqueryIterator.<init>(SubqueryIterator.java:66)
	... 35 more
Caused by: java.lang.IllegalStateException: Transaction 481 has been closed.
	at com.sleepycat.je.txn.Txn.checkState(Txn.java:1991)
	at com.sleepycat.je.txn.Txn.lockInternal(Txn.java:531)
	at com.sleepycat.je.txn.Locker.nonBlockingLock(Locker.java:534)
	at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3606)
	at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3372)
	at com.sleepycat.je.dbi.CursorImpl.lockLNAndCheckDefunct(CursorImpl.java:2156)
	at com.sleepycat.je.dbi.CursorImpl.lockAndGetCurrent(CursorImpl.java:2081)
	at com.sleepycat.je.dbi.CursorImpl.getNext(CursorImpl.java:2585)
	at com.sleepycat.je.Cursor.retrieveNextNoDups(Cursor.java:3576)
	at com.sleepycat.je.Cursor.retrieveNext(Cursor.java:3334)
	at com.sleepycat.je.Cursor.getInternal(Cursor.java:1305)
	at com.sleepycat.je.Cursor.get(Cursor.java:1238)
	at com.sleepycat.je.Cursor.getNext(Cursor.java:1524)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.getSlice(BerkeleyJEKeyValueStore.java:145)
	... 46 more
Could not rollback transaction due to exception
Type ':help' or ':h' for help.
Display stack trace? [yN]y
org.janusgraph.core.JanusGraphException: Could not rollback transaction due to exception
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.rollback(StandardJanusGraphTx.java:1410)
	at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsTransaction$1.doRollback(JanusGraphBlueprintsTransaction.java:190)
	at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.rollback(AbstractTransaction.java:114)
	at org.apache.tinkerpop.gremlin.structure.Transaction$rollback$1.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:116)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:120)
	at groovysh_evaluate.run(groovysh_evaluate:3)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:71)
	at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:196)
	at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.super$3$execute(GremlinGroovysh.groovy)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
	at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.execute(GremlinGroovysh.groovy:72)
	at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:122)
	at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:95)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:165)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:130)
	at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:59)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:165)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:89)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:146)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:453)
Caused by: java.lang.IllegalStateException: Transaction 481 detected open cursors while aborting
	at com.sleepycat.je.txn.Txn.abortInternal(Txn.java:1256)
	at com.sleepycat.je.txn.Txn.abort(Txn.java:1160)
	at com.sleepycat.je.txn.Txn.abort(Txn.java:1133)
	at com.sleepycat.je.Transaction.abort(Transaction.java:220)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJETx.rollback(BerkeleyJETx.java:69)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.rollback(CacheTransaction.java:203)
	at org.janusgraph.diskstorage.BackendTransaction.rollback(BackendTransaction.java:170)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.rollback(StandardJanusGraphTx.java:1407)
	... 48 more
```

**Comment by mad** [comment]
Fixed in https://github.com/JanusGraph/janusgraph/pull/1676
