### ISSUE TITLE
path query leads dead loop

### ISSUE THREAD

**Issue by saralov** [JanusGraph/janusgraph#1616]
I hava a graph about 700,000 vertexes and 800,000 edges with JanusGraph v0.3.1。
when I execute a gremlin query like below to query paths between two vertexes, it blocked. I follow the source code, found it lead a dead loop when call "traversal.hasNext()":
g.V().hasId(8336).repeat(bothE().otherV().simplePath()).until(hasId(4168).loops().is(P.lte(3))).path()

following is thread dump:
"http-nio-13333-exec-1" Id=37 RUNNABLE
    at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37)
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
    at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192)
    at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.test(TraversalUtil.java:84)
    at org.apache.tinkerpop.gremlin.process.traversal.step.filter.AndStep.filter(AndStep.java:37)
    at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:38)
    at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
    at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192)
    at org.apache.tinkerpop.gremlin.process.traversal.util.TraversalUtil.test(TraversalUtil.java:84)

**Comment by FlorianHockmann** [comment]
I think your traversal simply lacks an `or()` step in the `until()` condition to connect the two conditions `hasId(4186)` and `loops().is(P.lte(3))`:

```groovy
g.V().hasId(8336).repeat(bothE().otherV().simplePath()).until(hasId(4168).or().loops().is(P.lte(3))).path()
```

In the future, please post first on [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) or ask in our [Gitter chat](https://gitter.im/janusgraph/janusgraph) as we use issues only for bug reports and feature requests. If a post there uncovers a bug, we can still create an issue here.

**Comment by saralov** [comment]
it works, thx!
