### ISSUE TITLE
Can the storage backends of JanusGraph be BerkeleyDB not BerkeleyDB JE ?

### ISSUE THREAD

**Issue by zhuguocheng29** [JanusGraph/janusgraph#1670]
I want to use JanusGraph on the Android. I used BerkeleyDB JE before, but there is the error due to Android does not support ManagementFactory as below : 

**java.lang.NoClassDefFoundError: Failed resolution of:Ljava/lang/management/ManagementFactory**

**Comment by pluradj** [comment]
Could you please include the full stack trace to show where the code is failing? Thank you.

**Comment by meteorlin** [comment]
After two days of trying, the current version of Janusgraph (from 0.1 to 0.5.x) is not suitable for running on Android because it lacks the necessary `java/lang/management/ManagementFactory`, and this class does not exist in the Android virtual machine.
At present, Janusgraph 0.5.x and above have cancelled the support for BerkeleyDB JE Android, because BerkeleyDB JE does not seem to support Android since version 6.4.25; while the version that supports Android cannot be compiled successfully due to age. In addition, I also tried to compile the latest version of BerkeleyDB JDBC For Android, but failed. (In fact, the BerkeleyDB JE version that I can find that can run on Android is 5.0.104, [see](https://github.com/FelixGV/bdb-je-5/blob/5a24b7e7a6168f036b778da64d31338e47bc64c9/lib/je-android-5.0.104.jar))
However, if `Janusgraph` and `BerkeleyDB JE 5.0.104-For Android` are tested separately, both can be successful. Isn’t this exciting? If Janusgraph can consider launching a version that does not depend on `java/lang/management/ManagementFactory`, that would be a wonderful thing. @pluradj 
Finally, attach the application I built and its stack trace information: ()
Gradle:app
```gradle
plugins {
    id 'com.android.application'
}

android {
    compileSdkVersion 29
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    defaultConfig {
        applicationId "com.koushikdutta.myapplication"
        minSdkVersion 26
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    packagingOptions {
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/INDEX.LIST'
        exclude 'META-INF/groovy-release-info.properties'
        exclude 'META-INF/groovy/org.codehaus.groovy.runtime.ExtensionModule'
    }
}

dependencies {

    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'com.google.android.material:material:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'

    testImplementation 'junit:junit:4.+'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    // Janusgraph
    implementation files('libs\\je-android-5.0.104.jar')
    implementation files('libs\\guava-30.1-android.jar')
    implementation files('libs\\janusgraph-berkeleyje-0.4.1.jar')
    implementation files('libs\\janusgraph-core-0.4.1.jar')
    annotationProcessor 'org.apache.tinkerpop:gremlin-driver:3.4.4'
    implementation 'org.apache.tinkerpop:gremlin-shaded:3.4.4'
    implementation 'org.apache.tinkerpop:tinkergraph-gremlin:3.4.4'
}
```
MainActivity.java
```java
package com.koushikdutta.myapplication;

import androidx.appcompat.app.AppCompatActivity;

import android.os.Bundle;

import org.janusgraph.core.JanusGraph;
import org.janusgraph.core.JanusGraphFactory;

import java.io.File;
import java.io.FileOutputStream;
import java.io.IOException;

public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        File envDir = this.getFilesDir();
        File paramFile = new File(this.getFilesDir(), "je.properties");
        if (!paramFile.exists()){
            try {
                FileOutputStream os = this.openFileOutput("je.properties",MODE_PRIVATE);
//                os.write("je.log.totalBufferBytes=7001\n".getBytes());
                os.close();
            } catch (IOException e) {
                e.printStackTrace();
            }
        }

        try {
            JanusGraph g = JanusGraphFactory.build().
                    set("storage.backend", "berkeleyje").
                    set("storage.directory", envDir.getCanonicalPath()).
                    open();
        } catch (IOException e) {
            e.printStackTrace();
        }

    }
}
```
Stack trace information
```
    java.lang.NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory;
        at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getSuffix(GraphDatabaseConfiguration.java:1500)
        at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.computeUniqueInstanceId(GraphDatabaseConfiguration.java:1531)
        at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getOrGenerateUniqueInstanceId(GraphDatabaseConfiguration.java:1543)
        at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1419)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:160)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:131)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:121)
        at org.janusgraph.core.JanusGraphFactory$Builder.open(JanusGraphFactory.java:260)
        at com.koushikdutta.myapplication.MainActivity.onCreate(MainActivity.java:37)
        at android.app.Activity.performCreate(Activity.java:7894)
        at android.app.Activity.performCreate(Activity.java:7881)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:224)
        at android.app.ActivityThread.main(ActivityThread.java:7560)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.lang.management.ManagementFactory" on path: DexPathList[[zip file "/data/app/com.koushikdutta.myapplication--tAy69fqX_6uX1KK-RCT_w==/base.apk"],nativeLibraryDirectories=[/data/app/com.koushikdutta.myapplication--tAy69fqX_6uX1KK-RCT_w==/lib/arm64, /system/lib64, /system/product/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:230)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getSuffix(GraphDatabaseConfiguration.java:1500) 
        at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.computeUniqueInstanceId(GraphDatabaseConfiguration.java:1531) 
        at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getOrGenerateUniqueInstanceId(GraphDatabaseConfiguration.java:1543) 
        at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1419) 
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:160) 
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:131) 
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:121) 
        at org.janusgraph.core.JanusGraphFactory$Builder.open(JanusGraphFactory.java:260) 
        at com.koushikdutta.myapplication.MainActivity.onCreate(MainActivity.java:37) 
        at android.app.Activity.performCreate(Activity.java:7894) 
        at android.app.Activity.performCreate(Activity.java:7881) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3283) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3457) 
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83) 
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135) 
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2044) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:224) 
        at android.app.ActivityThread.main(ActivityThread.java:7560) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:539) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950) 
```
