### ISSUE TITLE
gremlin-groovy is not an available GremlinScriptEngine

### ISSUE THREAD

**Issue by VINAYAK179** [JanusGraph/janusgraph#1685]
Sorry for asking the query here but I tried on google group and gitter but got no replies.
I am deploying janusgraph with cassandra on a single server but I am getting the following error: 

gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Configured localhost/127.0.0.1:8182
gremlin> :> ConfiguredGraphFactory.getGraphNames()
gremlin-groovy is not an available GremlinScriptEngine
Type ':help' or ':h' for help.
Display stack trace? [yN]y
java.lang.IllegalArgumentException: gremlin-groovy is not an available GremlinScriptEngine
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.registerLookUpInfo(CachedGremlinScriptEngineManager.java:95)
	at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.getEngineByName(CachedGremlinScriptEngineManager.java:58)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:266)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

Also can you please inform changes to be made in config files to deploy on server.

Thank You !!!

**Comment by VINAYAK179** [comment]
I issue was due to server configuration problem and solved.
