### ISSUE TITLE
BerkeleyDB TinkerPop test errors in  v7.3.7

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#171]
The update to BerkeleyDB JE 7.3.7 (https://github.com/JanusGraph/janusgraph/pull/101) causes numerous errors in TinkerPop test suites. To reproduce run the test suite with `test.skip.tp=false`.

```bash
mvn clean install -DskipTests
mvn verify -Dtest.skip.tp=false -pl janusgraph-berkeleyje
```

Failures are shown below.

```
Tests run: 19, Failures: 1, Errors: 17, Skipped: 0, Time elapsed: 8.599 sec <<< FAILURE! - in org.apache.tinkerpop.gremlin.process.traversal.TraversalInterruptionTest
Tests run: 2, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.001 sec <<< FAILURE! - in org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.TranslationStrategyProcessTest
Tests run: 24, Failures: 0, Errors: 24, Skipped: 0, Time elapsed: 0.013 sec <<< FAILURE! - in org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.ElementIdStrategyProcessTest
Tests run: 34, Failures: 0, Errors: 34, Skipped: 0, Time elapsed: 0.047 sec <<< FAILURE! - in org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.EventStrategyProcessTest
Tests run: 22, Failures: 0, Errors: 22, Skipped: 0, Time elapsed: 0.025 sec <<< FAILURE! - in org.apache.tinkerpop.gremlin.process.traversal.strategy.verification.ReadOnlyStrategyProcessTest
Tests run: 36, Failures: 0, Errors: 36, Skipped: 0, Time elapsed: 0.047 sec <<< FAILURE! - in org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.PartitionStrategyProcessTest
Tests run: 16, Failures: 0, Errors: 16, Skipped: 0, Time elapsed: 0.025 sec <<< FAILURE! - in org.apache.tinkerpop.gremlin.process.traversal.strategy.decoration.SubgraphStrategyProcessTest
```

The errors have the following form.

```
java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager
        at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:69)
        at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:480)
        at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:414)
        at org.janusgraph.diskstorage.Backend.<init>(Backend.java:148)
        at org.janusgraph.graphdb.JanusGraphBaseTest.clearGraph(JanusGraphBaseTest.java:85)
...
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Error during BerkeleyJE initialization: 
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.initialize(BerkeleyJEStoreManager.java:126)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.<init>(BerkeleyJEStoreManager.java:82)
...
Caused by: com.sleepycat.je.ThreadInterruptedException: (JE 7.3.7) Environment must be closed, caused by: com.sleepycat.je.ThreadInterruptedException: Environment invalid because of previous exception: (JE 7.3.7) target/db/standard java.lang.InterruptedException THREAD_INTERRUPTED: InterruptedException may cause incorrect internal state, unable to continue. Environment is invalid and must be closed.
        at com.sleepycat.je.ThreadInterruptedException.wrapSelf(ThreadInterruptedException.java:105)
        at com.sleepycat.je.dbi.EnvironmentImpl.checkIfInvalid(EnvironmentImpl.java:1766)
        at com.sleepycat.je.dbi.DbEnvPool.getEnvironment(DbEnvPool.java:151)
        at com.sleepycat.je.Environment.makeEnvironmentImpl(Environment.java:267)
        at com.sleepycat.je.Environment.<init>(Environment.java:252)
        at com.sleepycat.je.Environment.<init>(Environment.java:222)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.initialize(BerkeleyJEStoreManager.java:122)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.<init>(BerkeleyJEStoreManager.java:82)
...
Caused by: com.sleepycat.je.ThreadInterruptedException: Environment invalid because of previous exception: (JE 7.3.7) target/db/standard java.lang.InterruptedException THREAD_INTERRUPTED: InterruptedException may cause incorrect internal state, unable to continue. Environment is invalid and must be closed.
        at com.sleepycat.je.latch.SharedLatchImpl.acquireShared(SharedLatchImpl.java:109)
        at com.sleepycat.je.txn.TxnManager.registerTxn(TxnManager.java:213)
        at com.sleepycat.je.txn.Txn.initTxn(Txn.java:392)
        at com.sleepycat.je.txn.Txn.<init>(Txn.java:286)
        at com.sleepycat.je.txn.Txn.<init>(Txn.java:265)
        at com.sleepycat.je.txn.Txn.createLocalTxn(Txn.java:292)
        at com.sleepycat.je.txn.Txn.createUserTxn(Txn.java:314)
        at com.sleepycat.je.txn.TxnManager.txnBegin(TxnManager.java:199)
        at com.sleepycat.je.dbi.EnvironmentImpl.txnBegin(EnvironmentImpl.java:2460)
        at com.sleepycat.je.Environment.beginTransactionInternal(Environment.java:1482)
        at com.sleepycat.je.Environment.beginTransaction(Environment.java:1367)
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.beginTransaction(BerkeleyJEStoreManager.java:152)
```

**Comment by sjudeng** [comment]
The root issue here is the TraversalInterruptionTest in the TP [ProcessStandardSuite](https://github.com/apache/tinkerpop/blob/3.2.3/gremlin-test/src/main/java/org/apache/tinkerpop/gremlin/process/ProcessStandardSuite.java#L178). Since interrupts are not supported in Berkeley JE (see [BerkeleyJEStoreManager](https://github.com/JanusGraph/janusgraph/blob/1e221be44ef14558a3503e008843e44c64fdec8d/janusgraph-berkeleyje/src/main/java/org/janusgraph/diskstorage/berkeleyje/BerkeleyJEStoreManager.java#L92) and [Berkeley JE FAQ](http://www.oracle.com/technetwork/database/berkeleydb/je-faq-096044.html#WhatisasafewaytostopthreadsinaJEapplication)) there are internal state errors in all tests after that suite runs. If I locally remove this suite from ProcessStandardSuite then all janusgraph-berkeleyje tests pass. It might be that more state validation is being performed in recent  BerkeleyDB versions, which is why this isn't a problem in the older v5.0.73.

It seems to me the easiest solution would be to exclude this suite from running through TP ProcessStandardSuite via BerkeleyJanusGraphProcessTest. Not sure if this is possible (@pluradj, @twilmes any ideas?). Interruption support does not appear to be an optional feature in TP (see [Interrupting Traversals](http://tinkerpop.apache.org/docs/3.2.3/upgrade/#_graph_system_providers_3)).

In the meantime I'll look at whether the state issues can be handled in janusgraph-berkeleyje to allow the suite to run.

**Comment by pluradj** [comment]
The TinkerPop way to do it is to add a `@Graph.OptOut` annotation into [`JanusGraph.java`](https://github.com/JanusGraph/janusgraph/blob/jg01/janusgraph-core/src/main/java/org/janusgraph/core/JanusGraph.java#L42). Side effect for JanusGraph though is that the `TraversalInterruptionTest` would not be run against any of the other storage backends either.

I think you're suggesting to change `BerkeleyJanusGraphProcessTest` to `@RunWith(BerkeleyProcessStandardSuite.class)` where `BerkeleyProcessStandardSuite extends ProcessStandardSuite` but doesn't include `TraversalInterruptionTest`. That sounds reasonable, and it should work fine.

We should add a note in the JanusGraph server docs about this interruption behavior.

**Comment by sjudeng** [comment]
I didn't want to go with `@OptOut` for exactly the reason you point out. It is too bad we're not able to opt out at the backend level in JanusGraph.

I can revisit possibly extending `ProcessStandardSuite`. When I initially looked at this it didn't seem ideal because it would likely require copying the full test list (which would be a maintenance issue) and/or using reflection to get at the underlying field (which is `private static final`).

**Comment by sjudeng** [comment]
PR #179 has been submitted to resolve this issue by using the custom `ProcessStandardSuite` as described above.

I did also look at resolving these test issues instead of skipping them. When running `TraversalInterruptionTest` in isolation all errors can be resolved by updating BerkeleyJEKeyValueStore to handle interrupts. But I was unable to consistently resolve errors observed when running the test class in combination with other `ProcessStandardSuite` test classes. These errors appeared to be associated with sporadic issues with the BerkeleyDB environment not being fully closed after interruption.

This could be revisited as part of #88. If at that time interrupts can be handled in BerkeleyDB (at least as far as fully cleaning up the environment) then the custom extension added in #179 could be removed.
