### ISSUE TITLE
Janusgraph + hbase +es initialziation failed

### ISSUE THREAD

**Issue by GangLiCN** [JanusGraph/janusgraph#1723]
[Env]
Janusgraph version: 0.4.0
hbase version:  1.4.10
Elasticsearch:  using embedded "elasticsearch" which is included in  "janusgraph-0.4.0-hadoop2zip".

[Reproduce steps]
1.  cd $JG_HOME/conf/gremlin-server

2.  Copy "janusgraph-cassandra-es-server.properties" to "janusgraph-hbase-es-server.properties"

3.  Edit "janusgraph-hbase-es-server.properties",  set  hbase and ES's storage host name/ip  in it:

4.  Copy "gremlin-server.yaml"  to " gremlin-hbase-es-server.yaml"

5.  Edit "gremlin-hbase-es-server.yaml"
update "graph:" line like below:
graph: conf/gremlin-server/janusgraph-hbase-es-server.properties

6.  Start gremlin-server:
cd $JG_HOME
bin/gremlin-server.sh  conf/gremlin-server/gremlin-hbase-es-server.yaml

7.  Many java exceptions shows as below:
......
2288 [main] WARN  org.janusgraph.diskstorage.hbase.HBaseStoreManager  - Unexpected exception during getDeployment()
java.lang.RuntimeException: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
        at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:379)
        at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getFeatures(HBaseStoreManager.java:418)
        at org.janusgraph.graphdb.configuration.builder.GraphDatabaseConfigurationBuilder.build(GraphDatabaseConfigurationBuilder.java:51)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:161)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:132)
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:112)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:78)
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:70)
        at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:104)
        at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.lambda$new$0(DefaultGraphManager.java:57)
        at java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
        at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.<init>(DefaultGraphManager.java:55)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:80)
......

Caused by: org.apache.hadoop.hbase.regionserver.NoSuchColumnFamilyException: org.apache.hadoop.hbase.regionserver.NoSuchColumnFamilyException: Column family table does not exist in region hbase:meta,,1.1588230740 in table 'hbase:meta', {TABLE_ATTRIBUTES => {IS_META => 'true', coprocessor$1 => '|org.apache.hadoop.hbase.coprocessor.MultiRowMutationEndpoint|536870911|'}, {NAME => 'info', BLOOMFILTER => 'NONE', VERSIONS => '3', IN_MEMORY => 'true', KEEP_DELETED_CELLS => 'FALSE', DATA_BLOCK_ENCODING => 'NONE', TTL => 'FOREVER', COMPRESSION => 'NONE', CACHE_DATA_IN_L1 => 'true', MIN_VERSIONS => '0', BLOCKCACHE => 'true', BLOCKSIZE => '8192', REPLICATION_SCOPE => '0'}
        at org.apache.hadoop.hbase.regionserver.HRegion.checkFamily(HRegion.java:8371)
        at org.apache.hadoop.hbase.regionserver.HRegion.get(HRegion.java:7363)
        at org.apache.hadoop.hbase.regionserver.RSRpcServices.get(RSRpcServices.java:2259)
        at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$2.callBlockingMethod(ClientProtos.java:36609)
        at org.apache.hadoop.hbase.ipc.RpcServer.call(RpcServer.java:2380)
        at org.apache.hadoop.hbase.ipc.CallRunner.run(CallRunner.java:124)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:297)
        at org.apache.hadoop.hbase.ipc.RpcExecutor$Handler.run(RpcExecutor.java:277)

        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.apache.hadoop.hbase.ipc.RemoteWithExtrasException.instantiateException(RemoteWithExtrasException.java:99)
        at org.apache.hadoop.hbase.ipc.RemoteWithExtrasException.unwrapRemoteException(RemoteWithExtrasException.java:89)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.makeIOExceptionOfException(ProtobufUtil.java:282)
        at org.apache.hadoop.hbase.protobuf.ProtobufUtil.handleRemoteException(ProtobufUtil.java:269)
        at org.apache.hadoop.hbase.client.RegionServerCallable.call(RegionServerCallable.java:129)
        at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
        at org.apache.hadoop.hbase.client.HTable.get(HTable.java:386)
         at org.apache.hadoop.hbase.client.HTable.get(HTable.java:360)
        at org.apache.hadoop.hbase.MetaTableAccessor.getTableState(MetaTableAccessor.java:1078)
        at org.apache.hadoop.hbase.MetaTableAccessor.tableExists(MetaTableAccessor.java:403)
        at org.apache.hadoop.hbase.client.HBaseAdmin$6.rpcCall(HBaseAdmin.java:450)
        at org.apache.hadoop.hbase.client.HBaseAdmin$6.rpcCall(HBaseAdmin.java:447)
        at org.apache.hadoop.hbase.client.RpcRetryingCallable.call(RpcRetryingCallable.java:58)
        at org.apache.hadoop.hbase.client.RpcRetryingCallerImpl.callWithRetries(RpcRetryingCallerImpl.java:107)
        at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3089)
        at org.apache.hadoop.hbase.client.HBaseAdmin.executeCallable(HBaseAdmin.java:3081)
        at org.apache.hadoop.hbase.client.HBaseAdmin.tableExists(HBaseAdmin.java:447)
        at org.janusgraph.diskstorage.hbase.HBaseAdmin1_0.tableExists(HBaseAdmin1_0.java:111)
        at org.janusgraph.diskstorage.hbase.HBaseStoreManager.ensureTableExists(HBaseStoreManager.java:725)

I think that  during JanusGraph initialization, it checks if some necessary namespace or table exists on hbase,  So, How to fix it ?

Thanks in advance.

**Comment by jerryjch** [comment]
The new JanusGraph 0.4’s packaged HBase2 is not backward comparable with
HBase 1.4 server.  Please refer to the Upgrade guide for JanusGraph 0.4.0.

Thanks.

Jerry

**Comment by GangLiCN** [comment]
Thanks !  Yes, You're right.

I tried installing hbase 2.1.5  then configured JanusGraph to use it as background storage, it succeeded.

So,  I suggest  readme file on github releasen page need to be updated
url:  https://github.com/JanusGraph/janusgraph/releases/tag/v0.4.0
to be updated text:
Tested Compatibility
Apache Cassandra 2.2.10, 3.0.14, 3.11.0
Apache HBase 1.2.6, 1.3.1, 1.4.10, 2.1.5

all 1.X versions need to be removed.

**Comment by thevalzo** [comment]
I'm wrong or the documentation is still incorrect? I've had the same issue with Janusgraph 0.4.0 and HBase 1.2.0

**Comment by FlorianHockmann** [comment]
> I'm wrong or the documentation is still incorrect? I've had the same issue with Janusgraph 0.4.0 and HBase 1.2.0

Looks like you're right and we really forgot to update the release description. I just did the update as suggested by @GangLiCN.
cc @jerryjch

**Comment by tstadje** [comment]
> > I'm wrong or the documentation is still incorrect? I've had the same issue with Janusgraph 0.4.0 and HBase 1.2.0
> 
> Looks like you're right and we really forgot to update the release description. I just did the update as suggested by @GangLiCN.
> cc @jerryjch

Hi, looks like the HBase versions 1.2.6, 1.3.1, 1.4.10 are back in [Release 0.5.0](https://github.com/JanusGraph/janusgraph/releases/tag/v0.5.0). Is this correct or a mistake?

**Comment by FlorianHockmann** [comment]
@porunov The 0.5 releases do indeed list older HBase version again that we don't support any more from what I know. It looks like we need to fix that for all release notes for versions 0.4.1 and higher.

**Comment by Deepakparashar14** [comment]
Am confused here , can anyone tell me which version of janus graph will support both hbase1 and hbase2 along with atlas 2.0.0

**Comment by geosmart** [comment]
@FlorianHockmann can janusgraoh latest version(0.5.2)support hbase v1.2?
I use atlas backend with janusgraph,but I already has a hbase 1.2 cluster.

**Comment by FlorianHockmann** [comment]
@farodin91 @porunov @jerryjch Can anyone of you comment on this? Do the newer versions support HBase 1 and if so, are there any additional steps to get that working, or if not, shouldn't we update the release notes to no longer claim support for HBase 1?

**Comment by farodin91** [comment]
For HBase1, it is required to build JanusGraph with the profile flag hbase1. I think it would be good to add distribution for HBase 1 assets for a new release.

**Comment by godofwharf** [comment]
If you are planning to use Janus Graph with HBase 1.x, use the following maven command `mvn clean deploy -pl janusgraph-hbase -am -DskipTests -Denforcer.skip=true -Drat.skip=true -Dgpg.skip=true -Dhbase.profile -Pjanusgraph-release,hbase1`. This command was tested with Janus Graph version 0.6.1. I am just adding it here for reference.

**Comment by timrobertson100** [comment]
> I am just adding it here for reference.

Thank you @godofwharf
