### ISSUE TITLE
janusgraph  concurrency

### ISSUE THREAD

**Issue by zhangatao** [JanusGraph/janusgraph#1787]
Hello, I now use gremlin-server, through the form of session to establish a connection, when the concurrency is not large, server is not abnormal, but when the concurrency is larger, such as 50 processes to press gremlin-server, Then there's going to be a mistake.
18953348 [gremlin-server-worker-43] WARN  org.apache.tinkerpop.gremlin.server.handler.OpExecutorHandler  - There was no session named 618ecfb7-8822-4069-adae-cc47d6326f09 to close
org.apache.tinkerpop.gremlin.server.op.OpProcessorException: There was no session named 618ecfb7-8822-4069-adae-cc47d6326f09 to close
        at org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor.lambda$selectOther$0(SessionOpProcessor.java:144)
        at org.apache.tinkerpop.gremlin.server.handler.OpExecutorHandler.channelRead0(OpExecutorHandler.java:68)
        at org.apache.tinkerpop.gremlin.server.handler.OpExecutorHandler.channelRead0(OpExecutorHandler.java:43)
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)

**Comment by zhangatao** [comment]
![image](https://user-images.githubusercontent.com/28706321/64599045-55192f80-d3eb-11e9-931f-4f5320819f12.png)

**Comment by zhangatao** [comment]
I now have the following questions:
1, through java to connect gremlin-server, in the production environment, the use of that connection is better? 2, how much can the son of gremlin-server, if I want to increase the concurrency, I need to adjust those parameters?

**Comment by FlorianHockmann** [comment]
Closed as it's not a feature request or bug report. Please ask your questions in our Gitter chat or the janusgraph-users Google group as described [in our README](https://github.com/JanusGraph/janusgraph#community) and in the issue template you saw (and deleted) when creating this issue.
