### ISSUE TITLE
TinkerPop tests fail for Berkeley

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#1854]
TinkerPop tests are failing for me, at least for the Berkeley backend (I haven't tried it on the distributed backends yet). They definitely worked when I executed them for the 0.4.0 release which was probably [at this commit](https://github.com/JanusGraph/janusgraph/commit/8fe5983cee8eb8a079b80754e5048d81d1993ff1).

### Stack Trace

```
Running org.janusgraph.blueprints.process.ESC[1mBerkeleyJanusGraphComputerTestESC[m
Exception in thread "Thread-13265" java.lang.IllegalArgumentException: The memory does not have a value for provided key: 4.1.0(4.0.0())
        at org.apache.tinkerpop.gremlin.process.computer.Memory$Exceptions.memoryDoesNotExist(Memory.java:153)
        at org.janusgraph.graphdb.olap.computer.FulgoraMemory.get(FulgoraMemory.java:119)
        at org.apache.tinkerpop.gremlin.process.computer.traversal.MemoryTraversalSideEffects.add(MemoryTraversalSideEffects.java:84)
        at org.apache.tinkerpop.gremlin.process.computer.traversal.TraversalVertexProgram.workerIterationEnd(TraversalVertexProgram.java:380)
        at org.janusgraph.graphdb.olap.computer.VertexProgramScanJob.workerIterationEnd(VertexProgramScanJob.java:82)
        at org.janusgraph.graphdb.olap.computer.VertexProgramScanJob$Executor.workerIterationEnd(VertexProgramScanJob.java:183)
        at org.janusgraph.diskstorage.keycolumnvalue.scan.StandardScannerExecutor.run(StandardScannerExecutor.java:206)
        at java.lang.Thread.run(Thread.java:748)
```

**Comment by porunov** [comment]
@FlorianHockmann would you be able to execute Tinkerpop tests on your setup (where 0.4.0 works) for commit before #1676 ? Does it pass for you?

**Comment by porunov** [comment]
@FlorianHockmann if you could make a VM or resolve #1856 , I would also be able to test tinkerpop tests, so that the process would go faster

**Comment by mad** [comment]
I try to run this test and catch next exception:

```
1851 [Thread-13] ERROR org.janusgraph.diskstorage.keycolumnvalue.scan.StandardScannerExecutor  - Could not load data from storage: {}
java.lang.IllegalStateException: Non-transactional Cursors may not be used in multiple threads; Cursor was created in Thread[Thread-12,5,main] but used in Thread[Thread-13,5,main]
```
BDB uses thread locker if transaction not specified

It directly relate with this PR https://github.com/JanusGraph/janusgraph/pull/1753. Because bdb store return iterator that opened in one thread but iterated in another - before that PR all entries returned in first call

I changed STORAGE_TRANSACTIONAL to true and GraphComputerTest succeed

I think transaction disabled for some performance reason. So may be check it with read only transaction?


Next failed test TraversalInterruptionComputerTest

```
1122978 [Thread-31948] ERROR org.janusgraph.diskstorage.keycolumnvalue.scan.StandardScannerExecutor  - Could not load data from storage: {}
java.lang.IllegalStateException: Database was closed.
	at com.sleepycat.je.Database.checkOpen(Database.java:2372)
	at com.sleepycat.je.Cursor.checkOpen(Cursor.java:5393)
	at com.sleepycat.je.Cursor.get(Cursor.java:1221)
	at com.sleepycat.je.Cursor.getNext(Cursor.java:1499)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore$1.getNextEntry(BerkeleyJEKeyValueStore.java:167)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore$1.hasNext(BerkeleyJEKeyValueStore.java:144)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter$KeyIteratorImpl$EntryIterator.next(OrderedKeyValueStoreAdapter.java:370)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter$KeyIteratorImpl$EntryIterator.next(OrderedKeyValueStoreAdapter.java:339)
	at org.janusgraph.diskstorage.util.StaticArrayEntryList.of(StaticArrayEntryList.java:397)
	at org.janusgraph.diskstorage.util.StaticArrayEntryList.ofStaticBuffer(StaticArrayEntryList.java:345)
	at org.janusgraph.diskstorage.keycolumnvalue.scan.StandardScannerExecutor$DataPuller.run(StandardScannerExecutor.java:339)
1122978 [main] WARN  org.janusgraph.util.system.IOUtils  - Failed closing org.janusgraph.diskstorage.Backend@7a31b8e
java.lang.IllegalStateException: Database closed while still referenced by other handles. 3 open cursors.
	at com.sleepycat.je.Database.closeInternalWork(Database.java:770)
	at com.sleepycat.je.Database.closeInternal(Database.java:599)
	at com.sleepycat.je.Database.close(Database.java:499)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.close(BerkeleyJEKeyValueStore.java:86)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.BaseKeyColumnValueAdapter.close(BaseKeyColumnValueAdapter.java:42)
	at org.janusgraph.diskstorage.keycolumnvalue.scan.StandardScanner.close(StandardScanner.java:66)
	at org.janusgraph.diskstorage.Backend.close(Backend.java:514)
	at org.janusgraph.util.system.IOUtils.closeQuietly(IOUtils.java:63)
	at org.janusgraph.graphdb.database.StandardJanusGraph.closeInternal(StandardJanusGraph.java:243)
	at org.janusgraph.graphdb.database.StandardJanusGraph.close(StandardJanusGraph.java:201)
	at org.janusgraph.blueprints.AbstractJanusGraphProvider.clear(AbstractJanusGraphProvider.java:137)
	at org.apache.tinkerpop.gremlin.GraphManager$ManagedGraphProvider.clear(GraphManager.java:142)
	at org.apache.tinkerpop.gremlin.AbstractGremlinTest.tearDown(AbstractGremlinTest.java:146)
	at jdk.internal.reflect.GeneratedMethodAccessor34.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:55)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:229)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite.runChild(AbstractGremlinSuite.java:51)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.apache.tinkerpop.gremlin.AbstractGremlinSuite$1.evaluate(AbstractGremlinSuite.java:238)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:230)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:58)
Exception in thread "Thread-31948" java.lang.IllegalStateException: Database was closed.
	at com.sleepycat.je.Database.checkOpen(Database.java:2372)
	at com.sleepycat.je.Database.removeCursor(Database.java:2356)
	at com.sleepycat.je.Cursor.close(Cursor.java:543)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJETx.closeCursor(BerkeleyJETx.java:69)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.closeCursor(BerkeleyJEKeyValueStore.java:80)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore.access$200(BerkeleyJEKeyValueStore.java:36)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore$1.close(BerkeleyJEKeyValueStore.java:188)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter$KeyIteratorImpl.close(OrderedKeyValueStoreAdapter.java:336)
	at org.janusgraph.diskstorage.keycolumnvalue.scan.StandardScannerExecutor$DataPuller.run(StandardScannerExecutor.java:349)
```

**Comment by porunov** [comment]
@mad I didn't review #1753 and #1676 but as I understand Berkeley  tests now fail when tinkerpop tests are enabled. Maybe we should rollback those commits and merge when they are fixed? I didn't work with Berkeley, if the bugs are easy to resolve, it would be good to resolve them, otherwise I think rollback is a good option, so that we could work on new releases.

**Comment by mad** [comment]
@porunov All TP tests passed on bdb backend

![image](https://user-images.githubusercontent.com/56705/69241071-01774f00-0baf-11ea-84e0-cdc6e3a754a7.png)

**Comment by porunov** [comment]
@mad Thank you for the fix. I've also started Tinkerpop tests with your fix. I will share a report when it is finished

**Comment by porunov** [comment]
I am closing this issue because TinkerPop tests passes for Berkeley from the fix provided by @mad .
@FlorianHockmann please, reopen this issue if you get Berkeley errors still
