### ISSUE TITLE
TemporaryLockingException: Temporary locking failure

### ISSUE THREAD

**Issue by hooverhe** [JanusGraph/janusgraph#1893]
When I executed the following  GraphOfTheGodsFactory.load(graph) command, the error happened. 

HBase 2.2.1
ES 6.6.0

gremlin> graph = JanusGraphFactory.open('conf/janusgraph-hbase-es.properties')
gremlin> GraphOfTheGodsFactory.load(graph)

15:23:12 ERROR org.janusgraph.graphdb.database.StandardJanusGraph  - Could not commit transaction [1] due to exception
org.janusgraph.diskstorage.locking.TemporaryLockingException: Temporary locking failure
	at org.janusgraph.diskstorage.locking.AbstractLocker.writeLock(AbstractLocker.java:309)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingStore.acquireLock(ExpectedValueCheckingStore.java:103)

Could not commit transaction due to exception during persistence
Type ':help' or ':h' for help.
Display stack trace? [yN]y
org.janusgraph.core.JanusGraphException: Could not commit transaction due to exception during persistence
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1391)

**Comment by li-boxuan** [comment]
It looks like the GraphOfTheGods graph is loaded by multiple threads concurrently. 

Closing this issue due to inactivity. Feel free to reopen if anyone sees a similar problem.
