### ISSUE TITLE
NPE during index lookup for edges

### ISSUE THREAD

**Issue by mad** [JanusGraph/janusgraph#1944]
- Version: 0.3, 0.4, master
- Storage Backend: berkeleyje
- Mixed Index Backend: lucene
- Mailing list Thread URL:
- Steps to Reproduce: 

```
graph = JanusGraphFactory.build().
set("storage.backend","inmemory").
set("index.search.backend","lucene").
set("index.search.directory","indexRootPath").
open()
mgmt = graph.openManagement()
ep = mgmt.makePropertyKey('ep').cardinality(Cardinality.SINGLE).dataType(String.class).make()
mgmt.buildIndex("ep", Edge.class).addKey(ep).buildMixedIndex("search")
mgmt.commit()

g = graph.traversal()
v1=g.addV().property("p1", "Tom").next()
v2=g.addV().property("p1", "Jerry").next()
e1=g.addE('Link').from(g.V(v1)).to(g.V(v2)).property('ep', 'hello')
g.tx().commit()
g.E().has('ep', 'hello')
g.E().property('ep', 'hello2')
g.tx().commit()
g.E().drop()
g.tx().commit()
graph.indexQuery("ep", "e.ep:'hello2'").edges()
```

### Stack Trace 

```
java.lang.NullPointerException
	at org.janusgraph.graphdb.query.graph.IndexQueryBuilder.lambda$execute$1(IndexQueryBuilder.java:207)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:174)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(ArrayList.java:1359)
	at java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:295)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:207)
	at java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:162)
```

Caused by DOCID tokenization

**Comment by porunov** [comment]
Fixed in #1975
