### ISSUE TITLE
can not set vertex id

### ISSUE THREAD

**Issue by yuqin11** [JanusGraph/janusgraph#2050]
Please post all questions and issues on [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users)
before opening a GitHub issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

Please include configurations and logs if available.
1. Even if i configured like you said, i get this error:
2. is there any method to reopen a ConfiguredGraphFactory?

when i configured ConfiguredGraphFactory in gremlin-server
when the server is stopped for some reason.
when i restart the gremlin server.
the server get an error with:
there hava an janusgraph xxxxxx-id has already been opened.
can ConfiguredGraphFactory be reopened?
because i have configured many graph in that ManagementConfigureGraph.
I retrieve the graph by
g1=ConfiguredGraphFactory.open("kgnlp_sddl");g1.trasversal().V().has(/xxx/,/xxx/)

For confirmed bugs, please report:
- Version: 0.3.1
- Storage Backend: cql
- Mixed Index Backend:es
- Mailing list Thread URL:
- Steps to Reproduce: 

```
gremlin> map = new HashMap();\
......1> map.put("graph.graphname", "idtest");\
......2> map.put("storage.backend", "cql");\
......3> map.put("query.batch", "true");\
......4> map.put("query.force-index", "false");\
......5> map.put("storage.cql.compression", "true");\
......6> map.put("storage.cql.compression-block-size", "4");\
......7> map.put("storage.cql.keyspace", "graphtest");\
......8> map.put("storage.cql.read-consistency-level", "LOCAL_ONE");\
......9> map.put("storage.cql.write-consistency-level", "LOCAL_QUORUM");\
.....10> map.put("storage.cql.local-core-connections-per-host", "2");\
.....11> map.put("storage.cql.local-max-connections-per-host", "2");\
.....12> map.put("storage.cql.replication-factor", "1");\
.....13> map.put("storage.hostname", "xxxx");\
.....14> map.put("ids.block-size", "10000000");\
.....15> map.put("storage.batch-loading", "true");\
.....16> map.put("storage.buffer-size", "1024");\
.....17> map.put("index.ES.backend", "elasticsearch");\
.....18> map.put("index.ES.hostname", "xxx");\
.....19> map.put("index.ES.index-name", "idtest");\
.....20> map.put("index.ES.elasticsearch.client-only", "true");\
.....21> map.put("index.ES.elasticsearch.create.ext.index.number_of_shards", "4");\
.....22> map.put("index.ES.elasticsearch.create.ext.index.number_of_replicas", "1");\
.....23> map.put("index.ES.elasticsearch.create.ext.index.refresh_interval", "600s");\
.....24> map.put("log.tx.key-consistent", "true");\
.....25> map.put("cache.db-cache-size", "0");\
.....26> map.put("cache.db-cache-time", "0");\
.....27> map.put("cache.db-cache", "false");\
.....28> map.put("metrics.enabled", "false");\
.....29> map.put("graph.replace-instance-if-exists", "true");\
.....30> map.put("graph.set-vertex-id", "true");\
.....31> map.put("schema.default", "default");\
.....32> ConfiguredGraphFactory.createConfiguration(new MapConfiguration(map));
==>null
gremlin> 
gremlin> 
gremlin> 
gremlin> 
gremlin> g1 = ConfiguredGraphFactory.open("idtest");g1.traversal().addV(/person/).property(T.id,1L)
Vertex does not support user supplied identifiers
Type ':help' or ':h' for help.
Display stack trace? [yN]y
org.apache.tinkerpop.gremlin.jsr223.console.RemoteException: Vertex does not support user supplied identifiers
        at org.apache.tinkerpop.gremlin.console.jsr223.DriverRemoteAcceptor.submit(DriverRemoteAcceptor.java:178)
        at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.execute(GremlinGroovysh.groovy:99)
        at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:122)
        at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:95)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
        at sun.reflect.GeneratedMethodAccessor30.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:165)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:130)
        at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:59)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:165)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:89)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
        at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:146)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
        at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:453)
```

### Stack Trace (if you have one)

```
paste stack trace here
```

**Comment by FlorianHockmann** [comment]
As @porunov [already explained in your earlier question](https://github.com/JanusGraph/janusgraph/issues/2049#issuecomment-601025507), we don't use issues for questions. Please ask them on [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users) instead.

**Comment by yuqin11** [comment]
have you really read my question or bug/possible ?
