### ISSUE TITLE
set ttl bug 

### ISSUE THREAD

**Issue by 18252032615** [JanusGraph/janusgraph#2129]
Please post all questions and issues on [janusgraph-users](https://groups.google.com/forum/#!forum/janusgraph-users)
before opening a GitHub issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 0.2.0
- Storage Backend: hbase
- Mixed Index Backend:es
- Mailing list Thread URL:
- Steps to Reproduce: 

### Stack Trace (if you have one)

when i set edge ttl .i got this 

code ：

        System.out.println(ModifierType.TTL);
        JanusGraphManagement mgmt = graph.openManagement();
        EdgeLabel label = mgmt.getEdgeLabel("label_name");
        mgmt.setTTL(label , Duration.ofDays(3));

log：

Exception in thread "main" java.lang.ExceptionInInitializerError
	at org.janusgraph.graphdb.database.management.ModifierType.<clinit>(ModifierType.java:23)
	at JanusgraphTest.main(JanusgraphTest.java:12)
Caused by: java.lang.NullPointerException
	at org.janusgraph.graphdb.database.management.ModifierType.values(ModifierType.java:22)
	at org.janusgraph.graphdb.types.TypeDefinitionCategory.<clinit>(TypeDefinitionCategory.java:81)
	... 2 more

**Comment by farodin91** [comment]
First of all, we no longer support 0.2 as you can see in our docs: https://docs.janusgraph.org/changelog/.

It is hard see, which lines throws in your code example.

**Comment by porunov** [comment]
Please use https://groups.google.com/g/janusgraph-users for such type of questions. We use GitHub issues to track bugs and feature requests only.
