### ISSUE TITLE
"within" step combined with "or" step throws errors

### ISSUE THREAD

**Issue by sergeymetallic** [JanusGraph/janusgraph#2188]
- Version: 0.5.2
- Storage Backend: Scylla
- Mixed Index Backend: Elasticsearch
- Mailing list Thread URL: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/janusgraph-users/-tSt8U1kvxA/xz95la6DAgAJ
- Steps to Reproduce: 
We have a schema with a property of type "Long", when we try to execute simple Gremlin query in the console

g.V().or(__.has("prop",P.within(2L)),__.has("prop",P.within(1L)))

We get the error: 

Value [[2]] is not an instance of the expected data type for property key [prop] and cannot be converted. Expected: class java.lang.Long, found: class java.util.Arrays$ArrayList

While g.V().has("prop",P.within()) can be executed just fine
### Stack Trace 

```
2020-08-17 11:21:41.310 -  [gremlin-server-exec-6] WARN  o.a.t.g.s.op.AbstractEvalOpProcessor - Exception processing a script on request [RequestMessage{, requestId=153f5014-2d6a-4aa9-934d-43d506cdb0c6, op='eval', processor='', args={gremlin=g.V().or(__.has("prop",P.within(2L)),__.has("prop",P.within(1L))), bindings={}, batchSize=64}}].
org.janusgraph.core.SchemaViolationException: Value [[2]] is not an instance of the expected data type for property key [prop] and cannot be converted. Expected: class java.lang.Long, found: class java.util.Arrays$ArrayList
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.verifyAttribute(StandardJanusGraphTx.java:578)
	at org.janusgraph.graphdb.query.QueryUtil.addConstraint(QueryUtil.java:267)
	at org.janusgraph.graphdb.query.QueryUtil.addConstraint(QueryUtil.java:257)
	at org.janusgraph.graphdb.query.QueryUtil.constraints2QNF(QueryUtil.java:209)
	at org.janusgraph.graphdb.query.graph.GraphCentricQueryBuilder.constructQueryWithoutProfile(GraphCentricQueryBuilder.java:238)
	at org.janusgraph.graphdb.query.graph.GraphCentricQueryBuilder.constructQuery(GraphCentricQueryBuilder.java:225)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.buildGraphCentricQuery(JanusGraphStep.java:148)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$null$0(JanusGraphStep.java:89)
	at java.base/java.util.LinkedHashMap$LinkedEntrySet.forEach(LinkedHashMap.java:671)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$new$2(JanusGraphStep.java:89)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:157)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:197)
	at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.handleIterator(AbstractOpProcessor.java:93)
	at org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor.lambda$evalOpInternal$5(AbstractEvalOpProcessor.java:264)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:278)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by rngcntr** [comment]
To solve this bug, we should have a look at `QueryUtil`, which is where the error arises. Specifically, this block of code:

https://github.com/JanusGraph/janusgraph/blob/d5ca0b05dfd356824b8e0f507dff99e76755f400/janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java#L182-L215

The body of the first `if` statement handles `IN` and `NOT_IN` predicates. In the given case however, the `IN` predicate is not at the top level but surrounded by an `OR`. Therefore, the following method is called:

https://github.com/JanusGraph/janusgraph/blob/d5ca0b05dfd356824b8e0f507dff99e76755f400/janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java#L241-L260

The content is quite similar, but it obviously misses the case of `predicate instanceof Contain`. I suspect we should add an equivalent handling of that case in this method. Additionally, we should probably also add a case to the following method: 

https://github.com/JanusGraph/janusgraph/blob/d5ca0b05dfd356824b8e0f507dff99e76755f400/janusgraph-core/src/main/java/org/janusgraph/graphdb/query/QueryUtil.java#L220-L239.

Fixing this should more ore less be a matter of copy & paste with some minor tweaks and with caution to not break any existing logic. It would also be good to add some test cases to ensure everything will behave as expected. So if anybody wants to dig down into the logic of nested predicates, please feel free. Otherwise I will try to find some time to implement a fix myself some time in the next couple of weeks.
