### ISSUE TITLE
NoClassDefFoundError: Could not initialize class org.janusgraph.diskstorage.es.rest.RestElasticSearchClient

### ISSUE THREAD

**Issue by kekukekro** [JanusGraph/janusgraph#2243]
- Version: V0.5.2
- Mixed Index Backend:ElasticSearch

When initializing RestElasticSearchClient, static variable INFO_REQUEST will be create first;
which calls the org.elasticsearch.client.request.Request
However, Request method requires four parameters, but Janus only passes in two parameters

like this

RestElasticSearchClient.java
```java
package org.janusgraph.diskstorage.es.rest;
public class RestElasticSearchClient implements ElasticSearchClient {
    ...
    private static final Request INFO_REQUEST = new Request(REQUEST_TYPE_GET, REQUEST_SEPARATOR);
```

Request.java
```java
package org.elasticsearch.client;

public final class Request {
...
   public Request(String method, String endpoint, Map<String, String> parameters, HttpEntity entity) {
        this.method = (String)Objects.requireNonNull(method, "method cannot be null");
        this.endpoint = (String)Objects.requireNonNull(endpoint, "endpoint cannot be null");
        this.parameters = (Map)Objects.requireNonNull(parameters, "parameters cannot be null");
        this.entity = entity;
    }
}
```

> This is log
```
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
        ... 97 more
Caused by: java.lang.NoClassDefFoundError: Could not initialize class org.janusgraph.diskstorage.es.rest.RestElasticSearchClient
        at org.janusgraph.diskstorage.es.rest.RestClientSetup.getElasticSearchClient(RestClientSetup.java:107)
        at org.janusgraph.diskstorage.es.rest.RestClientSetup.connect(RestClientSetup.java:75)
        at org.janusgraph.diskstorage.es.ElasticSearchSetup$1.connect(ElasticSearchSetup.java:51)
        at org.janusgraph.diskstorage.es.ElasticSearchIndex.interfaceConfiguration(ElasticSearchIndex.java:437)
        at org.janusgraph.diskstorage.es.ElasticSearchIndex.<init>(ElasticSearchIndex.java:324)
        ... 102 more
```

**Comment by kekukekro** [comment]
Sorry,This bug is caused by Apache Atlas and I will close it。
