### ISSUE TITLE
throw NullPointerException while submit gremlin script containing hasLable step, is it a bug?

### ISSUE THREAD

**Issue by hhhyang** [JanusGraph/janusgraph#2259]
if i submit gremlin script like:
```
g.E().hasLabel('L2_LINK').has('prop-1','prop-1-value')
```
or
```
g.E().has('L2_LINK', 'prop-1','prop-1-value')
```
janusgraph server throws NullPointerException exception. the stack information is as follow:
```
2020-11-27 12:07:35,507 WARN  [gremlin-server-exec-22] AbstractEvalOpProcessor.java:311 - Exception processing a script on request [RequestMessage{, requestId=e545c341-b4c7-4491-9757-89c9c1dff15b, op='eval', processor='', args={gremlin=g.E().hasLabel('L2_LINK').has('prop-1','prop-1-value'), batchSize=64}}].
java.lang.NullPointerException
        at org.janusgraph.graphdb.util.ElementHelper.getValues(ElementHelper.java:41)
        at org.janusgraph.graphdb.query.condition.PredicateCondition.evaluate(PredicateCondition.java:68)
        at org.janusgraph.graphdb.query.condition.And.evaluate(And.java:55)
        at org.janusgraph.graphdb.query.graph.GraphCentricQuery.matches(GraphCentricQuery.java:153)
        at org.janusgraph.graphdb.query.QueryProcessor.lambda$getFilterIterator$2(QueryProcessor.java:133)
        at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at org.janusgraph.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:54)
        at org.janusgraph.graphdb.query.ResultSetIterator.<init>(ResultSetIterator.java:44)
        at org.janusgraph.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:66)
        at com.google.common.collect.Iterables$7.iterator(Iterables.java:613)
        at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.executeGraphCentricQuery(JanusGraphStep.java:155)
        at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$null$1(JanusGraphStep.java:94)
        at java.lang.Iterable.forEach(Iterable.java:75)
        at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$new$2(JanusGraphStep.java:94)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:157)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
        at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:197)
        at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.handleIterator(AbstractOpProcessor.java:93)
        at org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor.lambda$evalOpInternal$5(AbstractEvalOpProcessor.java:264)
        at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:278)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
```
but if i submit gremlin script like:
```
g.E().has('prop-1','prop-1-value')
```
the result is correct

seems some meta data is corrupted? is it a bug?

enviroment:

janusgraph version: 0.5.2

backend cassandra version: 3.11

**Comment by FlorianHockmann** [comment]
And the edge really has the expected label? Can you show the result of `g.E().has('prop-1','prop-1-value').label()`?

**Comment by hhhyang** [comment]
@FlorianHockmann 

follow is the test result:
```
gremlin> :> g.E().has('prop-1','prop-1-value').label()
==>L2_LINK
```

**Comment by FlorianHockmann** [comment]
I hadn't seen that you already [asked this on janusgraph-users](https://groups.google.com/g/janusgraph-users/c/jrA0_px7imk) which is actually the right place to ask questions like this one. So I'm closing this for now and suggest that you continue the investigation over there as HadoopMarc has already provided some useful help in that thread. It doesn't make much sense to discuss this in two places in parallel.
If the conclusion in the linked thread will be that there is indeed a bug in JanusGraph, then we can re-open this issue here or create a new one.
