### ISSUE TITLE
BerkeleyElasticsearchTest.testIndexUpdatesWithoutReindex

### ISSUE THREAD

**Issue by farodin91** [JanusGraph/janusgraph#2272]
## Flaky Test

* **Test Name:** BerkeleyElasticsearchTest.testIndexUpdatesWithoutReindex
* **Branch:** master
* **Notes:** Additional details about the test, e.g., theory as to failure cause

### Stack Trace

```
org.janusgraph.core.JanusGraphException: Index did not stabilize within the given amount of time. For sufficiently long wait periods this is most likely caused by a failed/incorrectly shut down JanusGraph instance or a lingering transaction.
```

**Comment by FlorianHockmann** [comment]
Also seems to be flaky for CQL:

```
CQLElasticsearchTest>JanusGraphIndexTest.testIndexUpdatesWithoutReindex
```

It just failed in #3310 which targets `master`.

**Comment by FlorianHockmann** [comment]
Also flaky for Berkeley with Solr:

```
Error:  Errors: 
Error:    BerkeleySolrTest>JanusGraphIndexTest.testIndexUpdatesWithoutReindex:2302 » JanusGraph Could not execute operation due to backend exception
```

seems to be caused by a Deadlock here:

```
Error:  Tests run: 65, Failures: 0, Errors: 1, Skipped: 1, Time elapsed: 528.583 s <<< FAILURE! - in org.janusgraph.diskstorage.solr.BerkeleySolrTest
Error:  org.janusgraph.diskstorage.solr.BerkeleySolrTest.testIndexUpdatesWithoutReindex  Time elapsed: 123.91 s  <<< ERROR!
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
	at org.janusgraph.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:521)
	at org.janusgraph.diskstorage.BackendTransaction.edgeStoreQuery(BackendTransaction.java:284)
	at org.janusgraph.graphdb.database.StandardJanusGraph.edgeQuery(StandardJanusGraph.java:558)
	at org.janusgraph.graphdb.database.StandardJanusGraph$1.retrieveSchemaRelations(StandardJanusGraph.java:512)
	at org.janusgraph.graphdb.database.cache.StandardSchemaCache.getSchemaRelations(StandardSchemaCache.java:169)
	at org.janusgraph.graphdb.types.vertices.JanusGraphSchemaVertex.getRelated(JanusGraphSchemaVertex.java:121)
	at org.janusgraph.graphdb.types.indextype.MixedIndexTypeWrapper.getFieldKeys(MixedIndexTypeWrapper.java:53)
	at org.janusgraph.graphdb.types.indextype.MixedIndexTypeWrapper.getFieldKeys(MixedIndexTypeWrapper.java:30)
	at org.janusgraph.graphdb.database.management.JanusGraphIndexWrapper.getFieldKeys(JanusGraphIndexWrapper.java:74)
	at org.janusgraph.core.util.ManagementUtil.awaitIndexUpdate(ManagementUtil.java:81)
	at org.janusgraph.core.util.ManagementUtil.awaitGraphIndexUpdate(ManagementUtil.java:54)
	at org.janusgraph.graphdb.JanusGraphIndexTest.testIndexUpdatesWithoutReindex(JanusGraphIndexTest.java:2302)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1541)
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent exception while executing backend operation EdgeStoreQuery
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:79)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:52)
	... 15 more
Caused by: com.sleepycat.je.DeadlockException: (JE 18.3.12) Deadlock was detected. Locker: "1935476467 2046_main_Txn" was chosen randomly as the victim.
DB: edgestore. Timeout: 500ms.
Locker: "1935476467 2046_main_Txn" waits for lock: 1943661636(LSN: 0x0/0x65be, requestType: READ).
Locker: "799593079 2040_pool-1031-thread-1_Txn" owns lock: 1943661636(LSN: 0x0/0x65be, ownedType: WRITE). Locker: "799593079 2040_pool-1031-thread-1_Txn" waits for lock: 1474069226(LSN: 0x0/0x5fe8, requestType: WRITE).

	at com.sleepycat.je.txn.LockManager.makeDeadlockException(LockManager.java:1120)
	at com.sleepycat.je.txn.LockManager.checkAndHandleDeadlock(LockManager.java:961)
	at com.sleepycat.je.txn.LockManager.waitForLock(LockManager.java:490)
	at com.sleepycat.je.txn.LockManager.lock(LockManager.java:353)
	at com.sleepycat.je.txn.Txn.lockInternal(Txn.java:545)
	at com.sleepycat.je.txn.Locker.lock(Locker.java:496)
	at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3674)
	at com.sleepycat.je.dbi.CursorImpl.lockLN(CursorImpl.java:3399)
	at com.sleepycat.je.dbi.CursorImpl.lockLNAndCheckDefunct(CursorImpl.java:2177)
	at com.sleepycat.je.dbi.CursorImpl.lockAndGetCurrent(CursorImpl.java:2102)
	at com.sleepycat.je.dbi.CursorImpl.getNext(CursorImpl.java:2612)
	at com.sleepycat.je.Cursor.retrieveNextNoDups(Cursor.java:3554)
	at com.sleepycat.je.Cursor.retrieveNext(Cursor.java:3312)
	at com.sleepycat.je.Cursor.getInternal(Cursor.java:1313)
	at com.sleepycat.je.Cursor.get(Cursor.java:1244)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore$1.getNextEntry(BerkeleyJEKeyValueStore.java:187)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore$1.hasNext(BerkeleyJEKeyValueStore.java:164)
	at org.janusgraph.diskstorage.util.StaticArrayEntryList.applyElementsComputation(StaticArrayEntryList.java:540)
	at org.janusgraph.diskstorage.util.StaticArrayEntryList.of(StaticArrayEntryList.java:406)
	at org.janusgraph.diskstorage.util.StaticArrayEntryList.ofStaticBuffer(StaticArrayEntryList.java:358)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter.convert(OrderedKeyValueStoreAdapter.java:169)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter.getSlice(OrderedKeyValueStoreAdapter.java:88)
	at org.janusgraph.diskstorage.keycolumnvalue.cache.KCVSCache.getSliceNoCache(KCVSCache.java:82)
	at org.janusgraph.diskstorage.BackendTransaction$1.call(BackendTransaction.java:288)
	at org.janusgraph.diskstorage.BackendTransaction$1.call(BackendTransaction.java:284)
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:66)
	... 16 more
```
