### ISSUE TITLE
Getting a strange and intermittent "org.apache.thrift.TApplicationException: multiget_slice failed: out of sequence response" error

### ISSUE THREAD

**Issue by prismofeverything** [JanusGraph/janusgraph#234]
Hi all,

I am using Janusgraph version 0.2.0-SNAPSHOT with the cassandra backend (commit 67ba31e27ec173c30e14d1cff56cad27e0c719f9 from April 17th).

Seemingly at random I am getting strange errors about an "out of sequence response". I tried googling it and just found this inconclusive thread from 2013 about a similar error: https://groups.google.com/forum/#!topic/aureliusgraphs/uPNC90iH7Z4

Not sure what I should do about this? Any guidance appreciated, thanks!

```
23:44:13.981 [pool-19-thread-1] ERROR c.n.a.c.i.CountingConnectionPoolMonitor - com.netflix.astyanax.connectionpool.exceptions.ThriftStateException: ThriftStateException: [host=127.0.0.1(127.0.0.1):9160, latency=1(1), attempts=1]org.apache.thrift.TApplicationException: multiget_slice failed: out of sequence response
com.netflix.astyanax.connectionpool.exceptions.ThriftStateException: ThriftStateException: [host=127.0.0.1(127.0.0.1):9160, latency=1(1), attempts=1]org.apache.thrift.TApplicationException: multiget_slice failed: out of sequence response
        at com.netflix.astyanax.thrift.ThriftConverter.ToConnectionPoolException(ThriftConverter.java:177) ~[astyanax-thrift-3.8.0.jar:3.8.0]
        at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:65) ~[astyanax-thrift-3.8.0.jar:3.8.0]
        at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:28) ~[astyanax-thrift-3.8.0.jar:3.8.0]
        at com.netflix.astyanax.thrift.ThriftSyncConnectionFactoryImpl$ThriftConnection.execute(ThriftSyncConnectionFactoryImpl.java:153) ~[astyanax-thrift-3.8.0.jar:3.8.0]
        at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:119) ~[astyanax-core-3.8.0.jar:3.8.0]
        at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:352) [astyanax-core-3.8.0.jar:3.8.0]
        at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:538) [astyanax-thrift-3.8.0.jar:3.8.0]
        at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:126) [janusgraph-cassandra-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:92) [janusgraph-cassandra-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getSlice(AstyanaxKeyColumnValueStore.java:81) [janusgraph-cassandra-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller$1.call(KCVSLog.java:783) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller$1.call(KCVSLog.java:780) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:148) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.util.BackendOperation$1.call(BackendOperation.java:162) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:69) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:55) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:159) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller.run(KCVSLog.java:717) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_121]
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308) [na:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180) [na:1.8.0_121]
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_121]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_121]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_121]
Caused by: org.apache.thrift.TApplicationException: multiget_slice failed: out of sequence response
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:76) ~[libthrift-0.9.2.jar:0.9.2]
        at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:741) ~[cassandra-thrift-2.1.9.jar:2.1.9]
        at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:725) ~[cassandra-thrift-2.1.9.jar:2.1.9]
        at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4$1.internalExecute(ThriftColumnFamilyQueryImpl.java:544) ~[astyanax-thrift-3.8.0.jar:3.8.0]
        at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4$1.internalExecute(ThriftColumnFamilyQueryImpl.java:541) ~[astyanax-thrift-3.8.0.jar:3.8.0]
        at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:60) ~[astyanax-thrift-3.8.0.jar:3.8.0]
        ... 23 common frames omitted
```

**Comment by porunov** [comment]
Thrift support was deprecated in 0.4.1 version of JanusGraph. Thrift is going to be completely removed in 0.6.0 version of JanusGraph due to deprecation. The PR is #1800 
I am closing this issue as an obsolete issue. Feel free to reopen if you think it is still wise to support Thrift.
