### ISSUE TITLE
janusgraph-dist build stuck at generate-compat-test-files for ES

### ISSUE THREAD

**Issue by jerryjch** [JanusGraph/janusgraph#235]
This is happening on master branch:

mvn clean install -Pjanusgraph-release -Dgpg.skip=true -DskipTests=true

```
[INFO] --- exec-maven-plugin:1.2.1:exec (generate-compat-test-files) @ janusgraph-dist-hadoop-2 ---
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/root/git/janusgraph/janusgraph-dist/janusgraph-dist-hadoop-2/target/dependency/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/root/git/janusgraph/janusgraph-dist/janusgraph-dist-hadoop-2/target/dependency/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [ch.qos.logback.classic.util.ContextSelectorStaticBinder]
17:12:51.841 [main] INFO  o.j.d.es.ElasticsearchStatus - ES pidfile /tmp/janusgraph-test-es.pid does not exist
17:12:51.851 [main] INFO  org.janusgraph.DaemonRunner - Executing ./target/elasticsearch-5.2.2/bin/elasticsearch -d -p /tmp/janusgraph-test-es.pid
17:12:51.956 [main] INFO  org.janusgraph.DaemonRunner - Command "./target/elasticsearch-5.2.2/bin/elasticsearch -d -p /tmp/janusgraph-test-es.pid" exited with status 0
17:12:52.956 [main] INFO  o.j.d.es.ElasticsearchRunner - Watching ES logfile ./target/elasticsearch-5.2.2/logs/elasticsearch.log for  started token
17:12:52.963 [main] DEBUG o.j.d.es.ElasticsearchRunner - Elasticsearch logfile ./target/elasticsearch-5.2.2/logs/elasticsearch.log not found
java.io.FileNotFoundException: ./target/elasticsearch-5.2.2/logs/elasticsearch.log (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_111]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_111]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_111]
        at java.io.FileReader.<init>(FileReader.java:72) ~[na:1.8.0_111]
        at org.janusgraph.diskstorage.es.ElasticsearchRunner.watchLog(ElasticsearchRunner.java:139) [janusgraph-es-0.2.0-SNAPSHOT-tests.jar:na]
        at org.janusgraph.diskstorage.es.ElasticsearchRunner.startImpl(ElasticsearchRunner.java:112) [janusgraph-es-0.2.0-SNAPSHOT-tests.jar:na]
        at org.janusgraph.diskstorage.es.ElasticsearchRunner.startImpl(ElasticsearchRunner.java:33) [janusgraph-es-0.2.0-SNAPSHOT-tests.jar:na]
        at org.janusgraph.DaemonRunner.start(DaemonRunner.java:62) [janusgraph-test-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.es.ElasticsearchRunner.main(ElasticsearchRunner.java:167) [janusgraph-es-0.2.0-SNAPSHOT-tests.jar:na]
17:12:53.465 [main] DEBUG o.j.d.es.ElasticsearchRunner - Elasticsearch logfile ./target/elasticsearch-5.2.2/logs/elasticsearch.log not found
java.io.FileNotFoundException: ./target/elasticsearch-5.2.2/logs/elasticsearch.log (No such file or directory)
        at java.io.FileInputStream.open0(Native Method) ~[na:1.8.0_111]
        at java.io.FileInputStream.open(FileInputStream.java:195) ~[na:1.8.0_111]
        at java.io.FileInputStream.<init>(FileInputStream.java:138) ~[na:1.8.0_111]
        at java.io.FileReader.<init>(FileReader.java:72) ~[na:1.8.0_111]
        at org.janusgraph.diskstorage.es.ElasticsearchRunner.watchLog(ElasticsearchRunner.java:139) [janusgraph-es-0.2.0-SNAPSHOT-tests.jar:na]
        at org.janusgraph.diskstorage.es.ElasticsearchRunner.startImpl(ElasticsearchRunner.java:112) [janusgraph-es-0.2.0-SNAPSHOT-tests.jar:na]
        at org.janusgraph.diskstorage.es.ElasticsearchRunner.startImpl(ElasticsearchRunner.java:33) [janusgraph-es-0.2.0-SNAPSHOT-tests.jar:na]
        at org.janusgraph.DaemonRunner.start(DaemonRunner.java:62) [janusgraph-test-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.es.ElasticsearchRunner.main(ElasticsearchRunner.java:167) [janusgraph-es-0.2.0-SNAPSHOT-tests.jar:na]
17:12:53.767 [Thread-0] INFO  o.j.DaemonRunner$StreamLogger - End of stream.
17:13:53.022 [main] INFO  o.j.d.es.ElasticsearchRunner - Elasticsearch logfile timeout (60066 MILLISECONDS)
17:13:53.022 [main] INFO  o.j.d.es.ElasticsearchStatus - ES pidfile /tmp/janusgraph-test-es.pid does not exist
17:13:53.024 [main] DEBUG org.janusgraph.DaemonRunner - Registered daemon killer hook: Thread[Thread-1,5,main]
17:13:53.057 [main] DEBUG o.a.c.c.PropertiesConfiguration - FileName set to janusgraph-berkeleyje-es.properties
17:13:53.058 [main] DEBUG o.a.c.c.PropertiesConfiguration - Base path set to /root/git/janusgraph/janusgraph-dist/janusgraph-dist-hadoop-2/target/conf
17:13:53.062 [main] DEBUG o.a.c.c.ConfigurationUtils - ConfigurationUtils.locate(): base is /root/git/janusgraph/janusgraph-dist/janusgraph-dist-hadoop-2/target/conf, name is janusgraph-berkeleyje-es.properties
17:13:53.062 [main] DEBUG o.a.c.c.DefaultFileSystem - Could not locate file janusgraph-berkeleyje-es.properties at /root/git/janusgraph/janusgraph-dist/janusgraph-dist-hadoop-2/target/conf: no protocol: /root/git/janusgraph/janusgraph-dist/janusgraph-dist-hadoop-2/target/conf
17:13:53.062 [main] DEBUG o.a.c.c.ConfigurationUtils - Loading configuration from the path /root/git/janusgraph/janusgraph-dist/janusgraph-dist-hadoop-2/target/conf/janusgraph-berkeleyje-es.properties
17:13:53.167 [main] DEBUG o.janusgraph.core.JanusGraphFactory - Overwrote relative path: was ../db/berkeley, now /root/git/janusgraph/janusgraph-dist/janusgraph-dist-hadoop-2/target/conf/../db/berkeley
17:13:54.285 [main] DEBUG o.j.d.b.BerkeleyJEStoreManager - Opened database system_properties
java.lang.Throwable: null
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.openDatabase(BerkeleyJEStoreManager.java:187) [janusgraph-berkeleyje-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEStoreManager.openDatabase(BerkeleyJEStoreManager.java:48) [janusgraph-berkeleyje-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreManagerAdapter.openDatabase(OrderedKeyValueStoreManagerAdapter.java:89) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreManagerAdapter.openDatabase(OrderedKeyValueStoreManagerAdapter.java:82) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreManagerAdapter.openDatabase(OrderedKeyValueStoreManagerAdapter.java:38) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.Backend.getStandaloneGlobalConfiguration(Backend.java:456) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1345) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:107) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:75) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.example.GraphOfTheGodsFactory.main(GraphOfTheGodsFactory.java:165) [janusgraph-core-0.2.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.es.ElasticsearchRunner.main(ElasticsearchRunner.java:168) [janusgraph-es-0.2.0-SNAPSHOT-tests.jar:na]
17:13:54.309 [main] DEBUG o.j.d.k.k.OrderedKeyValueStoreAdapter - Used key length 0 for database system_properties
17:13:54.382 [main] INFO  o.j.g.c.GraphDatabaseConfiguration - Set default timestamp provider MICRO
17:13:54.390 [main] DEBUG o.j.d.b.BerkeleyJEStoreManager - Removed database system_properties
17:13:54.443 [main] INFO  o.j.g.c.GraphDatabaseConfiguration - Generated unique-instance-id=ac10a8f99868-throb1-fyre-ibm-com1
17:13:54.492 [main] INFO  org.janusgraph.diskstorage.Backend - Configuring index [search]
17:13:54.515 [main] DEBUG o.j.d.es.ElasticSearchIndex - Found ES client version matching JanusGraph's compile-time version: 2.4.4 (OK)
17:13:54.516 [main] DEBUG o.j.d.es.ElasticSearchSetup - Configuring RestClient
17:13:54.516 [main] INFO  o.j.d.es.ElasticSearchSetup - Configured remote host: 127.0.0.1 : 9200
17:13:54.982 [main] DEBUG o.a.h.impl.nio.client.MainClientExec - [exchange: 1] start execution
17:13:54.986 [main] DEBUG o.a.h.c.protocol.RequestAddCookies - CookieSpec selected: default
17:13:54.994 [main] DEBUG o.a.h.c.protocol.RequestAuthCache - Auth cache not set in the context
17:13:54.995 [main] DEBUG o.a.h.i.n.c.InternalHttpAsyncClient - [exchange: 1] Request connection for {}->http://127.0.0.1:9200
17:13:54.996 [main] DEBUG o.a.h.i.n.c.PoolingNHttpClientConnectionManager - Connection request: [route: {}->http://127.0.0.1:9200][total kept alive: 0; route allocated: 0 of 10; total allocated: 0 of 30]
17:13:55.006 [pool-1-thread-1] DEBUG o.a.h.i.n.c.PoolingNHttpClientConnectionManager - Connection request failed
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_111]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_111]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) [httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) [httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) [httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192) [httpasyncclient-4.1.2.jar:4.1.2]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) [httpasyncclient-4.1.2.jar:4.1.2]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
17:13:55.006 [pool-1-thread-1] DEBUG o.a.h.i.n.c.InternalHttpAsyncClient - [exchange: 1] connection request failed
17:13:55.008 [pool-1-thread-1] DEBUG org.elasticsearch.client.RestClient - request [GET http://127.0.0.1:9200/] failed
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_111]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_111]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) [httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) [httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) [httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192) [httpasyncclient-4.1.2.jar:4.1.2]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) [httpasyncclient-4.1.2.jar:4.1.2]
        at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
17:13:55.008 [pool-1-thread-1] DEBUG org.elasticsearch.client.RestClient - added host [http://127.0.0.1:9200] to blacklist
17:13:55.009 [main] WARN  o.j.d.e.rest.RestElasticSearchClient - Unable to determine Elasticsearch server version. Assuming 2.x.
java.net.ConnectException: Connection refused
        at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method) ~[na:1.8.0_111]
        at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717) ~[na:1.8.0_111]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvent(DefaultConnectingIOReactor.java:171) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.DefaultConnectingIOReactor.processEvents(DefaultConnectingIOReactor.java:145) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.reactor.AbstractMultiworkerIOReactor.execute(AbstractMultiworkerIOReactor.java:348) ~[httpcore-nio-4.4.5.jar:4.4.5]
        at org.apache.http.impl.nio.conn.PoolingNHttpClientConnectionManager.execute(PoolingNHttpClientConnectionManager.java:192) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at org.apache.http.impl.nio.client.CloseableHttpAsyncClientBase$1.run(CloseableHttpAsyncClientBase.java:64) ~[httpasyncclient-4.1.2.jar:4.1.2]
        at java.lang.Thread.run(Thread.java:745) ~[na:1.8.0_111]
```

**Comment by sjudeng** [comment]
I created #238 for updating documentation regarding building as non-root user.
