### ISSUE TITLE
java.lang.UnsupportedOperationException: Vertex does not support user supplied identifiers

### ISSUE THREAD

**Issue by lvchongyi** [JanusGraph/janusgraph#2426]
JanusGraphVertex v2 = graph.addVertex(T.id, Integer.parseInt(otherV));

java.lang.UnsupportedOperationException: Vertex does not support user supplied identifiers
	at org.apache.tinkerpop.gremlin.structure.Vertex$Exceptions.userSuppliedIdsNotSupported(Vertex.java:163)
	at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsTransaction.addVertex(JanusGraphBlueprintsTransaction.java:105)
	at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph.addVertex(JanusGraphBlueprintsGraph.java:141)
	at com.newland.JanusgraphImpl.JanusgraphImpl.addJanusgraphData(JanusgraphImpl.java:99)
	at com.newland.JanusgraphImpl.JanusgraphImpl.main(JanusgraphImpl.java:151)

what's this wrong?

**Comment by farodin91** [comment]
Did you override `graph.set-vertex-id`?
