### ISSUE TITLE
Caused by: org.janusgraph.core.JanusGraphException: A JanusGraph graph with the same instance id [0a000439355-0b2b58ca5c222] is already open. Might required forced shutdown

### ISSUE THREAD

**Issue by srinu0266** [JanusGraph/janusgraph#2512]
getting same instance  issue even if i set graph.replace-instance-if-exists=true .please respond to below issue.
graph.replace-instance-if-exists=true
jnausgraph version 0.5.2

For confirmed bugs, please report:
- Version: 0.5.2
- Storage Backend:cql
- Mixed Index Backend: elasticsearch
- Link to discussed bug: 
- Expected Behavior:
- Current Behavior:
- Steps to Reproduce: 

### Stack Trace (if you have one)

```
10689 [main] ERROR org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor  - Could not invoke constructor on class org.janusgraph.graphdb.management.JanusGraphManager (defined by the 'graphManager' setting) with one argument of class Settings


Exception in thread "main" java.lang.RuntimeException: java.lang.reflect.InvocationTargetException


	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:91)


	at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:122)


	at org.apache.tinkerpop.gremlin.server.GremlinServer.<init>(GremlinServer.java:86)


	at org.apache.tinkerpop.gremlin.server.GremlinServer.main(GremlinServer.java:345)


Caused by: java.lang.reflect.InvocationTargetException


	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)


	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)


	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)


	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)


	at org.apache.tinkerpop.gremlin.server.util.ServerGremlinExecutor.<init>(ServerGremlinExecutor.java:80)


	... 3 more


Caused by: org.janusgraph.core.JanusGraphException: A JanusGraph graph with the same instance id [0a000439355-0b2b58ca5c222] is already open. Might required forced shutdown.


	at org.janusgraph.graphdb.database.StandardJanusGraph.<init>(StandardJanusGraph.java:173)


	at org.janusgraph.core.JanusGraphFactory.lambda$open$0(JanusGraphFactory.java:150)


	at org.janusgraph.graphdb.management.JanusGraphManager.openGraph(JanusGraphManager.java:243)


	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:150)


	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:100)


	at org.janusgraph.graphdb.management.JanusGraphManager.lambda$new$0(JanusGraphManager.java:75)


	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)


	at org.janusgraph.graphdb.management.JanusGraphManager.<init>(JanusGraphManager.java:74)


	... 8 more
```

**Comment by li-boxuan** [comment]
Can you paste your full configuration file and your commands to open the graph?

**Comment by srinu0266** [comment]
Hi li-boxuan,
   Thanks for reply.
   
  please find commands used 
 :remote connect tinkerpop.server conf/remote.yaml session-managed
 :remote console
 t8=ConfiguredGraphFactory.open('test')
 g=t8.traversal()
 g.V()

[gremlin-server.txt](https://github.com/JanusGraph/janusgraph/files/6128083/gremlin-server.txt)

Thanks,
M.Srinivas.

**Comment by li-boxuan** [comment]
The configuration file you provided is gremlin server config. Can you provide your janusgraph configs which includes your "graph.replace-instance-if-exists" setting?

**Comment by srinu0266** [comment]
Hi,
          Please find attached janusgraph properties file for your reference.
          Tried some tweak changes but of no use.

 [janusgraph.properties.txt](https://github.com/JanusGraph/janusgraph/files/6131405/janusgraph.properties.txt)

Thanks,
M.Srinivas

**Comment by li-boxuan** [comment]
That is weird... Can you try without using janusgraph server? Do you see the same problem?

**Comment by srinu0266** [comment]
able to connect to the remote gremlin console.but while exexuting queries get the following error.

gremlin> g.V()
Host did not respond in a timely fashion - check the server status and submit again.
Type ':help' or ':h' for help.
Display stack trace? [yN]y
org.apache.tinkerpop.gremlin.jsr223.console.RemoteException: Host did not respond in a timely fashion - check the server status and submit again.
        at org.apache.tinkerpop.gremlin.console.jsr223.DriverRemoteAcceptor.submit(DriverRemoteAcceptor.java:188)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
        at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.execute(GremlinGroovysh.groovy:110)
        at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:120)
        at org.codehaus.groovy.tools.shell.Shell$leftShift$1.call(Unknown Source)
        at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:93)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:164)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:138)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.runtime.callsite.PlainObjectMetaMethodSite.doInvoke(PlainObjectMetaMethodSite.java:43)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:190)
        at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:58)
        at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:160)
        at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:57)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:144)
        at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:164)
        at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:97)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
        at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:168)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234)
        at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:502)

Thanks,
M.Srinivas

**Comment by srinu0266** [comment]
Hi,
          Please Look into the following warn msg while login to remote console.
  :remote connect tinkerpop.server conf/remote.yaml session-managed
09:26:37 WARN  org.apache.tinkerpop.gremlin.driver.Host  - ****Marking Host{address=localhost/127.0.0.1:8182, hostUri=ws://localhost:8182/gremlin} as unavailable****. Trying to reconnect.

Thanks,
M.Srinivas

**Comment by shrinu2k22** [comment]
Any solution for this error @srinu0266
