### ISSUE TITLE
Gremlin groovy script engine won't start

### ISSUE THREAD

**Issue by linehrr** [JanusGraph/janusgraph#2616]
starting gremlin server and encountered: 
```
janus-spark-server    | 19:25:32.307 [gremlin-server-exec-1] ERROR o.a.t.g.j.DefaultGremlinScriptEngineManager - Could not create GremlinScriptEngine for gremlin-groovy
janus-spark-server    | groovy.lang.MissingPropertyException: No such property: metaClass for class: java.util.Map
janus-spark-server    |         at groovy.lang.MetaClassImpl.invokeStaticMissingProperty(MetaClassImpl.java:1021) ~[job.jar:0.1.0]
janus-spark-server    |         at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1866) ~[job.jar:0.1.0]
janus-spark-server    |         at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:1842) ~[job.jar:0.1.0]
janus-spark-server    |         at groovy.lang.MetaClassImpl.getProperty(MetaClassImpl.java:3797) ~[job.jar:0.1.0]
janus-spark-server    |         at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234) ~[job.jar:0.1.0]
janus-spark-server    |         at org.apache.tinkerpop.gremlin.groovy.loaders.ObjectLoader.load(ObjectLoader.groovy:28) ~[job.jar:0.1.0]
janus-spark-server    |         at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:234) ~[job.jar:0.1.0]
janus-spark-server    |         at org.apache.tinkerpop.gremlin.groovy.loaders.GremlinLoader.load(GremlinLoader.groovy:27) ~[job.jar:0.1.0]
janus-spark-server    |         at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.<init>(GremlinGroovyScriptEngine.java:223) ~[job.jar:0.1.0]
janus-spark-server    |         at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngineFactory.getScriptEngine(GremlinGroovyScriptEngineFactory.java:63) ~[job.jar:0.1.0]
janus-spark-server    |         at org.apache.tinkerpop.gremlin.jsr223.DefaultGremlinScriptEngineManager.createGremlinScriptEngine(DefaultGremlinScriptEngineManager.java:415) ~[job.jar:0.1.0]
janus-spark-server    |         at org.apache.tinkerpop.gremlin.jsr223.DefaultGremlinScriptEngineManager.getEngineByName(DefaultGremlinScriptEngineManager.java:219) ~[job.jar:0.1.0]
janus-spark-server    |         at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.lambda$getEngineByName$0(CachedGremlinScriptEngineManager.java:57) [job.jar:0.1.0]
janus-spark-server    |         at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_201]
janus-spark-server    |         at org.apache.tinkerpop.gremlin.jsr223.CachedGremlinScriptEngineManager.getEngineByName(CachedGremlinScriptEngineManager.java:57) [job.jar:0.1.0]
janus-spark-server    |         at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:267) ~[job.jar:0.1.0]
janus-spark-server    |         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_201]
janus-spark-server    |         at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_201]
janus-spark-server    |         at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_201]
janus-spark-server    |         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_201]
janus-spark-server    |         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_201]
janus-spark-server    |         at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_201]
```

Looks like it's Java version related, however we are running JRE1.8 so it should be good to support groovy3. 

For confirmed bugs, please report:
- Version: 3.4.6
- Storage Backend: cql
- Mixed Index Backend: ES

**Comment by Charele** [comment]
groovy3?
Janusgraph use Tinkerpop, Tinkerpop use Groovy, 
but Tinkerpop(include the newest v3.5.0)  use Groovy2, not Groovy3.

So I think you should use groovy2 for compatibility,
It's Tinkerpop's business, not Janusgraph
