### ISSUE TITLE
Issues in sample bulk loader with HBase

### ISSUE THREAD

**Issue by ruweih** [JanusGraph/janusgraph#268]
Tried bulk loading sample with HBase using the configuration provided in current Janus release (0.1.0):

http://docs.janusgraph.org/latest/hadoop-tp3.html

Found two issues:

1. By default, the following instruction would not work in default configuration.
hdfs.copyFromLocal('data/grateful-dead.kryo','data/grateful-dead.kryo')
It would destroy the file since it copy to itself, and leave a hidden check sum file, which prevents the file to be copied to HDFS later. 
To solve the problem, the HDFS configuration "core-site.xml" need to be added/linked into "conf" directory in order for the command to work, make sure the hidden checksum file deleted before try again.

2. The sample Janus HBase configuration "conf/janusgraph-hbase.properties" works for normal graph operation, like schema definition, but won't work with bulk loader with exception:

11:05:55 ERROR org.apache.spark.executor.Executor  - Exception in task 0.0 in stage 1.0 (TID 1)
java.lang.RuntimeException: Configuration must contain a valid 'gremlin.graph' setting
	at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:57)
	at org.apache.tinkerpop.gremlin.process.computer.bulkloading.BulkLoaderVertexProgram.workerIterationStart(BulkLoaderVertexProgram.java:171)
	at org.apache.tinkerpop.gremlin.spark.process.computer.SparkExecutor.lambda$executeVertexProgramIteration$35c6b113$1(SparkExecutor.java:97)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$9$1.apply(JavaRDDLike.scala:215)
	at org.apache.spark.api.java.JavaRDDLike$$anonfun$fn$9$1.apply(JavaRDDLike.scala:215)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.RDD$$anonfun$mapPartitions$1$$anonfun$apply$20.apply(RDD.scala:710)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.rdd.MapPartitionsRDD.compute(MapPartitionsRDD.scala:38)
	at org.apache.spark.rdd.RDD.computeOrReadCheckpoint(RDD.scala:306)
	at org.apache.spark.rdd.RDD.iterator(RDD.scala:270)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:73)
	at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:41)
	at org.apache.spark.scheduler.Task.run(Task.scala:89)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

Comparing with the Cassandra example, it need one more entry in the file:
gremlin.graph=org.janusgraph.core.JanusGraphFactory

**Comment by pluradj** [comment]
Improving Hadoop docs is related to https://github.com/JanusGraph/janusgraph/issues/253
