### ISSUE TITLE
NoSuchMethodError when enabling CQL driver metrics

### ISSUE THREAD

**Issue by cdegroc** [JanusGraph/janusgraph#2722]
### Summary
While testing JanusGraph's master branch (0.6.0), I've stumbled on the following issue and would appreciate if anyone could confirm it.

- Version: master (a8925e90cdd5eb872ee8f937c9b56d9bf0f3caab)
- Storage Backend: CQL
- Expected Behavior: JanusGraph would start with CQL driver metrics enabled
- Current Behavior: `java.lang.NoSuchMethodError: com.codahale.metrics.MetricRegistry.gauge` is thrown
- Steps to Reproduce:
  - Using JanusGraph's master branch
  - Build and start a docker image running `janusgraph-server.sh`
  - Create a graph from a configuration including properties
```
storage.cql.metrics.node-enabled = pool.open-connections,pool.available-streams,pool.in-flight,bytes-sent,bytes-received,cql-messages
storage.cql.metrics.session-enabled = bytes-sent,bytes-received,cql-requests,cql-client-timeouts,throttling.delay,throttling.queue-size,throttling.errors
```
  - Graph creation fails with a `NoSuchMethodError` (stack trace below)

### Stack Trace

```
jce-janusgraph   | 2021-07-27 13:42:34,895 [gremlin-server-session-1] WARN  org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor - 0 0 - Exception processing a script on request [RequestMessage{, requestId=774b3c82-18a5-4a92-b01e-65acc0812a22, op='eval', processor='session', args={gremlin=graph = createGraph(graphName), session=5a48bd92-4457-4cd0-9224-8f93fbdfd484, manageTransaction=false, evaluationTimeout=600000, userAgent=Gremlin Console/1.21.0, batchSize=64, maintainStateAfterException=false}}].
jce-janusgraph   | java.lang.NoSuchMethodError: com.codahale.metrics.MetricRegistry.gauge(Ljava/lang/String;Lcom/codahale/metrics/MetricRegistry$MetricSupplier;)Lcom/codahale/metrics/Gauge;
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.metrics.DropwizardMetricUpdater.lambda$initializeGauge$1(DropwizardMetricUpdater.java:110) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660) ~[na:1.8.0_292]
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.metrics.DropwizardMetricUpdater.initializeGauge(DropwizardMetricUpdater.java:106) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.metrics.DropwizardSessionMetricUpdater.<init>(DropwizardSessionMetricUpdater.java:40) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.metrics.DropwizardMetricsFactory.<init>(DropwizardMetricsFactory.java:74) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.metrics.DefaultMetricsFactory.<init>(DefaultMetricsFactory.java:37) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_292]
jce-janusgraph   | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_292]
jce-janusgraph   | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_292]
jce-janusgraph   | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_292]
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:246) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.util.Reflection.buildFromConfig(Reflection.java:108) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildMetricsFactory(DefaultDriverContext.java:541) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getMetricsFactory(DefaultDriverContext.java:877) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.session.DefaultSession.<init>(DefaultSession.java:123) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.internal.core.session.DefaultSession.init(DefaultSession.java:88) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildDefaultSessionAsync(SessionBuilder.java:841) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildAsync(SessionBuilder.java:755) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:773) ~[java-driver-core-4.12.0.jar:na]
jce-janusgraph   | 	at org.janusgraph.diskstorage.cql.CQLStoreManager.initializeSession(CQLStoreManager.java:337) ~[janusgraph-cql-0.6.0-SNAPSHOT.jar:na]
jce-janusgraph   | 	at org.janusgraph.diskstorage.cql.CQLStoreManager.<init>(CQLStoreManager.java:186) ~[janusgraph-cql-0.6.0-SNAPSHOT.jar:na]
jce-janusgraph   | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[na:1.8.0_292]
jce-janusgraph   | 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) ~[na:1.8.0_292]
jce-janusgraph   | 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[na:1.8.0_292]
jce-janusgraph   | 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423) ~[na:1.8.0_292]
jce-janusgraph   | 	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:73) ~[janusgraph-core-0.6.0-SNAPSHOT.jar:na]
jce-janusgraph   | 	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:514) ~[janusgraph-core-0.6.0-SNAPSHOT.jar:na]
jce-janusgraph   | 	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:478) ~[janusgraph-core-0.6.0-SNAPSHOT.jar:na]
jce-janusgraph   | 	at org.janusgraph.graphdb.configuration.builder.GraphDatabaseConfigurationBuilder.build(GraphDatabaseConfigurationBuilder.java:64) ~[janusgraph-core-0.6.0-SNAPSHOT.jar:na]
jce-janusgraph   | 	at org.janusgraph.core.ConfiguredGraphFactory.lambda$open$1(ConfiguredGraphFactory.java:114) ~[janusgraph-core-0.6.0-SNAPSHOT.jar:na]
jce-janusgraph   | 	at org.janusgraph.graphdb.management.JanusGraphManager.openGraph(JanusGraphManager.java:239) ~[janusgraph-core-0.6.0-SNAPSHOT.jar:na]
jce-janusgraph   | 	at org.janusgraph.core.ConfiguredGraphFactory.open(ConfiguredGraphFactory.java:114) ~[janusgraph-core-0.6.0-SNAPSHOT.jar:na]
jce-janusgraph   | 	at org.janusgraph.core.ConfiguredGraphFactory$open$1.call(Unknown Source) ~[na:na]
jce-janusgraph   | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at Script2.createGraph(Script2.groovy:60) ~[na:na]
jce-janusgraph   | 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_292]
jce-janusgraph   | 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_292]
jce-janusgraph   | 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_292]
jce-janusgraph   | 	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_292]
jce-janusgraph   | 	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:101) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:323) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1217) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at groovy.lang.MetaClassImpl.invokeMethodClosure(MetaClassImpl.java:1050) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1092) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1041) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at groovy.lang.Closure.call(Closure.java:405) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.callGlobal(GremlinGroovyScriptEngine.java:763) ~[gremlin-groovy-3.5.0.jar:3.5.0]
jce-janusgraph   | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.access$100(GremlinGroovyScriptEngine.java:93) ~[gremlin-groovy-3.5.0.jar:3.5.0]
jce-janusgraph   | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$3.invokeMethod(GremlinGroovyScriptEngine.java:662) ~[gremlin-groovy-3.5.0.jar:3.5.0]
jce-janusgraph   | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine$3.invokeMethod(GremlinGroovyScriptEngine.java:651) ~[gremlin-groovy-3.5.0.jar:3.5.0]
jce-janusgraph   | 	at groovy.lang.GroovyObjectSupport.invokeMethod(GroovyObjectSupport.java:44) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at groovy.lang.Script.invokeMethod(Script.java:97) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at org.codehaus.groovy.runtime.callsite.PogoMetaClassSite.callCurrent(PogoMetaClassSite.java:71) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:51) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:156) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:168) ~[groovy-2.5.14-indy.jar:2.5.14]
jce-janusgraph   | 	at Script11.run(Script11.groovy:1) ~[na:na]
jce-janusgraph   | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:676) ~[gremlin-groovy-3.5.0.jar:3.5.0]
jce-janusgraph   | 	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:378) ~[gremlin-groovy-3.5.0.jar:3.5.0]
jce-janusgraph   | 	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:233) ~[na:1.8.0_292]
jce-janusgraph   | 	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$0(GremlinExecutor.java:272) ~[gremlin-groovy-3.5.0.jar:3.5.0]
jce-janusgraph   | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_292]
jce-janusgraph   | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[na:1.8.0_292]
jce-janusgraph   | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[na:1.8.0_292]
jce-janusgraph   | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) ~[na:1.8.0_292]
jce-janusgraph   | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) ~[na:1.8.0_292]
jce-janusgraph   | 	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_292]
```

### Discussion
JanusGraph's classpath includes two versions of metrics-core `-cp [...]:/var/janusgraph/lib/metrics-core-3.0.2.jar:/var/janusgraph/lib/metrics-core-4.1.18.jar:[...]`. According to `mvn dependency:tree`, version 3.0.2 comes from `org.apache.tinkerpop:gremlin-server` ([pom.xml](https://github.com/apache/tinkerpop/blob/3.5-dev/pom.xml#L162)), while JanusGraph ([pom.xml](https://github.com/JanusGraph/janusgraph/blob/master/pom.xml#L79)) and Cassandra driver ([pom.xml](https://github.com/datastax/java-driver/blob/4.12.0/pom.xml#L49)) expect 4.1.18.

Both versions of `metrics-core` include class `com.codahale.metrics.MetricsRegistry`. The older version does not have a `gauge()` method which could explain the issue.

**Comment by porunov** [comment]
Fixed in #2723
