### ISSUE TITLE
Using Gremlin Driver connect to Gremlin Server

### ISSUE THREAD

**Issue by wangxen** [JanusGraph/janusgraph#276]
When I  add multiple vertices or edges through gremlin driver, after tens of thousands, it break down：
```
org.janusgraph.core.JanusGraphException: Could not commit transaction due to exception during persistence
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1374)
        at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph$GraphTransaction.doCommit (JanusGraphBlueprintsGraph.java:272)
        at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:105)
	at org.apache.tinkerpop.gremlin.server.GraphManager.lambda$commitAll$10(GraphManager.java:122)
	at java.util.concurrent.ConcurrentHashMap$EntrySetView.forEach(ConcurrentHashMap.java:4795)
	at org.apache.tinkerpop.gremlin.server.GraphManager.commitAll(GraphManager.java:119)
	at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.attemptCommit(AbstractOpProcessor.java:299)
	at org.apache.tinkerpop.gremlin.server.op.AbstractOpProcessor.handleIterator(AbstractOpProcessor.java:168)
	at org.apache.tinkerpop.gremlin.server.op.AbstractEvalOpProcessor.lambda$evalOpInternal$64(AbstractEvalOpProcessor.java:248)
	at org.apache.tinkerpop.gremlin.groovy.engine.GremlinExecutor.lambda$eval$2(GremlinExecutor.java:298)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.janusgraph.core.JanusGraphException: Unexpected exception
	at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:798)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1363)
	... 13 more
Caused by: org.janusgraph.diskstorage.locking.TemporaryLockingException: Temporary locking failure
	at org.janusgraph.diskstorage.locking.AbstractLocker.writeLock(AbstractLocker.java:309)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingStore.acquireLock
	(ExpectedValueCheckingStore.java:103)
	at org.janusgraph.diskstorage.keycolumnvalue.KCVSProxy.acquireLock(KCVSProxy.java:52)
	at org.janusgraph.diskstorage.BackendTransaction.acquireIndexLock(BackendTransaction.java:255)
	at org.janusgraph.graphdb.database.StandardJanusGraph.prepareCommit(StandardJanusGraph.java:565)
	at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:713)
	... 14 more
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Lock write retry count exceeded
	at org.janusgraph.diskstorage.locking.consistentkey.ConsistentKeyLocker.writeSingleLock(ConsistentKeyLocker.java:339)
	at org.janusgraph.diskstorage.locking.consistentkey.ConsistentKeyLocker.writeSingleLock(ConsistentKeyLocker.java:123)
	at org.janusgraph.diskstorage.locking.AbstractLocker.writeLock(AbstractLocker.java:304)
	... 19 more
```

**Comment by mbrukman** [comment]
Sorry to hear you're running into this issue, @wangxen! Can you please provide more information to help debug this:

* which version of JanusGraph are you using
* which storage backend are you using, and configuration for this backend
* your platform (OS and version)
* if possible, a sequence of commands or a script that consistently reproduces this issue

**Comment by wangxen** [comment]
using janusgraph-0.1.0-hadoop2.zip
storage backend：Hbase-1.0.3
I connect to gremlin-server via Java,
the sample demo as follows: 
import org.apache.tinkerpop.gremlin.driver.Client;
import org.apache.tinkerpop.gremlin.driver.Cluster;
       Cluster cluster = Cluster.open("config/remote.yaml");
       Client client = cluster.connect();
       client.submit("graph.addVertex(T.label,'x','name','tom')");
Could you tell me another method to create a batch of vertices or edges?

**Comment by wangxen** [comment]
using janusgraph-0.1.0-hadoop2.zip
storage backend：Hbase-1.0.3
I connect to gremlin-server via Java
demo:
import org.apache.tinkerpop.gremlin.driver.Client;
import org.apache.tinkerpop.gremlin.driver.Cluster;
       Cluster cluster = Cluster.open("config/remote.yaml");
       Client client = cluster.connect();
       client.submit("graph.addVertex(T.label,'x','name','tom')");

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
