### ISSUE TITLE
Error:Temporary failure in storage backend

### ISSUE THREAD

**Issue by absoult-dev** [JanusGraph/janusgraph#2766]
Enviroment:
CDH：5.8.3
Hadoop: Hadoop 2.6
Hbase: 1.2.0

When I run "sh gremlin.sh",It throw exception:
java.lang.RuntimeException: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getDeployment(HBaseStoreManager.java:364) ~[jar:rsrc:janusgraph-hbase-0.2.0.jar!/:na]
at org.janusgraph.diskstorage.hbase.HBaseStoreManager.getFeatures(HBaseStoreManager.java:403) ~[jar:rsrc:janusgraph-hbase-0.2.0.jar!/:na]
at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1377) [jar:rsrc:janusgraph-core-0.2.0.jar!/:na]
at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:164) [jar:rsrc:janusgraph-core-0.2.0.jar!/:na]
at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:133) [jar:rsrc:janusgraph-core-0.2.0.jar!/:na]
at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:80) [jar:rsrc:janusgraph-core-0.2.0.jar!/:na]

I have no idea with this TemporaryBackendException, has anyone met this before?

**Comment by li-boxuan** [comment]
Hi @absoult-dev , janusgraph 0.2.0 is EOL. Would you be able to try 0.5.3 (or 0.6.0, which will be released in a few days)?

**Comment by absoult-dev** [comment]
I had tried 0.5.3,but the same error happened

**Comment by vtslab** [comment]
Hi, using "sh"  is unusual, can you just try bin/gremlin.sh
The TemporaryBackendException can only occur after opening a graph. Can you show the config file for the graph you opened?
