### ISSUE TITLE
hasKey(key) throws NPE

### ISSUE THREAD

**Issue by s-nel** [JanusGraph/janusgraph#285]
In Janus 0.1.1 when doing a simple `hasKey`, I get an NPE:

```
[info]   java.lang.NullPointerException: null value for property key ~key
[info]   at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:250)
[info]   at org.janusgraph.graphdb.relations.AbstractVertexProperty.<init>(AbstractVertexProperty.java:37)
[info]   at org.janusgraph.graphdb.relations.StandardVertexProperty.<init>(StandardVertexProperty.java:36)
[info]   at org.janusgraph.graphdb.query.vertex.BasicVertexCentricQueryBuilder.executeImplicitKeyQuery(BasicVertexCentricQueryBuilder.java:210)
[info]   at org.janusgraph.graphdb.query.vertex.VertexCentricQueryBuilder.properties(VertexCentricQueryBuilder.java:99)
[info]   at org.janusgraph.graphdb.util.ElementHelper.getValues(ElementHelper.java:41)
[info]   at org.janusgraph.graphdb.query.condition.PredicateCondition.evaluate(PredicateCondition.java:66)
[info]   at org.janusgraph.graphdb.query.condition.And.evaluate(And.java:55)
[info]   at org.janusgraph.graphdb.query.graph.GraphCentricQuery.matches(GraphCentricQuery.java:154)
[info]   at org.janusgraph.graphdb.query.QueryProcessor$3.apply(QueryProcessor.java:146)
```

minimal code to reproduce (Scala):

```
    val conf = new BaseConfiguration()
    conf.setProperty("storage.backend","inmemory")
    val graph = JanusGraphFactory.open(conf)

    (1 to 5) foreach { i ⇒
      graph.addVertex(T.label, "planet", "name", s"planet $i")
    }

    graph.traversal().V().hasKey("name").count().next() shouldBe 5

    graph.close
```

**Comment by twilmes** [comment]
Thanks for reporting this. I think that would be the expected behavior for `hasKey` because it operates on properties (e.g. `g.V().properties().hasKey("name")`), not vertices. 

TinkerPop docs: `hasKey(keys...): Remove the traverser if its property does not have any of the keys.`

If you'd like to check for the existence of the `name` property on planet vertices, you can use a regular `has("name")` instead.

**Comment by s-nel** [comment]
Ah okay that makes sense.
