### ISSUE TITLE
StandardJanusGraphTx::expireSchemaElement throws NPE due to race condition

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#2898]
For confirmed bugs, please report:
- Version: 0.6.0, master
- Storage Backend: doesn't matter
- Mixed Index Backend: doesn't matter
- Current Behavior: No NPE should be thrown

I was running [this benchmark](https://gist.github.com/li-boxuan/98d4dc18215e28b239c7433c8c39fb3f) and encountered NPE on v0.6 and master branches (provided that I changed concurrency in https://github.com/JanusGraph/janusgraph/blob/e64facbcdefd9d63ede4bedfbf15b78dc56d4751/janusgraph-core/src/main/java/org/janusgraph/diskstorage/Backend.java#L430-L435 from 1 to 8).

The exception trace is:

```
java.lang.NullPointerException
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.expireSchemaElement(StandardJanusGraphTx.java:1593)
	at org.janusgraph.graphdb.database.management.ManagementLogger.read(ManagementLogger.java:97)
	at org.janusgraph.diskstorage.log.util.ProcessMessageJob.run(ProcessMessageJob.java:46)
```

Apparently, `vertexCache` is null because the transaction has already been closed.

This bug was uncovered by 0.6.0 (08fd019) because now the internal resources are cleared after the transaction gets closed.

The cause is a race condition. Right after `graph.getOpenTransactions()` is invoked in ManagementLogger, the transaction could be released (i.e. `releaseTransaction()` being called) concurrently. Then, when ManagementLogger calls `expireSchemaElement` method for that transaction, NPE occurs.

This is similar to the bug discussed in https://lists.lfaidata.foundation/g/janusgraph-users/topic/potential_transaction_issue/85970858, where NPEs occur because some transaction internal structures are accessed even if the transaction has already been closed. Nonetheless, it is not yet clear what is the exact reason for this NPE.

**Comment by li-boxuan** [comment]
A potential fix is to ignore the method call if `vertexCache` is null.
