### ISSUE TITLE
Failing tests when building janusgraph-examples standalone

### ISSUE THREAD

**Issue by vtslab** [JanusGraph/janusgraph#2911]
It was reported on the user list that janusgraph-examples as included in the binary distribution does not build in standalone fashion.

- Version: 0.6.0
- Link to discussed bug: https://lists.lfaidata.foundation/g/janusgraph-users/topic/88046694 
- Expected Behavior:  build with success
- Current Behavior: failing tests during build

Steps to Reproduce: 
- unzip binary distribution
- cd examples
- mvn clean install  # as prescribed in the examples/README.md 

Workaround for using examples:
`mvn clean install -DskipTests`

### Stack Trace (if you have one)
-------------------------------------------------------------------------------
Test set: org.janusgraph.example.GraphAppTest
-------------------------------------------------------------------------------
Tests run: 6, Failures: 2, Errors: 0, Skipped: 0, Time elapsed: 0.832 s <<< FAILURE! - in org.janusgraph.example.GraphAppTest
openGraphConfigNotFound  Time elapsed: 0.015 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <java.io.FileNotFoundException> but was: <org.apache.commons.configuration2.ex.ConfigurationException>
	at org.janusgraph.example.GraphAppTest.openGraphConfigNotFound(GraphAppTest.java:70)
Caused by: org.apache.commons.configuration2.ex.ConfigurationException: Could not locate: org.apache.commons.configuration2.io.FileLocator@439a8f59[fileName=conf/foobar,basePath=<null>,sourceURL=,encoding=ISO-8859-1,fileSystem=<null>,locationStrategy=<null>]
	at org.janusgraph.example.GraphAppTest.lambda$openGraphConfigNotFound$1(GraphAppTest.java:70)
	at org.janusgraph.example.GraphAppTest.openGraphConfigNotFound(GraphAppTest.java:70)

openGraphNullConfig  Time elapsed: 0.004 s  <<< FAILURE!
org.opentest4j.AssertionFailedError: Unexpected exception type thrown ==> expected: <java.lang.NullPointerException> but was: <java.lang.RuntimeException>
	at org.janusgraph.example.GraphAppTest.openGraphNullConfig(GraphAppTest.java:65)
Caused by: java.lang.RuntimeException: Configuration must contain a valid 'gremlin.graph' setting
	at org.janusgraph.example.GraphAppTest.lambda$openGraphNullConfig$0(GraphAppTest.java:65)
	at org.janusgraph.example.GraphAppTest.openGraphNullConfig(GraphAppTest.java:65)

**Comment by farodin91** [comment]
I think it would be a good idea to look into the examples. I don't had run them over some period of time.
