### ISSUE TITLE
Multiple edges with same edgeid returned by VertexCentric indices

### ISSUE THREAD

**Issue by pankajydv** [JanusGraph/janusgraph#301]
The issue reproduces fairly easily on my production environment (on Titan), and reproduces on my dev environment only after few retries and changing the ConsistencyModifier to FORK followed by LOCK.

Following is the code, I used to reproduce the issue on my local environment on JanusGraph 0.1.1, Backed by Apahe-Cassandra 2.1.7

```
	private void createPropertiesAndIndexes() {
		JanusGraphManagement mgmt = graph.openManagement();
		PropertyKey key = null;
		JanusGraphIndex index = null;
		EdgeLabel label = null;
		
		//Vertex
		key = mgmt.makePropertyKey(MSID).dataType(Integer.class).cardinality(Cardinality.SINGLE).make();
		index = mgmt.buildIndex("by"+MSID, Vertex.class).addKey(key).unique().buildCompositeIndex();
		mgmt.setConsistency(index, ConsistencyModifier.LOCK);
		
		key = mgmt.makePropertyKey(TYPE).dataType(Short.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey(CREATEDAT).dataType(Long.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey(CMSTYPE).dataType(Integer.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey(MSNAME).dataType(String.class).cardinality(Cardinality.SINGLE).make();
		
		//Edge
		label = mgmt.makeEdgeLabel(HIE_CHILD).multiplicity(Multiplicity.MULTI).make();

		key = mgmt.makePropertyKey(HOSTID_E).dataType(Integer.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey(CREATEAT_E).dataType(Long.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey(CMSTYPE_E).dataType(Integer.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey(STATUS_E).dataType(Short.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey(HNAME).dataType(String.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey(HRANK).dataType(Float.class).cardinality(Cardinality.SINGLE).make();
		
		mgmt.buildEdgeIndex(label, "HSCCERDecr", Direction.BOTH, Order.decr,
				mgmt.getPropertyKey(HOSTID_E),
				mgmt.getPropertyKey(STATUS_E),
				mgmt.getPropertyKey(CMSTYPE_E),
				mgmt.getPropertyKey(HRANK));
		
		mgmt.commit();
	}
	private void createNodesAndEdges() {
		System.out.println("BEGIN createNodesAndEdges");
		JanusGraphTransaction trxn = graph.newTransaction();
		try {
			//create msid=0;
			Vertex root = createMasterVertex(0, 1);
			
			//create level-1;
			Vertex l1V, l2V;
			for(int i =1; i <= NUM_L1; i++) {
				int l1msid = i*MULTIPLIER;
				l1V = createMasterVertex(l1msid, 2);
				Edge edge1 = createEdge(l1V, root, i);
				edge1.property(CMSTYPE_E, 2);
				
				//create level-2;
				for(int j =1; j <= NUM_L2; j++) {
					int l2msid = l1msid + j;
					l2V = createMasterVertex(l2msid, 1001);
					Edge edge2= createEdge(l2V, l1V, j);
					edge2.property(CMSTYPE_E, 1001);
				}
			}
			System.out.println("END createNodesAndEdges");
		} finally {
			trxn.commit();
		}
	}

	private Vertex createMasterVertex(int msid, int cmstype) {
		Vertex masterV = graph.addVertex();
		masterV.property(MSID, msid);
		masterV.property(TYPE, 0);
		masterV.property(CREATEDAT, Math.abs(random.nextLong()));
		masterV.property(CMSTYPE, cmstype);
		masterV.property(MSNAME, "Master Vertex " + msid + " Of Type " + cmstype);
		System.out.println("Created MasterVertex: msid: " + msid + "; cmstype: " + cmstype);
		return masterV;
	}

	private Edge createEdge(Vertex childV, Vertex parentV, int rank) {
		Edge edge = parentV.addEdge(HIE_CHILD, childV);
		
		edge.property(HOSTID_E, 83);
		edge.property(CREATEAT_E, Math.abs(random.nextLong()));
		edge.property(STATUS_E, 2);
		edge.property(HNAME, childV.id() + " Child of Parent " + parentV.id() + ", rank: " + rank);
		edge.property(HRANK);
		
		return edge;
	}

```

After chaning the ConsistencyModifier from DEFAULT to FORK and then LOCK (however in production, I don't need to change the ConsistencyModifer.

The problem is If I try to concurrently modify an edge with n threads, I get n copies of the same edge, with same edgeid and then gremlin queries start behaving very abruptly. Like direct children on some vertex are m, but if I fire a query which uses the VertexCentricIndex the number of children returned are m+n (n was the number of threads I used). I used the following code to reproduce the issue.

```
                       Thread[] threads = new Thread[numThreads];
			for (int i = 0; i < numThreads; i++) {
				threads[i] = new Thread(new EdgeUpdator(graph, parent, child, hostid));
			}
			for (int i = 0; i < numThreads; i++) {
				threads[i].start();
			}
			for (int i = 0; i < numThreads; i++) {
				threads[i].join();
			}

                public void run() {
			JanusGraphTransaction trxn = graph.newTransaction();
			GraphTraversalSource g = trxn.traversal();
			Edge edge = (Edge) g.V().has("msid", parent).outE("hie_child").as("e")
					.has("hostid_e", hostid)
					.inV().has("msid", child)
					.select("e").next();
			Random random = new Random(System.nanoTime());
			Long updatedAt = random.nextLong();
			
			edge.property("hrank", random.nextInt());
			edge.property("updatedAt_e", updatedAt);
			
			System.out.println("updatedAt: {}" + updatedAt);
			trxn.commit();
			System.out.println("updatedAt: {}" + updatedAt);
		}
```

Following is the behavior, I observed through gremlin console:

Before the concurrent modification:
```

gremlin> g.V().has('msid', 1000000).outE('hie_child').as('e').inV().has('msid', 1000002).select('e').count()
==>1
gremlin> g.V().has('msid', 1000000).outE('hie_child').has('hostid_e', 83).as('e').inV().has('msid', 1000002).select('e').count()
==>1
```

After the concurrent modification
```

gremlin> g.V().has('msid', 1000000).outE('hie_child').has('hostid_e', 83).as('e').inV().has('msid', 1000002).select('e').count()
==>10
gremlin> g.V().has('msid', 1000000).outE('hie_child').as('e').inV().has('msid', 1000002).select('e').count()
==>1
gremlin> g.V().has('msid', 1000000).outE('hie_child').has('hostid_e', 83).as('e').inV().has('msid', 1000002).select('e').range(1,100).count()
==>9
gremlin> g.V().has('msid', 1000000).outE('hie_child').has('hostid_e', 83).as('e').inV().has('msid', 1000002).select('e').range(1,100).drop()
gremlin> g.V().has('msid', 1000000).outE('hie_child').has('hostid_e', 83).as('e').inV().has('msid', 1000002).select('e').count()
==>0
gremlin> g.V().has('msid', 1000000).outE('hie_child').as('e').inV().has('msid', 1000002).select('e').count()
==>0
gremlin> 
gremlin> g.tx().commit()
==>null
gremlin> g.V().has('msid', 1000000).outE('hie_child').has('hostid_e', 83).as('e').inV().has('msid', 1000002).select('e').count()
==>9
gremlin> g.V().has('msid', 1000000).outE('hie_child').as('e').inV().has('msid', 1000002).select('e').count()
==>0
```

Please note within the transaction after deleting the affected edge, it seems all the edges are deleted, but after transaction commit, n-1 edges re-appear using the VertexCentric index query, but there is no edge if that VertexCentric Index is not used.

**Comment by pankajydv** [comment]
Any updates here, we are suffering from this issue in our Live environment.

**Comment by pankajydv** [comment]
Any update, on this?

**Comment by mbrukman** [comment]
@pankajydv — could you please try to see if it's possible to reproduce the same issue with JanusGraph 0.2.0 and/or `master` branch as well? A number of changes have been made, including upgrades to dependencies.

**Comment by pankajydv** [comment]
@mbrukman - thanks for the update, let's test this on the latest JanusGraph codebase and we'll let you know the results.

**Comment by rahul38888** [comment]
Same issue is reproducible  on JanusGraph 0.2.0 with Apache Cassandra 3.0.9 as well. The properties corresponding to  are following:

```properties
storage.backend=cassandra
storage.cassandra.replication-strategy-class=org.apache.cassandra.locator.NetworkTopologyStrategy
storage.cassandra.replication-strategy-options= dc1, 2
storage.hostname=xxx.xxx.xxx.xxx
storage.cassandra.keyspace=janustest
storage.cassandra.frame-size-mb=300
storage.read-only=false
query.force-index=true
```

**Comment by pankajydv** [comment]
@mbrukman - one of my colleague tried this code with JanusGraph 0.2 and Apache Cassandra 3.0.9 and we are still seeing this issue - request you to please prioritize this as this sometimes affect our live production system and is tedious to fix. In our observation what goes wrong is 2 or more copies get indexed in the VertexCentric index having same edge id (if you query in such a way that this VertexCentric index is not used then only 1 edge is found) and starts giving confusing results. This is even after we have set ConsistencyModifier to LOCK for this edge, and it's not possible to change the ConsistencyModifer of the VertexCentric index.
 Please let us know if you need any more help/information in the form of logs etc from our side.

**Comment by pankajydv** [comment]
@rahul38888 please attach the code and config you used to reproduce this issue here in zip format.

**Comment by rahul38888** [comment]
The code used to reproduce the issue is following.

**Graph creation code**
```java
package com.cms.til.test.janus.creation;

import java.util.Properties;
import java.util.Random;

import org.apache.commons.configuration.BaseConfiguration;
import org.apache.tinkerpop.gremlin.process.traversal.Order;
import org.apache.tinkerpop.gremlin.structure.Direction;
import org.apache.tinkerpop.gremlin.structure.Edge;
import org.apache.tinkerpop.gremlin.structure.Vertex;
import org.janusgraph.core.Cardinality;
import org.janusgraph.core.EdgeLabel;
import org.janusgraph.core.JanusGraph;
import org.janusgraph.core.JanusGraphFactory;
import org.janusgraph.core.JanusGraphTransaction;
import org.janusgraph.core.Multiplicity;
import org.janusgraph.core.PropertyKey;
import org.janusgraph.core.schema.ConsistencyModifier;
import org.janusgraph.core.schema.JanusGraphIndex;
import org.janusgraph.core.schema.JanusGraphManagement;
import org.springframework.context.support.AbstractApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class DummyJanusGraphCreator {
	
	private static Integer NUM_L1 = 10;
	private static Integer NUM_L2 = 10;
	private static Integer MULTIPLIER = 123456;
	
	private static AbstractApplicationContext context = null;
	
	private static Properties properties = null;
	private static JanusGraph graph = null;
	
	private static Random randomGenerator = new Random();

	public static void main(String[] args) {

		System.out.println("Loading application context");
		context = new ClassPathXmlApplicationContext("spring.xml");
		properties = context.getBean("properties", Properties.class);
		
		if(properties!=null){
			System.out.println("Creating JanusGraph");
			setGraph();
			System.out.println("Hosts connected : " + graph);
		}

		System.out.println("Staring creating properties and their indexes");
		createPropertiesAndIndexes();
		
		System.out.println("Staring creating Nodes and their edges");
		createNodesAndEdges();

		System.out.println("Finished creating graph : " + properties.getProperty("storage.cassandra.keyspace"));
		shutdown();
		
	}
	
	private static void setGraph(){

		BaseConfiguration config = new BaseConfiguration();
		for(Object property:properties.keySet()){
			System.out.println((String)property + " : " + properties.get(property));
			config.setProperty((String)property, properties.get(property));
		}
		
		graph = JanusGraphFactory.open(config);
	}
	
	private static void createPropertiesAndIndexes() {
		JanusGraphManagement mgmt = graph.openManagement();
		PropertyKey key = null;
		JanusGraphIndex index = null;
		EdgeLabel label = null;
		
		//Vertex
		key = mgmt.makePropertyKey("msid").dataType(Integer.class).cardinality(Cardinality.SINGLE).make();
		index = mgmt.buildIndex("bymsid", Vertex.class).addKey(key).unique().buildCompositeIndex();
		mgmt.setConsistency(index, ConsistencyModifier.LOCK);
		
		key = mgmt.makePropertyKey("type").dataType(Short.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey("createdat").dataType(Long.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey("cmstype").dataType(Integer.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey("msname").dataType(String.class).cardinality(Cardinality.SINGLE).make();
		
		//Edge
		label = mgmt.makeEdgeLabel("hie_child").multiplicity(Multiplicity.MULTI).make();

		key = mgmt.makePropertyKey("hostid_e").dataType(Integer.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey("createdat_e").dataType(Long.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey("cmstype_e").dataType(Integer.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey("status_e").dataType(Short.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey("hname").dataType(String.class).cardinality(Cardinality.SINGLE).make();
		key = mgmt.makePropertyKey("hrank").dataType(Float.class).cardinality(Cardinality.SINGLE).make();
		
		mgmt.buildEdgeIndex(label, "HSCCERDecr", Direction.BOTH, Order.decr,
				mgmt.getPropertyKey("hostid_e"),
				mgmt.getPropertyKey("status_e"),
				mgmt.getPropertyKey("cmstype_e"),
				mgmt.getPropertyKey("hrank"));
		
		mgmt.commit();
	}
	
	private static void createNodesAndEdges() {
		System.out.println("BEGIN createNodesAndEdges");
		JanusGraphTransaction trxn = graph.newTransaction();
		try {
			//create msid=0;
			Vertex root = createMasterVertex(0, 1);
			
			//create level-1;
			Vertex l1V, l2V;
			for(int i =1; i <= NUM_L1; i++) {
				int l1msid = i*MULTIPLIER;
				l1V = createMasterVertex(l1msid, 2);
				Edge edge1 = createEdge(l1V, root, i);
				edge1.property("cmstype_e", 2);
				
				//create level-2;
				for(int j =1; j <= NUM_L2; j++) {
					int l2msid = l1msid + j;
					l2V = createMasterVertex(l2msid, 1001);
					Edge edge2= createEdge(l2V, l1V, j);
					edge2.property("cmstype_e", 1001);
				}
			}
			System.out.println("END createNodesAndEdges");
		}
		catch (Exception e) {
			System.out.println("Exception while creating vertex and edges. " + e.getStackTrace());
		}
		
		trxn.commit();
	}

	private static Vertex createMasterVertex(int msid, int cmstype) {
		Vertex masterV = graph.addVertex();
		masterV.property("msid", msid);
		masterV.property("type", 0);
		masterV.property("createdAt", Math.abs(randomGenerator.nextLong()));
		masterV.property("cmstype", cmstype);
		masterV.property("msname", "Master Vertex " + msid + " Of Type " + cmstype);
		System.out.println("Created MasterVertex: msid: " + msid + "; cmstype: " + cmstype);
		System.out.println("Vertex : " + masterV);
		return masterV;
	}


	private static Edge createEdge(Vertex childV, Vertex parentV, int rank) {
		Edge edge = parentV.addEdge("hie_child", childV);
		
		edge.property("hostid_e", 83);
		edge.property("createdAt_e", Math.abs(randomGenerator.nextLong()));
		edge.property("status_e", 2);
		edge.property("hname", childV.id() + " Child of Parent " + parentV.id() + ", rank: " + rank);
		edge.property("hrank");
		System.out.println("Edge : " + edge);
		
		return edge;
	}
	
	private static void shutdown() {
		if(graph != null && graph.isOpen()) {
			System.out.println("Shutting down the graph!");
			graph.tx().commit();
			graph.close();
		}
	}
	
}

```



**Code for concurrent mutation of edge**

```java
package com.cms.til.test.janus.create.error;

import java.util.Properties;
import java.util.Random;

import org.apache.commons.configuration.BaseConfiguration;
import org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource;
import org.janusgraph.core.JanusGraph;
import org.janusgraph.core.JanusGraphEdge;
import org.janusgraph.core.JanusGraphFactory;
import org.janusgraph.core.JanusGraphTransaction;
import org.springframework.context.support.AbstractApplicationContext;
import org.springframework.context.support.ClassPathXmlApplicationContext;

public class JanusConcurrentEdgeUpdator {

	private static AbstractApplicationContext context = null;
	
	private static Properties properties = null;
	private static JanusGraph graph = null;
	
	public static void main(String[] args) throws InterruptedException {
		
		System.out.println("Loading application context");
		context = new ClassPathXmlApplicationContext("spring.xml");
		properties = context.getBean("properties", Properties.class);
		
		if(properties!=null){
			System.out.println("Creating TitanGraph");
			setGraph();
		}
		
	    try {
	        int parent = 246912;
	        int child = 246913;
	        int hostid = 83;
	        int numThreads = 10;
	        Thread[] threads = new Thread[numThreads];
	        for(int i =0; i < numThreads; i++) {
	            threads[i] = new Thread(new JanusEdgeUpdator(graph, parent, child, hostid));
	        }
	        for(int i =0; i < numThreads; i++) {
	        	System.out.println("Starting EdgeUpdator thread : " + threads[i].getName());
	            threads[i].start();
	        }
	        for(int i = 0; i < numThreads; i++) {
	        	System.out.println("Waiting for EdgeUpdator thread : " + threads[i].getName());
	            threads[i].join();
	        }
	    } finally {
        	System.out.println("All threads have finished!");
	        graph.close();
	    }
	}
	
	private static void setGraph(){

		BaseConfiguration config = new BaseConfiguration();
		for(Object property:properties.keySet()){
			config.setProperty((String)property, properties.get(property));
		}
		
		graph = JanusGraphFactory.open(config);
	}
	
}

class JanusEdgeUpdator implements Runnable{
	public JanusEdgeUpdator(JanusGraph graph, int parent, int child, int hostid) {
        this.graph = graph;
        this.parent = parent;
        this.child = child;
        this.hostid = hostid;
    }

    private int parent;
    private int child;
    private int hostid;
    private JanusGraph graph;

    public void run() {
    	
    	Thread thread = Thread.currentThread();
    	
        JanusGraphTransaction trxn = graph.newTransaction();
        GraphTraversalSource g = trxn.traversal();
        
        JanusGraphEdge edge = (JanusGraphEdge)g.V().has("msid", parent).outE("hie_child").
        		has("hostid_e", hostid).as("e").
        		inV().has("msid", child).select("e").next();
        Random random = new Random(System.nanoTime());
        edge.property("updatedAt", random.nextLong());
        edge.property("hrank", random.nextInt());
        trxn.commit();
        System.out.println("Commit completed for " + thread.getName());
    }
}
```

**Project Object Model file**

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>

  <groupId>com.cms.til.test</groupId>
  <artifactId>testTIL</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>jar</packaging>
  <url>http://maven.apache.org</url>
	<properties>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<version.aspectj>1.7.3</version.aspectj>
		<jackson.version>2.6.1</jackson.version>
		<cms.version>4.1.0-SNAPSHOT</cms.version>
	</properties>

  <name>testTIL</name>

  <dependencies>
		<dependency>
			<groupId>junit</groupId>
			<artifactId>junit</artifactId>
			<version>4.12</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-api</artifactId>
			<version>1.7.7</version>
		</dependency>

		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>jcl-over-slf4j</artifactId>
			<version>1.7.7</version>
			<scope>runtime</scope>
		</dependency>
		<dependency>
			<groupId>org.slf4j</groupId>
			<artifactId>slf4j-log4j12</artifactId>
			<version>1.7.7</version>
		</dependency>

		<dependency>
		   <groupId>org.janusgraph</groupId>
		   <artifactId>janusgraph-core</artifactId>
		   <version>0.2.0</version>
		</dependency>

		<dependency>
			<groupId>org.janusgraph</groupId>
			<artifactId>janusgraph-cassandra</artifactId>
			<version>0.2.0</version>
		</dependency>

  </dependencies>

  <build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.1</version>
				<configuration>
					<source>1.8</source>
					<target>1.8</target>
				</configuration>
			</plugin>
		</plugins>
	</build>
</project>
```

**spring.xml**
```xml
<?xml version="1.0" encoding="UTF-8"?>

<beans xmlns="http://www.springframework.org/schema/beans"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:ctx="http://www.springframework.org/schema/context"
	xmlns:utl="http://www.springframework.org/schema/util"
	xsi:schemaLocation="http://www.springframework.org/schema/beans 
		http://www.springframework.org/schema/beans/spring-beans.xsd
        http://www.springframework.org/schema/context
        http://www.springframework.org/schema/context/spring-context.xsd
        http://www.springframework.org/schema/util
        http://www.springframework.org/schema/util/spring-util.xsd
        ">

	<utl:properties id="properties" location="classpath:graph.properties" />

</beans>
```

**graph.properties**

```properties
storage.backend=cassandra
storage.cassandra.replication-strategy-class=org.apache.cassandra.locator.NetworkTopologyStrategy
storage.cassandra.replication-strategy-options= dc1, 2
storage.hostname=xxx.xxx.xxx.xxx
storage.cassandra.keyspace=janustest1
storage.cassandra.frame-size-mb=300
storage.read-only=false
query.force-index=true
```

**Comment by robertdale** [comment]
First, this isn't a working example.  It would be great if you had something where one could just do `mvn test`.
Next, it's not clear what the expected is vs. actual. Again, if you had a failed test case with `mvn test`, it would be more clear.
Finally, it looks like you're missing a consistency `LOCK` on edgeIndex "HSCCERDecr"
Finally,

**Comment by rahul38888** [comment]
We have created a working maven test to reproduce the issue. Please find the project attached with this.

Change the **graph.properties** in classpath accordingly.

[testTemp.zip](https://github.com/JanusGraph/janusgraph/files/1622387/testTemp.zip)

**Comment by pankajydv** [comment]
@robertdale We have updated our code in Junit Testcase format, so now the issue is reproducible via `mvn test`. We tried setting consistency `LOCK` on edgeindex(VertexCentric index) "HSCCERDecr", but it seems this is not supported by Titan/JanusGraph, as we get the following exception when we try this:

```javascript
gremlin> edge=mgmt.getRelationType('hie_child')
gremlin> index=mgmt.getRelationIndex(edge, 'HSCCERDecr')
gremlin> mgmt.setConsistency(index, ConsistencyModifier.LOCK)
Cannot change consistency of schema element: HSCCERDecr
Type ':help' or ':h' for help.
Display stack trace? [yN]y
java.lang.IllegalArgumentException: Cannot change consistency of schema element: HSCCERDecr
at org.janusgraph.graphdb.database.management.ManagementSystem.setConsistency(ManagementSystem.java:1115)

```

**Comment by amcp** [comment]
Isn’t consistency part immutable? I think you need to set the consistency when you create the index.

**Comment by rahul38888** [comment]
Thanks @amcp . I tried to set consistency after building vertex-centric index, as following
```java
RelationTypeIndex hie_childIndex = mgmt.buildEdgeIndex(label, "HSCCERDecr", Direction.BOTH, Order.decr,
				mgmt.getPropertyKey("hostid_e"),
				mgmt.getPropertyKey("status_e"),
				mgmt.getPropertyKey("cmstype_e"),
				mgmt.getPropertyKey("hrank"));
		
mgmt.setConsistency(hie_childIndex, ConsistencyModifier.LOCK);
```
This throws following exception:
```
java.lang.IllegalArgumentException: Cannot change consistency of schema element: HSCCERDecr
at org.janusgraph.graphdb.database.management.ManagementSystem.setConsistency(ManagementSystem.java:1115)
```

Also, there seems no implementation of _JanusGraphManagement#buildEdgeIndex_ which would take consistency as an argument.

Its seems this is not allowed even when the index is being created.

Please guide me if I am missing something.

**Comment by pankajydv** [comment]
Any update here?

**Comment by rahul38888** [comment]
The re-runnable code to reproduce the issue is attached below:

[janusedgetest.zip](https://github.com/JanusGraph/janusgraph/files/1641922/janusedgetest.zip)

**Comment by chupman** [comment]
Hi @rahul38888 I'd like to help reproduce the issue. Would it be possible for you to put the code from your zip into a fresh github repository with the steps required to reproduce on a fresh system included in the readme?

**Comment by chupman** [comment]
Thanks @pankajydv, I was able to recreate the issue with the repo. I was trying the same thing with the zip yesterday and it was failing before it got to the use case. I forked and uploaded the [output xml](https://github.com/chupman/janusedgetest/blob/master/TEST-com.cms.til.graph.janus.JanusMultipleEdgesTest.xml) since 2400 lines seemed a bit long for a Gist.

**Comment by pankajydv** [comment]
@chupman - are you still working on this. Can you please share, if there is an update.

**Comment by pluradj** [comment]
It doesn't look like the test code ([`JanusMultipleEdgesTest`](https://github.com/pankajydv/janusedgetest/blob/master/src/test/java/com/cms/til/graph/janus/JanusMultipleEdgesTest.java#L97) and [`JanusEdgeUpdator `](https://github.com/pankajydv/janusedgetest/blob/master/src/main/java/com/cms/til/graph/janus/JanusEdgeUpdator.java#L27)) is using [multi-threaded transactions](http://docs.janusgraph.org/latest/tx.html#multi-thread-tx) as described in the JanusGraph docs.

**Comment by pankajydv** [comment]
@pluradj - Sorry didn't get your point. Our use case suits a different transaction for every thread, allowing every thread to work independently.

@mbrukman - Request you to please assign this issue to someone so as to expedite the solution to this problem.

**Comment by pankajydv** [comment]
We tried to figure out the root cause of this problem by looking at the code of tag v0.2.0 and we see that the code in
 `org.janusgraph.graphdb.database.StandardJanusGraph.prepareCommit(...)` is not able to acquire edge LOCK through
`org.janusgraph.graphdb.database.StandardJanusGraph.acquireLock(InternalRelation, int, boolean)` for the following operations

> //1) Collect deleted edges and their index updates and acquire edge locks
> &
> //2) Collect added edges and their index updates and acquire edge locks
> 

We modified the code of the acquireLock method to return true even in case of 'MULTI' edges if the edge consistency level is set to LOCK and could resolve this issue. Can anyone please let's know if this can lead to any discrepancy. Please note we have already tested MULTIPLE edges creation between a pair of vertices and it works fine with this change.

**Comment by pankajydv** [comment]
Looking at the code we can conclude that an edge with a multiplicity of MULTI will never be able to acquire LOCK. Can someone please throw some light on **why is an edge with multiplicity MULTI is not supposed to acquire** lock and if it is then how can we make the edge modifications acquire the LOCK. Please note **edge consistency is already set to LOCK**.

**Comment by pluradj** [comment]
@pankajydv Do you have a public fork with your changes? It would be easier for understanding what you are proposing, and ultimately could lead to a pull request from you.

**Comment by pankajydv** [comment]
@pluradj  Please refer to my public [fork](https://github.com/pankajydv/janusgraph/tree/acquirelock_issue-301) with the changes corresponding to the [comment](https://github.com/JanusGraph/janusgraph/issues/301#issuecomment-364864804).

**Comment by chupman** [comment]
HI @pankajydv, I'm curious why you're locking the edge label instead of the property. Based off the [docs](http://docs.janusgraph.org/latest/eventual-consistency.html) it seems like it's not recommended to rely on locking this way with Cassandra. Would using the consistency modifier [FORK](http://docs.janusgraph.org/latest/eventual-consistency.html#_data_consistency_without_locks) rather than LOCK work for your use case?

**Comment by pankajydv** [comment]
@chupman 

- I have tried setting LOCK on edge as well as on all of the edge properties, but the duplicate edges with the same edge-id issue still persist.

- The issue doesn't look like a Cassandra level inconsistency issue. I can say that because if I make the aquireLock method to return true - the issue get's resolved. Hence it looks like the issue is because the edge modification path is not acquiring LOCK.

- with edge consistency set to FORK, I am still getting multiple edges between these vertices the only difference is this time they all have different ids, this is expected behavior as per the [docs](http://docs.janusgraph.org/latest/eventual-consistency.html#_forking_edges). What we need is only a single edge between a pair of vertices depending on the value of an edge property.

**Comment by cjxqhhh** [comment]
Any updates on this? It's an important issue with data consistency I think.
