### ISSUE TITLE
Flaky CQL test: testReindexingForEdgeIndex

### ISSUE THREAD

**Issue by FlorianHockmann** [JanusGraph/janusgraph#3142]
## Flaky Test

* **Test Name:** CQLGraphTest>JanusGraphTest.testReindexingForEdgeIndex
* **Link:** https://github.com/JanusGraph/janusgraph/blob/0b000d8d691e309c11c6a1e4a2382b79fdef0526/janusgraph-backend-testutils/src/main/java/org/janusgraph/graphdb/JanusGraphTest.java#L7133
* **Branch:** master (PR was: #3136)
* **Notes:** Job was: `tests (cql, -Pcassandra3-murmur -Dtest="**/graphdb/cql/*", murmur-graphdb, 8) `

### Stack Trace

The error is:
```
java.lang.IllegalArgumentException: Update action [ENABLE_INDEX] cannot be invoked for index with status [INSTALLED]
```

and there are several stack traces like this one logged just before:

```
org.janusgraph.core.JanusGraphException: Could not commit transaction due to exception during persistence
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1538)
	at org.janusgraph.graphdb.JanusGraphTest$4.run(JanusGraphTest.java:3192)
Caused by: org.janusgraph.diskstorage.locking.PermanentLockingException: Local lock contention
	at org.janusgraph.diskstorage.locking.AbstractLocker.writeLock(AbstractLocker.java:324)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingStore.acquireLock(ExpectedValueCheckingStore.java:102)
	at org.janusgraph.diskstorage.keycolumnvalue.KCVSProxy.acquireLock(KCVSProxy.java:52)
	at org.janusgraph.diskstorage.BackendTransaction.acquireIndexLock(BackendTransaction.java:258)
	at org.janusgraph.graphdb.database.StandardJanusGraph.prepareCommit(StandardJanusGraph.java:636)
	at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:776)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1527)
	... 1 more
org.janusgraph.core.JanusGraphException: Could not commit transaction due to exception during persistence
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1538)
	at org.janusgraph.graphdb.JanusGraphTest$4.run(JanusGraphTest.java:3192)
Caused by: org.janusgraph.diskstorage.locking.PermanentLockingException: Local lock contention
	at org.janusgraph.diskstorage.locking.AbstractLocker.writeLock(AbstractLocker.java:324)
	at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingStore.acquireLock(ExpectedValueCheckingStore.java:102)
	at org.janusgraph.diskstorage.keycolumnvalue.KCVSProxy.acquireLock(KCVSProxy.java:52)
	at org.janusgraph.diskstorage.BackendTransaction.acquireIndexLock(BackendTransaction.java:258)
	at org.janusgraph.graphdb.database.StandardJanusGraph.prepareCommit(StandardJanusGraph.java:636)
	at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:776)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1527)
	... 1 more
```

**Comment by FlorianHockmann** [comment]
Also flaky for `CQLGraphCacheTest`:

```
Error:  Errors: 
Error:    CQLGraphCacheTest>JanusGraphTest.testReindexingForEdgeIndex:8778 » IllegalArgument Update action [ENABLE_INDEX] cannot be invoked for index with status [INSTALLED]
```
