### ISSUE TITLE
GraphBinaryMessageSerializerV1 cause a geoshape-read error

### ISSUE THREAD

**Issue by dh-cloud** [JanusGraph/janusgraph#3181]
In a certain situation, reading a geoshape point by GraphBinaryMessageSerializerV1 will cause an IndexOutOfBoundsException. But in some situation is ok. For example:

- correct geoshape point
```
29.7154387159,120.20480209799999
29.7154387134,120.20480209799999
29.7154387334,120.20480209799999
29.7154387334,120.2048
29.7154387334,29.7154387334
29.71543872,29.7154387334
29.715438723,29.7154387334
29.7154387233,29.7154387334
```
- error geoshape point
```
29.7154388159,120.20480209799999
29.7154387234,120.20480209799999
29.7154387234,120.2048
29.7154387334,29.7154387234
29.7154387234,29.7154387334
29.7154387235,29.7154387334
```
 janusgraph client configutation:
```
hosts: [0.0.0.0]
port: 8182
serializer: {
    className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1,
    config: {
        ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry]
    }
}
```
For confirmed bugs, please report:

- Version: 0.6.0, 0.6.1, 0.6.2
- Storage Backend: hbase
- Mixed Index Backend: elasticsearch
- Link to discussed bug: 
- Expected Behavior:
- Current Behavior:
- Steps to Reproduce:

### Stack Trace (if you have one)

```
2022-08-15 11:38:51,021 ERROR [https-jsse-nio-8888-exec-3] org.apache.catalina.core.ContainerBase.[Tomcat].[localhost].[/].[dispatcherServlet] : Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is java.util.concurrent.CompletionException: io.netty.handler.codec.DecoderException: java.lang.IndexOutOfBoundsException: readerIndex(299) + length(4) exceeds writerIndex(299): CompositeByteBuf(ridx: 299, widx: 299, cap: 299, components=1)] with root cause
java.lang.IndexOutOfBoundsException: readerIndex(299) + length(4) exceeds writerIndex(299): CompositeByteBuf(ridx: 299, widx: 299, cap: 299, components=1)
        at io.netty.buffer.AbstractByteBuf.checkReadableBytes0(AbstractByteBuf.java:1478)
        at io.netty.buffer.AbstractByteBuf.readInt(AbstractByteBuf.java:811)
        at org.apache.tinkerpop.gremlin.driver.ser.NettyBuffer.readInt(NettyBuffer.java:112)
        at org.janusgraph.graphdb.tinkerpop.io.binary.GeoshapeGraphBinarySerializer$BufferInputStream.read(GeoshapeGraphBinarySerializer.java:41)
        at java.base/java.io.InputStream.read(InputStream.java:280)
        at java.base/java.io.DataInputStream.readFully(DataInputStream.java:200)
        at java.base/java.io.DataInputStream.readLong(DataInputStream.java:421)
        at java.base/java.io.DataInputStream.readDouble(DataInputStream.java:473)
        at org.locationtech.spatial4j.io.BinaryCodec.readDim(BinaryCodec.java:109)
        at org.locationtech.spatial4j.io.jts.JtsBinaryCodec.readDim(JtsBinaryCodec.java:46)
        at org.locationtech.spatial4j.io.BinaryCodec.readPoint(BinaryCodec.java:117)
        at org.locationtech.spatial4j.io.BinaryCodec.readShapeByTypeIfSupported(BinaryCodec.java:66)
        at org.locationtech.spatial4j.io.jts.JtsBinaryCodec.readShapeByTypeIfSupported(JtsBinaryCodec.java:69)
        at org.locationtech.spatial4j.io.BinaryCodec.readShape(BinaryCodec.java:52)
        at org.janusgraph.core.attribute.JtsGeoshapeHelper.readShape(JtsGeoshapeHelper.java:95)
        at org.janusgraph.core.attribute.Geoshape$GeoshapeBinarySerializer.read(Geoshape.java:625)
        at org.janusgraph.graphdb.tinkerpop.io.binary.GeoshapeGraphBinarySerializer.readNonNullableValue(GeoshapeGraphBinarySerializer.java:48)
        at org.janusgraph.graphdb.tinkerpop.io.binary.GeoshapeGraphBinarySerializer.readNonNullableValue(GeoshapeGraphBinarySerializer.java:26)
        at org.janusgraph.graphdb.tinkerpop.io.binary.JanusGraphTypeSerializer.readValue(JanusGraphTypeSerializer.java:63)
        at org.janusgraph.graphdb.tinkerpop.io.binary.JanusGraphTypeSerializer.read(JanusGraphTypeSerializer.java:52)
        at org.apache.tinkerpop.gremlin.structure.io.binary.GraphBinaryReader.read(GraphBinaryReader.java:106)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.CollectionSerializer.readValue(CollectionSerializer.java:41)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.ListSerializer.readValue(ListSerializer.java:39)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.ListSerializer.readValue(ListSerializer.java:29)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.readValue(SimpleTypeSerializer.java:59)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.read(SimpleTypeSerializer.java:47)
        at org.apache.tinkerpop.gremlin.structure.io.binary.GraphBinaryReader.read(GraphBinaryReader.java:106)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.MapSerializer.readValue(MapSerializer.java:42)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.MapSerializer.readValue(MapSerializer.java:31)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.readValue(SimpleTypeSerializer.java:59)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.read(SimpleTypeSerializer.java:47)
        at org.apache.tinkerpop.gremlin.structure.io.binary.GraphBinaryReader.read(GraphBinaryReader.java:106)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.TraverserSerializer.readValue(TraverserSerializer.java:42)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.TraverserSerializer.readValue(TraverserSerializer.java:33)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.readValue(SimpleTypeSerializer.java:59)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.read(SimpleTypeSerializer.java:47)
        at org.apache.tinkerpop.gremlin.structure.io.binary.GraphBinaryReader.read(GraphBinaryReader.java:106)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.CollectionSerializer.readValue(CollectionSerializer.java:41)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.ListSerializer.readValue(ListSerializer.java:39)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.ListSerializer.readValue(ListSerializer.java:29)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.readValue(SimpleTypeSerializer.java:59)
        at org.apache.tinkerpop.gremlin.structure.io.binary.types.SimpleTypeSerializer.read(SimpleTypeSerializer.java:47)
        at org.apache.tinkerpop.gremlin.structure.io.binary.GraphBinaryReader.read(GraphBinaryReader.java:106)
        at org.apache.tinkerpop.gremlin.driver.ser.binary.ResponseMessageSerializer.readValue(ResponseMessageSerializer.java:56)
        at org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1.deserializeResponse(GraphBinaryMessageSerializerV1.java:180)
        at org.apache.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:47)
        at org.apache.tinkerpop.gremlin.driver.handler.WebSocketGremlinResponseDecoder.decode(WebSocketGremlinResponseDecoder.java:35)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)

```

**Comment by dh-cloud** [comment]
- The root cause of this problem is due to BufferInputStream.class in GeoshapeGraphBinarySerializer.java extends InputStream.class, it Overrides the superclass's read() method, but not Overrides superclass's read(byte b[], int off, int len) method.
```
//BufferInputStream
 @Override
        public int read() {
            return buffer.readInt();
        }

//InputStream
 public int read(byte b[], int off, int len) throws IOException {
        Objects.checkFromIndexSize(off, len, b.length);
        if (len == 0) {
            return 0;
        }

        int c = read();
        if (c == -1) {
            return -1;
        }
        b[off] = (byte)c;

        int i = 1;
        try {
            for (; i < len ; i++) {
                c = read(); //will call BufferInputStream.class's read() method, but the return value is int type, so it maybe -1.
                if (c == -1) { //when c is -1 returned by BufferInputStream.class's read() at last step, will lose the value, so will cause IndexOutOfBoundsException finally
                    break;
                }
                b[off + i] = (byte)c;
            }
        } catch (IOException ee) {
        }
        return i;
    }

//DataInputStream
    public final void readFully(byte b[], int off, int len) throws IOException {
        if (len < 0)
            throw new IndexOutOfBoundsException();
        int n = 0;
        while (n < len) {
            int count = in.read(b, off + n, len - n);
            if (count < 0)
                throw new EOFException();
            n += count;
        }
    }
```

- when `c` in the read(byte b[], int off, int len) method is -1 returned by BufferInputStream.class's read() at last step, will lose the value, so will cause IndexOutOfBoundsException finally.

**Comment by dh-cloud** [comment]
- When a dobule latitude value is 29.7154388159, it will cause a read error by GraphBinaryMessageSerializerV1. For example, -1 is shown in the follow picture.
![image](https://user-images.githubusercontent.com/60729713/186812757-b558a4fe-f389-49e7-bbf1-0c36272b4e8f.png)
