### ISSUE TITLE
Mixed index for properties defined on properties do not work

### ISSUE THREAD

**Issue by wojciechwojcik** [JanusGraph/janusgraph#330]
Configuration:
```
# storage backend
gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=cassandrathrift
storage.hostname=192.168.99.100
schema.default=none

# index backend
index.search.backend=lucene
# path is relative to pwd
index.search.directory=build/searchindex
```

Try this fully functional code attached.
[test-janus.zip](https://github.com/JanusGraph/janusgraph/files/1063588/test-janus.zip)

JanusManagement allows to to define mixed index for a vertex property (no errors):
```
        PropertyKey names = mgmt.makePropertyKey("names").dataType(String.class).cardinality(Cardinality.SINGLE).make();
        PropertyKey origin = mgmt.makePropertyKey("origin").dataType(String.class).cardinality(Cardinality.SINGLE).make();

        mgmt.buildIndex("byNames", Vertex.class).addKey(names, Mapping.TEXT.asParameter()).buildMixedIndex("search");
        mgmt.buildIndex("byOrigin", JanusGraphVertexProperty.class).addKey(origin, Mapping.TEXT.asParameter()).buildMixedIndex("search");
```

But I was not able to find a way to actually make use of it. 
None of the below approaches work:
```
            // no results
            System.out.println("Query mixed index by origin (vp)");
            for (Result<JanusGraphVertexProperty> result : graph.indexQuery("byOrigin", "vp.origin:p*").properties()) {
                JanusGraphVertexProperty prop = result.getElement();
                printVertex(prop.element());
            }

            // NPE
            System.out.println("Query mixed index by origin (p)");
            for (Result<JanusGraphVertexProperty> result : graph.indexQuery("byOrigin", "p.origin:p*").properties()) {
                JanusGraphVertexProperty prop = result.getElement();
                printVertex(prop.element());
            }
```

The result is:
```
[main] INFO org.janusgraph.diskstorage.cassandra.thrift.CassandraThriftStoreManager - Closed Thrift connection pooler.
[main] INFO org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration - Generated unique-instance-id=09a4af3b17384-ADMINIB-6KL0CL41
[main] INFO org.janusgraph.diskstorage.Backend - Configuring index [search]
[main] INFO org.janusgraph.diskstorage.Backend - Initiated backend operations thread pool of size 16
[main] INFO org.janusgraph.diskstorage.log.kcvs.KCVSLog - Loaded unidentified ReadMarker start time 2017-06-09T09:26:21.963Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@7e3f6a2b
Schema is already defined
[main] WARN org.janusgraph.graphdb.transaction.StandardJanusGraphTx - Query requires iterating over all vertices [()]. For better performance, use indexes
Graph already filled
Print all
[main] WARN org.janusgraph.graphdb.transaction.StandardJanusGraphTx - Query requires iterating over all vertices [()]. For better performance, use indexes
Vertex: v[4272]
vp[names->123]
p[empty]
Vertex: v[4096]
vp[names->abc]
p[origin->prod]
Vertex: v[4112]
vp[names->xxx]
p[origin->test]
Query mixed index by name
[main] INFO org.janusgraph.graphdb.database.IndexSerializer - Converted query string with 1 replacements: [v.names:a*] => [names:a*]
Vertex: v[4296]
vp[empty]
p[empty]
Vertex: v[4096]
vp[names->abc]
p[origin->prod]
Query mixed index by vertex origin
[main] INFO org.janusgraph.graphdb.database.IndexSerializer - Converted query string with 1 replacements: [v.origin:p*] => [origin:p*]
Query mixed index by origin (vp)
[main] INFO org.janusgraph.graphdb.database.IndexSerializer - Converted query string with 1 replacements: [vp.origin:p*] => [vorigin:p*]
Query mixed index by origin (p)
[main] INFO org.janusgraph.graphdb.database.IndexSerializer - Converted query string with 1 replacements: [p.origin:p*] => [origin:p*]
[main] INFO org.janusgraph.diskstorage.cassandra.thrift.CassandraThriftStoreManager - Closed Thrift connection pooler.
Exception in thread "main" java.lang.NullPointerException
	at org.janusgraph.graphdb.query.graph.IndexQueryBuilder$1.apply(IndexQueryBuilder.java:204)
	at org.janusgraph.graphdb.query.graph.IndexQueryBuilder$1.apply(IndexQueryBuilder.java:201)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:652)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at JanusTest.main(JanusTest.java:44)
```

The is no documentation to cover this topic at all, yet it seems that:
1) the Janus management seems to accept such index definitions 
2) for graph.indexQuery() there is a method ``properties()`` that returns vertex properties
3) there are some index query replacements taking place if  ``vp`` or `p` prefixes are used

Either this functionality should be fixed and documented or removed.

**Comment by holleyism** [comment]
This appears to be fixed in the current master branch.  The original example posted, runs the query:
```
graph.indexQuery("byNames", "v.origin:p*").vertices()
```
which correctly throws an error "The used key [origin] is not indexed in the targeted index [byNames].  Changing that to the query:
```
graph.indexQuery("byNames", "v.names:p*").vertices()
```
and running the entire test program, produces the following output:
```
13:45:39,795  INFO Backend:466 - Configuring index [search]
13:45:40,118  INFO Backend:183 - Initiated backend operations thread pool of size 16
13:45:40,165  INFO Backend:261 - Configuring total store cache size: 133341908
13:45:40,277  INFO KCVSLog:744 - Loaded unidentified ReadMarker start time 2017-06-14T18:45:40.265Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@d8d666dc
Schema is already defined
13:45:40,405  WARN StandardJanusGraphTx:1284 - Query requires iterating over all vertices [()]. For better performance, use indexes
Graph already filled
Print all
13:45:40,425  WARN StandardJanusGraphTx:1284 - Query requires iterating over all vertices [()]. For better performance, use indexes
Vertex: v[4096]
vp[names->abc]
p[origin->prod]
Vertex: v[4216]
vp[names->123]
p[empty]
Vertex: v[4288]
vp[names->xxx]
p[origin->test]
Query mixed index by name
13:45:40,519  INFO IndexSerializer:672 - Converted query string with 1 replacements: [v.names:a*] => [names:a*]
Vertex: v[4096]
vp[names->abc]
p[origin->prod]
Query mixed index by vertex origin (v)
13:45:40,825  INFO IndexSerializer:672 - Converted query string with 1 replacements: [v.names:p*] => [names:p*]
Query mixed index by origin (vp)
13:45:40,843  INFO IndexSerializer:672 - Converted query string with 1 replacements: [vp.origin:p*] => [vorigin:p*]
Query mixed index by origin (p)
13:45:40,847  INFO IndexSerializer:672 - Converted query string with 1 replacements: [p.origin:p*] => [origin:p*]
Vertex: v[4096]
vp[names->abc]
p[origin->prod]
Done
13:45:40,874  INFO CassandraThriftStoreManager:628 - Closed Thrift connection pooler.
```

**Comment by wojciechwojcik** [comment]
If the NPE is fixed in the master that is great news. 

Still not sure what vp query replacement is for?
```
13:45:40,843  INFO IndexSerializer:672 - Converted query string with 1 replacements: [vp.origin:p*] => [vorigin:p*]
Query mixed index by origin (p)
```

Some docs on the topic would be helpful as well.

**Comment by holleyism** [comment]
vp is not a query replacement.  "v.", "e." and "p." are the prefixes that are replaced but it's possible it can be in the string other than the beginning.
e.g.:
graph.indexQuery("vertexByText", "v.name:v.john").vertices() //DOES NOT WORK!
graph.indexQuery("vertexByText", "$v$name:v.john").setElementIdentifier("$v$").vertices()
In the example:
"vp.origin:p*" remove "p." becomes "vorigin:p*".

**Comment by wojciechwojcik** [comment]
@holleyism thanks for the explanation. 
So I guess this leaves only the doc update.

**Comment by porunov** [comment]
Documentation was updated with the above information which is placed here:
https://docs.janusgraph.org/index-backend/direct-index-query/#element-identifier-collision

I am closing this issue as I think it is resolved now. If you think that some additional information is needed to be added into the documentation, feel free to reopen this issue.
