### ISSUE TITLE
GraphFactory could not instantiate this Graph implementation

### ISSUE THREAD

**Issue by Simkiw** [JanusGraph/janusgraph#3574]
JanusGraph Version: 0.6.2  
TinkerPop Version: 3.5.3  

My container used to be working fine :)  
And for some reason, it crashed. Is it because I did not well configure the proxy, is it because i was trying to run queries while the container was still on setup phase? I don't know, and I don't much about graphs or thinkerpop. I hope the scenario would be enough to understand the issue along with the error  

```
[main] INFO  org.janusgraph.graphdb.server.JanusGraphServer  - JanusGraph Version: 0.6.2
2023-02-10 10:07:11 116  [main] INFO  org.janusgraph.graphdb.server.JanusGraphServer  - TinkerPop Version: 3.5.3
2023-02-10 10:07:11 121  [main] INFO  org.janusgraph.graphdb.server.JanusGraphServer  - Configuring JanusGraph Server from /etc/opt/janusgraph/janusgraph-server.yaml
2023-02-10 10:07:11 368  [main] INFO  org.apache.tinkerpop.gremlin.server.util.MetricManager  - Configured Metrics CsvReporter configured with report interval=180000ms to fileName=/tmp/gremlin-server-metrics.csv
2023-02-10 10:07:11 486  [main] INFO  org.apache.tinkerpop.gremlin.server.util.MetricManager  - Configured Metrics JmxReporter configured with domain= and agentId=
2023-02-10 10:07:11 491  [main] INFO  org.apache.tinkerpop.gremlin.server.util.MetricManager  - Configured Metrics Slf4jReporter configured with interval=180000ms and loggerName=org.apache.tinkerpop.gremlin.server.Settings$Slf4jReporterMetrics
2023-02-10 10:07:13 1910 [main] INFO  org.janusgraph.graphdb.idmanagement.UniqueInstanceIdRetriever  - Generated unique-instance-id=ac1100021-b4d084fe34d11
2023-02-10 10:07:13 1948 [main] INFO  org.janusgraph.diskstorage.Backend  - Configuring index [search]
2023-02-10 10:07:13 2075 [main] INFO  org.janusgraph.diskstorage.configuration.ExecutorServiceBuilder  - Initiated fixed thread pool of size 24
2023-02-10 10:07:13 2125 [main] WARN  org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager  - Graph [graph] configured at [/etc/opt/janusgraph/janusgraph.properties] could not be instantiated and will not be available in Gremlin Server.  GraphFactory message: GraphFactory could not instantiate this Graph implementation [class org.janusgraph.core.JanusGraphFactory]
2023-02-10 10:07:13 java.lang.RuntimeException: GraphFactory could not instantiate this Graph implementation [class org.janusgraph.core.JanusGraphFactory]
2023-02-10 10:07:13     at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:84)
2023-02-10 10:07:13     at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:72)
2023-02-10 10:07:13     at org.apache.tinkerpop.gremlin.structure.util.GraphFactory.open(GraphFactory.java:106)
2023-02-10 10:07:13     at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.addGraph(DefaultGraphManager.java:63)
2023-02-10 10:07:13     at java.util.LinkedHashMap.forEach(LinkedHashMap.java:684)
2023-02-10 10:07:13     at org.apache.tinkerpop.gremlin.server.util.DefaultGraphManager.<init>(DefaultGraphManager.java:58)
2023-02-10 10:07:13     at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
```

**Comment by cdegroc** [comment]
Hello @Simkiw, this seems like a configuration problem. The error message does not contain much information.
Could you maybe share the (redacted) content of `/etc/opt/janusgraph/janusgraph-server.yaml` and `/etc/opt/janusgraph/janusgraph.properties`?

**Comment by Simkiw** [comment]
Sorry @cdegroc , looks like I did miss your comment + I've been away for a long long while 😢 

I just remember it worked again.
I had to rebuild the whole thing.
In the end,
- Either I messed with the configuration and i don't think I was changing anything
- or the proxy interfered with my container based on the setup I already had (no proxy), and it's high-likely to be the culprit

I won't be able to provide more details, not even the logs or anything.
I'm closing the issue.

Happy 2026 (and 25 and 24)
