### ISSUE TITLE
Geoshape properties can't be deserialized in OLAP mode

### ISSUE THREAD

**Issue by twilmes** [JanusGraph/janusgraph#373]
A KryoException is thrown when attempting to deserialize any Geoshape properties in OLAP mode because Geoshape is missing a no-arg constructor.

```
Caused by: org.apache.spark.SparkException: Job aborted due to stage failure: Exception while getting task result: java.io.IOException: org.apache.tinkerpop.shaded.kryo.KryoException: Class cannot be created (missing no-arg constructor): org.janusgraph.core.attribute.Geos
hape
Serialization trace:
value (org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertexProperty)
properties (org.apache.tinkerpop.gremlin.structure.util.detached.DetachedVertex)
t (org.apache.tinkerpop.gremlin.process.traversal.traverser.B_O_Traverser)
        at org.apache.spark.scheduler.DAGScheduler.org$apache$spark$scheduler$DAGScheduler$$failJobAndIndependentStages(DAGScheduler.scala:1431)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1419)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$abortStage$1.apply(DAGScheduler.scala:1418)
        at scala.collection.mutable.ResizableArray$class.foreach(ResizableArray.scala:59)
        at scala.collection.mutable.ArrayBuffer.foreach(ArrayBuffer.scala:47)
        at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:1418)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGScheduler$$anonfun$handleTaskSetFailed$1.apply(DAGScheduler.scala:799)
        at scala.Option.foreach(Option.scala:236)
        at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:799)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:1640)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1599)
        at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:1588)
        at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:48)
        at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:620)
```

**Comment by sjudeng** [comment]
Is this with 0.1.0 or master? If on master try adding the below config.

```
spark.kryo.registrator=org.janusgraph.hadoop.serialize.JanusGraphKryoRegistrator
```

Even if that works please keep this issue open as documentation should be added for this (as it is it's just [here](https://github.com/JanusGraph/janusgraph/blob/513d1f6adad2c3c01050c3205c862a6aae537e6e/docs/hadoop.txt#L86)).

**Comment by twilmes** [comment]
Thanks @sjudeng , I bet that'll fix it. I'll keep this open, add docs, and update our hadoop configs.

**Comment by twilmes** [comment]
I gave that a try and I'm still running into the same issue. `Geoshape` is being registered but for some reason `GeoShapeKryoSerializer` is not being called. I'll keeping digging.

**Comment by sjudeng** [comment]
The Spark KryoRegistrator approach for custom serialization was originally added against TP 3.1.1. In the meantime it looks like there were some significant changes (e.g. [TINKERPOP-1321](https://issues.apache.org/jira/browse/TINKERPOP-1321)). The stack trace shows that TP shaded Kryo machinery is being used, which I guess doesn't recognize custom KryoRegistrator implementations.

I thought geoshape serialization was exercised in the InputFormat integration tests but clearly not. I just submitted a PR that adds a test and switches from Spark KryoRegistrator to TP KryoShimService for custom serialization. Can you take a look? I didn't find any definitive documentation on this and nothing indicating that providers should implement their own KryoShimService.
