### ISSUE TITLE
NoSuchMethodError: org.yaml.snakeyaml.constructor.Constructor.<init> on gremlin console

### ISSUE THREAD

**Issue by li-boxuan** [JanusGraph/janusgraph#3763]
I just found this issue on the master branch (hash 51591357c95b3eebb656c26802582ca8d5d68865) using java8. Not reproducible on 1.0.0-rc2.

```
gremlin> :remote connect tinkerpop.server conf/remote.yaml
21:24:10 INFO  com.jcabi.log.Logger.infoForced - 0 attributes loaded from 328 stream(s) in 96ms, 104 saved, 5165 ignored: []
org.yaml.snakeyaml.constructor.Constructor.<init>(Ljava/lang/Class;)V
Type ':help' or ':h' for help.
Display stack trace? [yN]y
java.lang.NoSuchMethodError: org.yaml.snakeyaml.constructor.Constructor.<init>(Ljava/lang/Class;)V
	at org.apache.tinkerpop.gremlin.driver.Settings.read(Settings.java:114)
	at org.apache.tinkerpop.gremlin.driver.Cluster.build(Cluster.java:172)
	at org.apache.tinkerpop.gremlin.driver.Cluster.open(Cluster.java:265)
	at org.apache.tinkerpop.gremlin.console.jsr223.DriverRemoteAcceptor.connect(DriverRemoteAcceptor.java:91)
	at org.apache.tinkerpop.gremlin.jsr223.console.RemoteAcceptor$connect.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:47)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:115)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:127)
	at org.apache.tinkerpop.gremlin.console.commands.RemoteCommand$_closure1.doCall(RemoteCommand.groovy:55)
```

**Comment by li-boxuan** [comment]
I'll take a look at this in a week or two, if no one else takes it.

**Comment by cdegroc** [comment]
Indeed, JanusGraph and TinkerPop versions of `snakeyaml` conflict:
- JanusGraph's `master` depends on `snakeyaml` `2.0` ([pom.xml](https://github.com/JanusGraph/janusgraph/blob/master/pom.xml#L750)) and TinkerPop `3.6.2` ([pom.xml](https://github.com/JanusGraph/janusgraph/blob/master/pom.xml#L59)).
- TinkerPop `3.6.2`. depends on `snakeyaml` `1.32` ([pom.xml](https://github.com/apache/tinkerpop/blob/3.6.2/pom.xml#L182)).

`snakeyaml` `1.32` and `2.0` are incompatible because the `Constructor` class now has a mandatory second argument ([ex](https://github.com/JanusGraph/janusgraph/pull/3628/files#diff-6a363c9347ed282f368be87744b81206e26e4db827e63aca98e0facc56a0b48eL37)).

A solution could be to upgrade to TinkerPop 3.6.3 which depends on `snakeyaml` **2.0** ([pom.xml](https://github.com/apache/tinkerpop/blob/3.6.3/pom.xml#L179)).

**Comment by li-boxuan** [comment]
@cdegroc Thanks for helping out! I was wondering why TinkerPop was already using `2.0` but we cannot upgrade to `2.0`. Not it makes sense. I'll fix current issue by downgrading `snakeyaml` (since this problem also occurs on 0.6 branch), and then someone could upgrade to newer TinkerPop version.
