### ISSUE TITLE
JanusGraph Embedded: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager

### ISSUE THREAD

**Issue by chenweisomebody126** [JanusGraph/janusgraph#4003]
Please include configurations and logs if available.

For confirmed bugs, please report:

- Version: 0.6.3 
- Storage Backend: cql
- JDK:azul-1.8
- Mixed Index Backend: none
- Expected Behavior: able to connect to Cassandra container
- Current Behavior: fail to connect Cassandra container
- Steps to Reproduce:

Apple M1 chip laptop
```
$ docker pull cassandra:3.11.9
$ docker run --name jg-cassandra -d -e CASSANDRA_START_RPC=true -p 9160:9160 \  -p 9042:9042 -p 7199:7199 -p 7001:7001 -p 7000:7000 cassandra:3.11.9
```
I also checked the ip of the Cassandra container 
```
docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' jg-cassandra
172.17.0.3
```
I also checked the Cassandra:
```
 % docker exec -it jg-cassandra cqlsh
Connected to Test Cluster at 127.0.0.1:9042.
[cqlsh 5.0.1 | Cassandra 3.11.9 | CQL spec 3.4.4 | Native protocol v4]
Use HELP for help.
cqlsh> DESCRIBE KEYSPACES;

system_traces  system_schema  system_auth  system  system_distributed
```
And then I created a HelloWorld project
```
package org.example;

import org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversalSource;
import org.janusgraph.core.JanusGraph;
import org.janusgraph.core.JanusGraphFactory;
import org.janusgraph.example.GraphOfTheGodsFactory;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class Main {
    private static final Logger LOGGER = LoggerFactory.getLogger(Main.class);

    public static void main(String[] args) {
        JanusGraph graph = JanusGraphFactory.build().
                set("storage.backend", "cql").
                set("storage.hostname", "172.17.0.3").
                open();
        GraphTraversalSource g = graph.traversal();
        if (g.V().count().next() == 0) {
            // load the schema and graph data
            GraphOfTheGodsFactory.load(graph);
        }
        System.exit(0);
    }
}
```
And my pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>org.example</groupId>
    <artifactId>HelloWorld</artifactId>
    <version>1.0-SNAPSHOT</version>
    <dependencies>
        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-core</artifactId>
            <version>0.6.3</version>
        </dependency>

        <!-- These are all runtime dependencies -->
        <dependency>
            <groupId>org.janusgraph</groupId>
            <artifactId>janusgraph-cql</artifactId>
            <version>0.6.3</version>
            <scope>runtime</scope>
        </dependency>
    </dependencies>

    <properties>
        <maven.compiler.source>8</maven.compiler.source>
        <maven.compiler.target>8</maven.compiler.target>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>

</project>
```

### Stack Trace (if you have one)

```
14:56:17.522 [main] DEBUG com.datastax.oss.driver.internal.core.util.Reflection - Could not load com.esri.core.geometry.ogc.OGCGeometry with loader null: java.lang.ClassNotFoundException: com.esri.core.geometry.ogc.OGCGeometry
java.lang.ClassNotFoundException: com.esri.core.geometry.ogc.OGCGeometry
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:264)
	at com.datastax.oss.driver.internal.core.util.Reflection.loadClass(Reflection.java:57)
	at com.datastax.oss.driver.internal.core.util.DefaultDependencyChecker.lambda$isPresent$0(DefaultDependencyChecker.java:48)
	at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1660)
	at com.datastax.oss.driver.internal.core.util.DefaultDependencyChecker.isPresent(DefaultDependencyChecker.java:41)
	at com.datastax.dse.driver.internal.core.type.codec.DseTypeCodecsRegistrar.registerDseCodecs(DseTypeCodecsRegistrar.java:32)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildCodecRegistry(DefaultDriverContext.java:523)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.<init>(DefaultDriverContext.java:260)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildContext(SessionBuilder.java:968)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildDefaultSessionAsync(SessionBuilder.java:904)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildAsync(SessionBuilder.java:817)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:835)
	at org.janusgraph.diskstorage.cql.builder.CQLSessionBuilder.build(CQLSessionBuilder.java:81)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.<init>(CQLStoreManager.java:135)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.<init>(CQLStoreManager.java:116)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:73)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:527)
	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:491)
	at org.janusgraph.graphdb.configuration.builder.GraphDatabaseConfigurationBuilder.build(GraphDatabaseConfigurationBuilder.java:64)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:176)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:147)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:137)
	at org.janusgraph.core.JanusGraphFactory$Builder.open(JanusGraphFactory.java:277)
	at org.example.Main.main(Main.java:40)
14:56:17.523 [main] DEBUG com.datastax.dse.driver.internal.core.type.codec.DseTypeCodecsRegistrar - ESRI was not found on the classpath: geo codecs will not be available
14:56:17.527 [main] INFO com.datastax.oss.driver.internal.core.DefaultMavenCoordinates - DataStax Java driver for Apache Cassandra(R) (com.datastax.oss:java-driver-core) version 4.15.0
14:56:17.528 [main] DEBUG com.datastax.oss.driver.internal.core.session.DefaultSession - Creating new session JanusGraph Session (1 live instances)
14:56:17.533 [main] DEBUG io.netty.util.internal.logging.InternalLoggerFactory - Using SLF4J as the default logging framework
14:56:17.534 [main] DEBUG io.netty.channel.MultithreadEventLoopGroup - -Dio.netty.eventLoopThreads: 20
14:56:17.540 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noUnsafe: false
14:56:17.541 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Buffer.address: available
14:56:17.541 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.theUnsafe: available
14:56:17.541 [main] DEBUG io.netty.util.internal.PlatformDependent0 - sun.misc.Unsafe.copyMemory: available
14:56:17.542 [main] DEBUG io.netty.util.internal.PlatformDependent0 - direct buffer constructor: available
14:56:17.542 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.Bits.unaligned: available, true
14:56:17.542 [main] DEBUG io.netty.util.internal.PlatformDependent0 - java.nio.DirectByteBuffer.<init>(long, int): available
14:56:17.542 [main] DEBUG io.netty.util.internal.Cleaner0 - java.nio.ByteBuffer.cleaner(): available
14:56:17.543 [main] DEBUG io.netty.util.internal.PlatformDependent - Java version: 8
14:56:17.543 [main] DEBUG io.netty.util.internal.PlatformDependent - sun.misc.Unsafe: available
14:56:17.543 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noJavassist: false
14:56:17.580 [main] DEBUG io.netty.util.internal.PlatformDependent - Javassist: available
14:56:17.580 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.tmpdir: /var/folders/30/nkqftcmd2mx_j23gmzjv7hlw0000gn/T (java.io.tmpdir)
14:56:17.580 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.bitMode: 64 (sun.arch.data.model)
14:56:17.580 [main] DEBUG io.netty.util.internal.PlatformDependent - -Dio.netty.noPreferDirect: false
14:56:17.580 [main] DEBUG io.netty.util.internal.PlatformDependent - io.netty.maxDirectMemory: 7635730432 bytes
14:56:17.591 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.noKeySetOptimization: false
14:56:17.591 [main] DEBUG io.netty.channel.nio.NioEventLoop - -Dio.netty.selectorAutoRebuildThreshold: 512
14:56:17.592 [main] DEBUG io.netty.util.internal.PlatformDependent - org.jctools-core.MpscChunkedArrayQueue: available
Exception in thread "main" java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:79)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:527)
	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:491)
	at org.janusgraph.graphdb.configuration.builder.GraphDatabaseConfigurationBuilder.build(GraphDatabaseConfigurationBuilder.java:64)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:176)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:147)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:137)
	at org.janusgraph.core.JanusGraphFactory$Builder.open(JanusGraphFactory.java:277)
	at org.example.Main.main(Main.java:40)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:73)
	... 8 more
Caused by: java.lang.NoClassDefFoundError: io/netty/channel/DefaultEventLoopGroup
	at com.datastax.oss.driver.internal.core.context.DefaultNettyOptions.<init>(DefaultNettyOptions.java:92)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.buildNettyOptions(DefaultDriverContext.java:472)
	at com.datastax.oss.driver.internal.core.util.concurrent.LazyReference.get(LazyReference.java:55)
	at com.datastax.oss.driver.internal.core.context.DefaultDriverContext.getNettyOptions(DefaultDriverContext.java:851)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.<init>(DefaultSession.java:116)
	at com.datastax.oss.driver.internal.core.session.DefaultSession.init(DefaultSession.java:88)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildDefaultSessionAsync(SessionBuilder.java:903)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.buildAsync(SessionBuilder.java:817)
	at com.datastax.oss.driver.api.core.session.SessionBuilder.build(SessionBuilder.java:835)
	at org.janusgraph.diskstorage.cql.builder.CQLSessionBuilder.build(CQLSessionBuilder.java:81)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.<init>(CQLStoreManager.java:135)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.<init>(CQLStoreManager.java:116)
	... 13 more
Caused by: java.lang.ClassNotFoundException: io.netty.channel.DefaultEventLoopGroup
	at java.net.URLClassLoader.findClass(URLClassLoader.java:387)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:419)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:352)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:352)
	... 25 more

Process finished with exit code 1

```

**Comment by chenweisomebody126** [comment]
I also tried `127.0.0.1:9042`, but still failed

**Comment by li-boxuan** [comment]
It looks like a dependency introduced by your project has a conflict with the same package introduced by JanusGraph

**Comment by li-boxuan** [comment]
FYI here's a working maven project with embedded JanusGraph: https://github.com/Citegraph/citegraph/blob/main/backend/pom.xml

**Comment by chenweisomebody126** [comment]
> It looks like a dependency introduced by your project has a conflict with the same package introduced by JanusGraph

This one https://stackoverflow.com/questions/76148239/connect-to-external-janusgraph-server-with-janusgraphfactory helps me.  Once I added `log4j2.xml` to resources folder, everything works.
But thanks for sharing the working maven project with embedded JanusGraph
