### ISSUE TITLE
Error while commiting index mutations for removing properties that are indexed

### ISSUE THREAD

**Issue by scottrpatterson** [JanusGraph/janusgraph#408]
I am running es embedded in the same jvm as JanusGraph 0.1.1. 
```
index.fts.backend=elasticsearch
index.fts.directory= /test/es
index.fts.elasticsearch.client-only=false
index.fts.elasticsearch.local-mode= true
index.fts.elasticsearch.interface=NODE
```

While performing a commit for a bunch of mutations, one of my changes to remove a property throws a exception complaining about a variable name in es. 

> Script1.groovy: 1: The current scope already contains a variable of the name index

Since the script that is executed in elasticsearch is generated by janusgraph, where is the suspect variable name "index" coming from? If there are multiple properties().drop() in the same commit, will that variable "index" be reused in the same es script?

The traversal is:
```
g.traversal().V().has("propA", "valueA").hasLabel("art")
                        .has("propB", "valueB"
                        .properties("propB").drop().iterate()
```

The backend exception:
```
[0]: index [janusgraph], type [FTSccde89523844234e61420a730ba96894], id [2wejoi8], message [ElasticsearchIllegalArgumentException[failed to execute script]; nested: GroovyScriptCompilationException[MultipleCompilationErrorsException[startup failed:
Script1.groovy: 1: The current scope already contains a variable of the name index
 @ line 1, column 156.
   propB"].remove(index);def index = ct
                                 ^

1 error
]]; ]
    at org.janusgraph.diskstorage.es.ElasticSearchIndex.mutate(ElasticSearchIndex.java:628)
    at org.janusgraph.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:137)
    at org.janusgraph.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:134)
    at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:69)
    at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:55)
    at org.janusgraph.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:134)
    at org.janusgraph.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:115)
    at org.janusgraph.diskstorage.BackendTransaction.commitIndexes(BackendTransaction.java:140)
    at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:743)
    at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1363)
    at org.janusgraph.graphdb.tinkerpop.JanusGraphBlueprintsGraph$GraphTransaction.doCommit(JanusGraphBlueprintsGraph.java:272)
    at org.apache.tinkerpop.gremlin.structure.util.AbstractTransaction.commit(AbstractTransaction.java:105)
```

**Comment by sharpau** [comment]
I don't know the answer to your question but the ES backend was completely rewritten for the 0.2.0 release, so it may be worth taking a snapshot build off of master and seeing if the problem still exists or not.
