### ISSUE TITLE
Edges traversal streaming - enclosing transaction is closed error.

### ISSUE THREAD

**Issue by xdev-developer** [JanusGraph/janusgraph#422]
Hello.

I've REST API service for graph interaction.
For retrieving graph object I use traversal.toStream API.

On some load(other requests processing (create/get objects)), edges stream failed with error:
```Operation cannot be executed because the enclosing transaction is closed
java.lang.IllegalStateException: Operation cannot be executed because the enclosing transaction is closed
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.verifyOpen(StandardJanusGraphTx.java:299)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.getVertex(StandardJanusGraphTx.java:383)
	at org.janusgraph.graphdb.relations.RelationIdentifier.findRelation(RelationIdentifier.java:155)
	at org.janusgraph.graphdb.relations.RelationIdentifier.findEdge(RelationIdentifier.java:186)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$8.apply(StandardJanusGraphTx.java:1327)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$8.apply(StandardJanusGraphTx.java:1322)
	at com.google.common.collect.Iterators$8.transform(Iterators.java:817)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:48)
	at org.janusgraph.graphdb.query.LimitAdjustingIterator.next(LimitAdjustingIterator.java:94)
	at org.janusgraph.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:55)
	at org.janusgraph.graphdb.query.ResultSetIterator.next(ResultSetIterator.java:67)
	at org.janusgraph.graphdb.query.ResultSetIterator.next(ResultSetIterator.java:28)
	at com.google.common.collect.Iterators$7.computeNext(Iterators.java:674)
	at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
	at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:131)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:50)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:37)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.DedupGlobalStep.processNextStart(DedupGlobalStep.java:105)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:192)
	at java.util.Spliterators$IteratorSpliterator.tryAdvance(Spliterators.java:1811)
	at java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
```

Vertex streaming working fine.

setup:
JanusGraph 0.1.1
storage backend - cassandra.
tinkerpop (3.2.3/3.2.5)

**Comment by xdev-developer** [comment]
Update:
Error only occurred when iterator of traversal is used (every step computed).

I understand this is multit-threaded issue - other request closes my transaction, but
why I'ts not happening with vertices traversals and why new transaction isn't opened.

**Comment by xdev-developer** [comment]
Seems like in multit-threaded env (web service) thread can read inconsistent state of StandardJanusGraphTx isOpen property and fail with java.lang.IllegalStateException: Operation cannot be executed because the enclosing transaction is closed.

Changing ```private boolean isOpen;``` to ```private volatile boolean isOpen;``` fixes all my concurrency problems and I can normally query > 2M edges using streaming api.

Is this change acceptable? should I send PR?

**Comment by dianadujing** [comment]
Just for those who have similar issue like this: In my condition, I have used wrong properties file, which has no index backend that caused the same issue.
