### ISSUE TITLE
JanusGraph read only transaction does not throw any exception on write

### ISSUE THREAD

**Issue by wojciechwojcik** [JanusGraph/janusgraph#427]
[JanusTransactionTest.zip](https://github.com/JanusGraph/janusgraph/files/1173837/JanusTransactionTest.zip)

The following code (see attachment)
````
            System.out.println("Base transaction");
            
            TransactionBuilder builder = graph.buildTransaction();
            JanusGraphTransaction transaction = builder.readOnly().start();
            //JanusGraphTransaction transaction = builder.start();
            GraphTraversalSource g = transaction.traversal();
            
            System.out.println(g.V().count().next());
            g.V().drop().tryNext();
            System.out.println(g.V().count().next());
            transaction.commit();

            System.out.println("Other transaction");
            
            transaction = graph.newTransaction();
            System.out.println(transaction.traversal().V().count().next());
            transaction.tx().close();

            System.out.println("Done");
````

simply prints:
````
Base transaction
[main] WARN org.janusgraph.graphdb.transaction.StandardJanusGraphTx - Query requires iterating over all vertices [()]. For better performance, use indexes
3
[main] WARN org.janusgraph.graphdb.transaction.StandardJanusGraphTx - Query requires iterating over all vertices [()]. For better performance, use indexes
[main] WARN org.janusgraph.graphdb.transaction.StandardJanusGraphTx - Query requires iterating over all vertices [()]. For better performance, use indexes
0
Other transaction
[main] WARN org.janusgraph.graphdb.transaction.StandardJanusGraphTx - Query requires iterating over all vertices [()]. For better performance, use indexes
3
Done
[main] INFO org.janusgraph.diskstorage.cassandra.thrift.CassandraThriftStoreManager - Closed Thrift connection pooler.
````

which correctly prevents the ``drop()`` statement from modifications, still NO exception, log or any indication of error is presented to the user.

If you look at the javadoc of ``TransactionBuilder::readOnly()`` it clearly states:
_Makes the transaction read only. **Any writes will cause an exception**.._

This is further misleading as ``drop()`` effects are still immediately visible in its own transaction context, which means that e.g. trying to access a vertex property you will get such error:
````
java.lang.IllegalStateException: Vertex with id 4224 was removed.
	at org.apache.tinkerpop.gremlin.structure.Element$Exceptions.elementAlreadyRemoved(Element.java:154) ~[gremlin-core-3.2.5.jar:3.2.5]
	at org.janusgraph.core.InvalidElementException.removedException(InvalidElementException.java:58) ~[janusgraph-core-0.2.0-SNAPSHOT.jar:?]
	at org.janusgraph.graphdb.vertices.AbstractVertex.verifyAccess(AbstractVertex.java:86) ~[janusgraph-core-0.2.0-SNAPSHOT.jar:?]
	at org.janusgraph.graphdb.vertices.AbstractVertex.query(AbstractVertex.java:133) ~[janusgraph-core-0.2.0-SNAPSHOT.jar:?]
	at org.janusgraph.graphdb.vertices.AbstractVertex.properties(AbstractVertex.java:173) ~[janusgraph-core-0.2.0-SNAPSHOT.jar:?]
	at org.apache.tinkerpop.gremlin.structure.Vertex.property(Vertex.java:70) ~[gremlin-core-3.2.5.jar:3.2.5]
````
stating that a vertex was already removed inside a read only transaction (!), which is NOT true.

**Comment by pluradj** [comment]
I downloaded and tried out your code. I'm getting an exception on `g.V().drop().tryNext()` as expected:

```
11:41:32,633  INFO GraphDatabaseConfiguration:1391 - Set default timestamp provider MICRO
11:41:32,642  INFO CassandraThriftStoreManager:628 - Closed Thrift connection pooler.
11:41:32,656  INFO GraphDatabaseConfiguration:1563 - Generated unique-instance-id=091b61cb10300-pluradj
11:41:32,683  INFO Backend:178 - Initiated backend operations thread pool of size 16
11:41:33,356  INFO KCVSLog:744 - Loaded unidentified ReadMarker start time 2017-07-25T15:41:33.341Z into org.janusgraph.diskstorage.log.kcvs.KCVSLog$MessagePuller@42c235c9
11:41:34,679  WARN StandardJanusGraphTx:1273 - Query requires iterating over all vertices [()]. For better performance, use indexes
Filling data
Base transaction
11:41:36,775  WARN StandardJanusGraphTx:1273 - Query requires iterating over all vertices [()]. For better performance, use indexes
3
11:41:36,784  WARN StandardJanusGraphTx:1273 - Query requires iterating over all vertices [()]. For better performance, use indexes
11:41:36,801  INFO CassandraThriftStoreManager:628 - Closed Thrift connection pooler.
[WARNING] 
java.lang.UnsupportedOperationException: Cannot create new entities in read-only transaction
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.verifyWriteAccess(StandardJanusGraphTx.java:278)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.removeRelation(StandardJanusGraphTx.java:605)
	at org.janusgraph.graphdb.relations.CacheVertexProperty.remove(CacheVertexProperty.java:137)
	at org.janusgraph.graphdb.transaction.RelationConstructor$1$1.remove(RelationConstructor.java:67)
	at org.janusgraph.graphdb.vertices.AbstractVertex.remove(AbstractVertex.java:102)
	at org.janusgraph.graphdb.vertices.StandardVertex.remove(StandardVertex.java:101)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.DropStep.filter(DropStep.java:65)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:143)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:179)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.tryNext(Traversal.java:86)
	at com.ibm.janusgraph.test.JanusTransactionTest.main(JanusTransactionTest.java:30)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:282)
	at java.lang.Thread.run(Thread.java:748)
```

Anything else notable about your environment?

**Comment by pluradj** [comment]
The exception is also reproducible from the Gremlin Console:

```
gremlin> graph = JanusGraphFactory.open('conf/janusgraph-cassandra.properties')
==>standardjanusgraph[cassandrathrift:[127.0.0.1]]
gremlin> GraphOfTheGodsFactory.load(graph, null, false)
==>null
gremlin> tx = graph.buildTransaction().readOnly().start()
==>standardjanusgraphtx[0x7ec08115]
gremlin> g = tx.traversal()
==>graphtraversalsource[standardjanusgraphtx[0x7ec08115], standard]
gremlin> g.V().drop().iterate()
11:48:17 WARN  org.janusgraph.graphdb.transaction.StandardJanusGraphTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
Cannot create new entities in read-only transaction
Type ':help' or ':h' for help.
Display stack trace? [yN]y
java.lang.UnsupportedOperationException: Cannot create new entities in read-only transaction
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.verifyWriteAccess(StandardJanusGraphTx.java:278)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.removeRelation(StandardJanusGraphTx.java:605)
	at org.janusgraph.graphdb.relations.CacheVertexProperty.remove(CacheVertexProperty.java:137)
	at org.janusgraph.graphdb.transaction.RelationConstructor$1$1.remove(RelationConstructor.java:67)
	at org.janusgraph.graphdb.vertices.AbstractVertex.remove(AbstractVertex.java:102)
	at org.janusgraph.graphdb.vertices.StandardVertex.remove(StandardVertex.java:101)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.DropStep.filter(DropStep.java:65)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.FilterStep.processNextStart(FilterStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
	at org.apache.tinkerpop.gremlin.process.traversal.Traversal.iterate(Traversal.java:175)
	at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal.iterate(GraphTraversal.java:1505)
	at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal$Admin.iterate(GraphTraversal.java:175)
	at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.DefaultGraphTraversal.iterate(DefaultGraphTraversal.java:48)
	at org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal$Admin$iterate.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at groovysh_evaluate.run(groovysh_evaluate:3)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at org.codehaus.groovy.tools.shell.Interpreter.evaluate(Interpreter.groovy:70)
	at org.codehaus.groovy.tools.shell.Groovysh.execute(Groovysh.groovy:190)
	at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.super$3$execute(GremlinGroovysh.groovy)
	at sun.reflect.GeneratedMethodAccessor14.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132)
	at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.execute(GremlinGroovysh.groovy:72)
	at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:122)
	at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:95)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:152)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:124)
	at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:59)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1215)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:132)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:152)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:83)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:152)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
	at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:455)
```

**Comment by wojciechwojcik** [comment]
I am using latest janusgraph-0.2.0-SNAPSHOT jar available from sonatype Mon Jul 17 19:55:11 UTC 2017.

My storage properties:
````
# storage backend
gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=cassandrathrift
storage.hostname=192.168.99.100
schema.default=none
storage.cassandra.keyspace=janustest
````

Perhaps this is only related to certain ``storage.backend``.

**Comment by pluradj** [comment]
Thanks. I was running against `0.1.1`. I've confirmed the behavior with your program using the latest code from `master` branch, so it seems like a regression.

Backend storage db doesn't matter. The error can be reproduced with `inmemory` with Gremlin Console.

```
graph = JanusGraphFactory.open('inmemory')
graph.addVertex()
graph.tx().commit()
graph.traversal().V().count().next() // result is 1
tx = graph.buildTransaction().readOnly().start()
g = tx.traversal()
g.V().drop().iterate() // should throw exception
g.V().count().next() // result is 0
tx.commit()
graph.traversal().V().count().next() // result is still 1
```

**Comment by pluradj** [comment]
@sjudeng seems like this is releated https://github.com/JanusGraph/janusgraph/blame/master/janusgraph-core/src/main/java/org/janusgraph/graphdb/relations/CacheVertexProperty.java#L136

**Comment by sjudeng** [comment]
@pluradj Yeah throwing an exception here fails a couple TinkerPop tests (`GraphComputerTest#shouldSucceedWithProperTraverserRequirements/shouldFailWithImproperTraverserRequirements`). Alternatives would be to opt-out of those tests or look into handling it at a higher level in FulgoraGraphComputer if possible.
