### ISSUE TITLE
OrderedKeyValueStoreAdapter array out of bounds exception

### ISSUE THREAD

**Issue by Eric-Chng** [JanusGraph/janusgraph#4401]
If you extract a OrderedKeyColumnValueStoreManager from a backend that is a KV store but uses OrderedKeyValueStoreAdapter to implement KCV storage. Then store two key,column,value tuples, one of which has a key which is a substring of the other starting from index 0. For instance, (hello, col, world) and (hel,col,wor). Attempting to getSlice to access the (hel,col,wor) pair will give an array index out of bounds exception. This is because the OrderedKeyValueStoreAdapter class does not check length when it compares keys.
This problem applies for any variable length KCV store usage that is applied against a KV backend. 

For confirmed bugs, please report:

- Version: 1.0.0
- Storage Backend: berkeley-db
- Mixed Index Backend: none
- Link to discussed bug: 
- Expected Behavior: Retrieve slice with no errors
- Current Behavior: ArrayIndexOutOfBoundsException
- Steps to Reproduce:
1. Cast your backend storage manager to KeyColumnValueStoreManager
2. Use storage manager to open a database
3. Store keys mentioned above (hello, col, world), (hel,col,wor)
4. Retrieve (hel,col,wor)

### Stack Trace

```
java.lang.ArrayIndexOutOfBoundsException: Required size [1] exceeds actual remaining size [0]

	at org.janusgraph.diskstorage.util.StaticArrayBuffer.require(StaticArrayBuffer.java:94)
	at org.janusgraph.diskstorage.util.StaticArrayBuffer.getByte(StaticArrayBuffer.java:170)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter.equalKey(OrderedKeyValueStoreAdapter.java:290)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter.lambda$convertQuery$1(OrderedKeyValueStoreAdapter.java:234)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.KeySelector.include(KeySelector.java:47)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore$1.getNextEntry(BerkeleyJEKeyValueStore.java:199)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyJEKeyValueStore$1.hasNext(BerkeleyJEKeyValueStore.java:164)
	at org.janusgraph.diskstorage.util.StaticArrayEntryList.applyElementsComputation(StaticArrayEntryList.java:540)
	at org.janusgraph.diskstorage.util.StaticArrayEntryList.of(StaticArrayEntryList.java:406)
	at org.janusgraph.diskstorage.util.StaticArrayEntryList.ofStaticBuffer(StaticArrayEntryList.java:358)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter.convert(OrderedKeyValueStoreAdapter.java:169)
	at org.janusgraph.diskstorage.keycolumnvalue.keyvalue.OrderedKeyValueStoreAdapter.getSlice(OrderedKeyValueStoreAdapter.java:88)
	at org.janusgraph.diskstorage.berkeleyje.BerkeleyVariableLengthKCVSTest.retrieveBackendAndGetKeyValue(BerkeleyVariableLengthKCVSTest.java:109)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
```

**Comment by porunov** [comment]
Fixed in #4402
