### ISSUE TITLE
CQL Backend Fails to Init

### ISSUE THREAD

**Issue by natevecc** [JanusGraph/janusgraph#468]
When I was trying to get a scala application working with only the following jars:
```
"org.janusgraph" % "janusgraph-core" % "0.2.0-SNAPSHOT",
"org.janusgraph" % "janusgraph-cql" % "0.2.0-SNAPSHOT",
"org.janusgraph" % "janusgraph-es" % "0.2.0-SNAPSHOT",
```
I got the following error:
```
[info]   java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager
[info]   at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:69)
[info]   at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:477)
[info]   at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:409)
[info]   at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1353)
[info]   at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:107)
[info]   at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:75)
[info]   at SimpleSpec.$anonfun$new$1(SimpleSpec.scala:13)
[info]   at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   ...
[info]   Cause: java.lang.reflect.InvocationTargetException:
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
[info]   at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
[info]   at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:477)
[info]   at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:409)
[info]   at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1353)
[info]   at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:107)
[info]   at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:75)
[info]   ...
[info]   Cause: java.lang.NoClassDefFoundError: io/netty/util/Timer
[info]   at com.datastax.driver.core.Configuration$Builder.build(Configuration.java:317)
[info]   at com.datastax.driver.core.Cluster$Builder.getConfiguration(Cluster.java:1282)
[info]   at com.datastax.driver.core.Cluster.<init>(Cluster.java:113)
[info]   at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:178)
[info]   at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:1299)
[info]   at org.janusgraph.diskstorage.cql.CQLStoreManager.initializeCluster(CQLStoreManager.java:248)
[info]   at org.janusgraph.diskstorage.cql.CQLStoreManager.<init>(CQLStoreManager.java:145)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
[info]   at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
[info]   at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
[info]   ...
[info]   Cause: java.lang.ClassNotFoundException: io.netty.util.Timer
[info]   at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[info]   at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[info]   at com.datastax.driver.core.Configuration$Builder.build(Configuration.java:317)
[info]   at com.datastax.driver.core.Cluster$Builder.getConfiguration(Cluster.java:1282)
[info]   at com.datastax.driver.core.Cluster.<init>(Cluster.java:113)
[info]   at com.datastax.driver.core.Cluster.buildFrom(Cluster.java:178)
[info]   at com.datastax.driver.core.Cluster$Builder.build(Cluster.java:1299)
[info]   at org.janusgraph.diskstorage.cql.CQLStoreManager.initializeCluster(CQLStoreManager.java:248)
[info]   at org.janusgraph.diskstorage.cql.CQLStoreManager.<init>(CQLStoreManager.java:145)
[info]   ...
```

Once I added the `"io.netty" % "netty-all" % "4.1.14.Final"` dependency the code ran fine. Not sure if this is a bug since I'm pulling the jars in piecemeal but saw that the cassandra-driver is excluding netty and probably the cause of my problem:
```xml
<dependency>
  <groupId>com.datastax.cassandra</groupId>
  <artifactId>cassandra-driver-core</artifactId>
  <version>${cassandra-driver.version}</version>
  <exclusions>
    <!-- conflicts with netty-all from org.apache.hbase:hbase-client -->
    <exclusion>
      <groupId>io.netty</groupId>
      <artifactId>netty-handler</artifactId>
    </exclusion>
    </exclusions>
</dependency>
```

If someone points me in the right direction on how to fix this I'd gladly open a PR but my maven foo is weak.

**Comment by bishnuagrawal-zeotap** [comment]
The issue comes sometime in the middle of running job
