### ISSUE TITLE
could not re-open management log exception while running groovy script

### ISSUE THREAD

**Issue by amyth** [JanusGraph/janusgraph#497]
Hi,

I had a Janusgraph/Cassandra (forked) implementation on my dev server. I had written a population script to populate the data that reads data from a JSON file and creates the required vertices, edges, and properties. Due to some implementation changes, I wanted to update the script to read a CSV file instead. In order to test this, I wanted to keep a backup of the current implementation so I simply made a copy of `janusgraph-0.1.0-hadoop2` folder and tried to run the script. And since then I am getting the following exception.

```
could not re-open management log
```

I have tried the following:

 - ./bin/janusgraph.sh restart (stop/start)
 - ./bin/janusgraph.sh clean
 - Delete whole project and re-create it
 - Download version 0.1.1 and try running the script with it.

But nothing works, every time I run the script I get the aforementioned error.

I tried to debug the script and found that the following statement is raising the error:

```
this.management.awaitGraphIndexStatus(this.graph, 'uniqueUid').call()
```

When I try running this in the gremlin-shell everything works fine. The problem arises when I try to execute the script as follows:

```
./bin/gremlin.sh -e /path/to/script
```

Here is the [link to the script](https://github.com/amyth/xonnect/blob/master/utils/population_scripts/populateJanus.groovy) that I am trying, just in case if it's required for debugging purposes.

**questions**

A few questions that I am looking an answer to are:

 - Where does the management log reside?
 - If it's the `log/gremlin-server.log` why am I facing this issue even after deleting everything and starting from scratch?

Any help will be much appreciated. Thanks.

**Comment by pluradj** [comment]
Please post the full stack trace.

**Comment by amyth** [comment]
Hey Jason (@pluradj), The output of the script does not print the full stack trace even with verbose option `-v` while executing the script. Here is the output that I get.

```
cd ~/Downloads/janusgraph-0.1.0-hadoop2
./bin/gremlin.sh -e ~/Documents/scripts/xonnect/utils/population_scripts/populateJanus.groovy -v

objc[2039]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/bin/java (0x10a54b4c0) and /Library/Java/JavaVirtualMachines/jdk1.8.0_131.jdk/Contents/Home/jre/lib/libinstrument.dylib (0x10bdbc4e0). One of the two will be used. Which one is undefined.
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/Users/admin/Desktop/janusgraph-0.1.1-hadoop2/lib/slf4j-log4j12-1.7.12.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/Users/admin/Desktop/janusgraph-0.1.1-hadoop2/lib/logback-classic-1.1.2.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
Preparing schema.
javax.script.ScriptException: org.janusgraph.core.JanusGraphException: Could not re-open management log
```

Here is the screenshot for the same.
![Screenshot](https://s26.postimg.org/55reuk8rt/Screenshot_2017-09-06_10.20.51.png)

Also, I did not find anything related to this in the log files. When I try running the same commands within the Gremlin console everything works fine.

**Comment by pluradj** [comment]
You need to add a try/catch block

```
try {
    this.management.awaitGraphIndexStatus(this.graph, 'uniqueUid').call()
} catch (Exception e) {
    e.printStackTrace()
}
```

**Comment by amyth** [comment]
Here is the stack trace that I get after adding a try/catch statement. Though, this does not seem like the same error message.

```
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:57)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:159)
	at org.janusgraph.diskstorage.log.kcvs.KCVSLog.readSetting(KCVSLog.java:818)
	at org.janusgraph.diskstorage.log.kcvs.KCVSLog.<init>(KCVSLog.java:270)
	at org.janusgraph.diskstorage.log.kcvs.KCVSLogManager.openLog(KCVSLogManager.java:225)
	at org.janusgraph.diskstorage.Backend.getSystemMgmtLog(Backend.java:332)
	at org.janusgraph.graphdb.database.StandardJanusGraph.openManagement(StandardJanusGraph.java:303)
	at org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher.call(GraphIndexStatusWatcher.java:64)
	at org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher.call(GraphIndexStatusWatcher.java:32)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at JanusGraphBuilder.createSchema(Script1.groovy:133)
	at JanusGraphBuilder.populate(Script1.groovy:148)
	at JanusGraphBuilder.main(Script1.groovy:33)
	at JanusGraphBuilder$main.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at Script1.run(Script1.groovy:250)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:619)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:448)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:421)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:212)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.ScriptExecutor.evaluate(ScriptExecutor.java:55)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.ScriptExecutor.main(ScriptExecutor.java:44)
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Could not successfully complete backend operation due to repeated temporary exceptions after PT4S
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:101)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:55)
	... 26 more
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:128)
	at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:92)
	at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getSlice(AstyanaxKeyColumnValueStore.java:81)
	at org.janusgraph.diskstorage.keycolumnvalue.KCVSUtil.get(KCVSUtil.java:52)
	at org.janusgraph.diskstorage.log.kcvs.KCVSLog$3.call(KCVSLog.java:821)
	at org.janusgraph.diskstorage.log.kcvs.KCVSLog$3.call(KCVSLog.java:818)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:148)
	at org.janusgraph.diskstorage.util.BackendOperation$1.call(BackendOperation.java:162)
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:69)
	... 27 more
Caused by: com.netflix.astyanax.connectionpool.exceptions.PoolTimeoutException: PoolTimeoutException: [host=127.0.0.1(127.0.0.1):9160, latency=10000(10000), attempts=1]Timed out waiting for connection
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.waitForConnection(SimpleHostConnectionPool.java:231)
	at com.netflix.astyanax.connectionpool.impl.SimpleHostConnectionPool.borrowConnection(SimpleHostConnectionPool.java:198)
	at com.netflix.astyanax.connectionpool.impl.RoundRobinExecuteWithFailover.borrowConnection(RoundRobinExecuteWithFailover.java:84)
	at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:117)
	at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:352)
	at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:538)
	at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:126)
	... 35 more
```

**Comment by amyth** [comment]
My bad, the earlier stack trace was another error. Here is the stack trace to the exception in question.

```
org.janusgraph.core.JanusGraphException: Could not re-open management log
org.janusgraph.core.JanusGraphException: Could not re-open management log
	at org.janusgraph.diskstorage.Backend.getSystemMgmtLog(Backend.java:334)
	at org.janusgraph.graphdb.database.StandardJanusGraph.openManagement(StandardJanusGraph.java:303)
	at org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher.call(GraphIndexStatusWatcher.java:64)
	at org.janusgraph.graphdb.database.management.GraphIndexStatusWatcher.call(GraphIndexStatusWatcher.java:32)
	at java_util_concurrent_Callable$call.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at JanusGraphBuilder.createSchema(Script1.groovy:133)
	at JanusGraphBuilder.populate(Script1.groovy:148)
	at JanusGraphBuilder.main(Script1.groovy:33)
	at JanusGraphBuilder$main.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:133)
	at Script1.run(Script1.groovy:250)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:619)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:448)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.GremlinGroovyScriptEngine.eval(GremlinGroovyScriptEngine.java:421)
	at javax.script.AbstractScriptEngine.eval(AbstractScriptEngine.java:212)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.ScriptExecutor.evaluate(ScriptExecutor.java:55)
	at org.apache.tinkerpop.gremlin.groovy.jsr223.ScriptExecutor.main(ScriptExecutor.java:44)
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Permanent failure in storage backend
	at org.janusgraph.diskstorage.cassandra.thrift.CassandraThriftStoreManager.ensureColumnFamilyExists(CassandraThriftStoreManager.java:539)
	at org.janusgraph.diskstorage.cassandra.thrift.CassandraThriftStoreManager.ensureColumnFamilyExists(CassandraThriftStoreManager.java:511)
	at org.janusgraph.diskstorage.cassandra.thrift.CassandraThriftStoreManager.openDatabase(CassandraThriftStoreManager.java:328)
	at org.janusgraph.diskstorage.cassandra.thrift.CassandraThriftStoreManager.openDatabase(CassandraThriftStoreManager.java:67)
	at org.janusgraph.diskstorage.log.kcvs.KCVSLogManager.openLog(KCVSLogManager.java:225)
	at org.janusgraph.diskstorage.Backend.getSystemMgmtLog(Backend.java:332)
	... 21 more
Caused by: org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
	at org.janusgraph.diskstorage.cassandra.thrift.CassandraThriftStoreManager.ensureKeyspaceExists(CassandraThriftStoreManager.java:484)
	at org.janusgraph.diskstorage.cassandra.thrift.CassandraThriftStoreManager.ensureColumnFamilyExists(CassandraThriftStoreManager.java:517)
	... 26 more
Caused by: java.lang.IllegalStateException: Pool not open
	at org.apache.commons.pool.BaseKeyedObjectPool.assertOpen(BaseKeyedObjectPool.java:160)
	at org.apache.commons.pool.impl.GenericKeyedObjectPool.borrowObject(GenericKeyedObjectPool.java:1113)
	at org.janusgraph.diskstorage.cassandra.thrift.CassandraThriftStoreManager.ensureKeyspaceExists(CassandraThriftStoreManager.java:453)
	... 27 more
```

**Comment by pluradj** [comment]
In `createSchema()`, you should not be calling on this:

```
this.management.set('ids.block-size', 20000000)
```

If you want to set the `ids.block-size`, it would be best to put it in `conf/testconf.properties` when you first create the graph. That property has [`GLOBAL_OFFLINE`](http://docs.janusgraph.org/latest/config-ref.html#cfg-mutability) mutability. After the management transaction containing that update gets committed, the graph needs to be shutdown and reconnected before continuing to work with the graph. This is why Thrift could no longer connect to the keyspace.

I'll also note that if you're creating the indexes into an empty keyspace before any graph data is populated, the indexes will get enabled immediately and you wouldn't need to reindex, so you could  [remove this code](https://github.com/amyth/xonnect/blob/master/utils/population_scripts/populateJanus.groovy#L115-L119).

**Comment by pluradj** [comment]
@amyth I believe this issue is resolved. Please reopen or [reach out](https://github.com/JanusGraph/janusgraph/#community) on the users mailing list or Gitter.

**Comment by amyth** [comment]
Hi @pluradj, Yes the issue is resolved after removing the `block-size` modification statement and re-indexing statements.
