### ISSUE TITLE
FilterBuilder class not found exception

### ISSUE THREAD

**Issue by HackingJ** [JanusGraph/janusgraph#553]
Hi. I use JanusGraph 0.1.1 in spring.
I added dependency janus-core, janus-es, janus-cassandra and start with below configuration.

```
JanusGraph graph = JanusGraphFactory.build()
	      .set("storage.backend", "cassandra")
        .set("storage.hostname", "127.0.0.1")
        .set("index.search.backend", "elasticsearch")
        .set("index.search.hostname", "localhost")
        .set("index.search.elasticsearch.client-only", true)
        .set("storage.username", "dba")
        .set("storage.password", "dba").open();
```
And I received below message

```
java.lang.NoClassDefFoundError: org/elasticsearch/index/query/FilterBuilder
	at java.lang.Class.forName0(Native Method) ~[na:1.8.0_131]
	at java.lang.Class.forName(Unknown Source) ~[na:1.8.0_131]
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:56) ~[janusgraph-core-0.1.1.jar:na]
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:477) ~[janusgraph-core-0.1.1.jar:na]
	at org.janusgraph.diskstorage.Backend.getIndexes(Backend.java:464) ~[janusgraph-core-0.1.1.jar:na]
	at org.janusgraph.diskstorage.Backend.<init>(Backend.java:149) ~[janusgraph-core-0.1.1.jar:na]
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1850) ~[janusgraph-core-0.1.1.jar:na]
	at org.janusgraph.graphdb.database.StandardJanusGraph.<init>(StandardJanusGraph.java:134) ~[janusgraph-core-0.1.1.jar:na]
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:107) ~[janusgraph-core-0.1.1.jar:na]
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:97) ~[janusgraph-core-0.1.1.jar:na]
	at org.janusgraph.core.JanusGraphFactory$Builder.open(JanusGraphFactory.java:152) ~[janusgraph-core-0.1.1.jar:na]
	at cc.rnd.DbtestApplication.lambda$0(DbtestApplication.java:43) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.7.RELEASE.jar:1.5.7.RELEASE]
	at cc.rnd.DbtestApplication.main(DbtestApplication.java:28) [classes/:na]
Caused by: java.lang.ClassNotFoundException: org.elasticsearch.index.query.FilterBuilder
	at java.net.URLClassLoader.findClass(Unknown Source) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_131]
	at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source) ~[na:1.8.0_131]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[na:1.8.0_131]
	... 19 common frames omitted

```
I think because of FilterBuilder is not available in ES 2.x, see `https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_java_api_changes.html`

**Comment by sjudeng** [comment]
JanusGraph 0.1.1 only supports Elasticsearch 1.x. Can you check that this is the version on your classpath?

**Comment by dodizzle** [comment]
I also cannot build janusgraph 0.1.1 with the janusgraph-es module enabled.

**Comment by sjudeng** [comment]
@dodizzle You're building the full project or a custom application? Is it a compilation failure or a test failure? Without more information I'd think another version of Elasticsearch or an associated core dependency (Guava, etc.) are on the classpath.

**Comment by HackingJ** [comment]
Hi, Thank you for your answering.
In spring, if you just add janus-core, janus-elasticsearch, janus-cassandra, you can encounter fail message . this is why maven download newest elastic search which version is 2.x. so here is my solution.

```
<dependency>
      <groupId>org.janusgraph</groupId>
      <artifactId>janusgraph-es</artifactId>
      <version>0.1.1</version>
      <exclusions>
        <exclusion>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-log4j12</artifactId>
        </exclusion>
        <exclusion>
          <groupId>log4j</groupId>
          <artifactId>log4j</artifactId>
        </exclusion>
        <exclusion>
          <groupId>org.elasticsearch</groupId>
          <artifactId>elasticsearch</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.janusgraph</groupId>
      <artifactId>janusgraph-cassandra</artifactId>
      <version>0.1.1</version>
    </dependency>
    <dependency>
      <groupId>org.elasticsearch</groupId>
      <artifactId>elasticsearch</artifactId>
      <version>1.5.1</version><!--$NO-MVN-MAN-VER$-->
      <exclusions>
        <exclusion>
          <groupId>org.antlr</groupId>
          <artifactId>antlr-runtime</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
```

Note that no need janus-core because of included in storage backend dependency like janus-cassandra.

**Comment by sjudeng** [comment]
I still see org.elasticsearch:elasticsearch:1.5.1 in Maven: https://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.elasticsearch%22%20AND%20a%3A%22elasticsearch%22%20AND%20v%3A%221.5.1%22

I tried with your dependencies above using a clean local Maven repository and the project built okay.

```xml
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>test</groupId>
  <artifactId>janusgraph-test</artifactId>
  <packaging>jar</packaging>
  <version>0.0.1-SNAPSHOT</version>
  <dependencies>
    <dependency>
      <groupId>org.janusgraph</groupId>
      <artifactId>janusgraph-es</artifactId>
      <version>0.1.1</version>
      <exclusions>
        <exclusion>
          <groupId>org.slf4j</groupId>
          <artifactId>slf4j-log4j12</artifactId>
        </exclusion>
        <exclusion>
          <groupId>log4j</groupId>
          <artifactId>log4j</artifactId>
        </exclusion>
      </exclusions>
    </dependency>
    <dependency>
      <groupId>org.janusgraph</groupId>
      <artifactId>janusgraph-cassandra</artifactId>
      <version>0.1.1</version>
    </dependency>
  </dependencies>
</project>
```

```
$ mvn clean install -Dmaven.repo.local=tmp
...
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
...
```

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
