### ISSUE TITLE
Update JanusGraphFactory's usage of JanusGraphManager to make it optional

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#565]
`gremlin-server` is marked as an optional dependency for `janusgraph-core` to enable some of the capabilities for dynamic graph configuration. There are some calls in JanusGraphFactory that invoke JanusGraphManager which do not account for this. These need to be better isolated so that `gremlin-server` is not required.

**Comment by pluradj** [comment]
Example stack trace from a user's application which includes only `janusgraph-core`

```
java.lang.NoClassDefFoundError: org.apache.tinkerpop.gremlin.server.GraphManager
    at java.lang.ClassLoader.defineClassImpl(Native Method)
    at java.lang.ClassLoader.defineClass(ClassLoader.java:346)
    at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:154)
    at java.net.URLClassLoader.defineClass(URLClassLoader.java:729)
    at java.net.URLClassLoader.access$400(URLClassLoader.java:95)
    at java.net.URLClassLoader$ClassFinder.run(URLClassLoader.java:1184)
    at java.security.AccessController.doPrivileged(AccessController.java:686)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:604)
    at java.lang.ClassLoader.loadClassHelper(ClassLoader.java:850)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:829)
    at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:329)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:809)
    at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:148)
    at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:133)
    at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:113)
```
