### ISSUE TITLE
CQL test failures with Cassandra 3.11.0, 3.0.14 and 2.2.10

### ISSUE THREAD

**Issue by sjudeng** [JanusGraph/janusgraph#586]
There are a number of test failures when running CQL tests against more recent versions of Cassandra (3.11.x, 3.0.x, 2.10.x). See https://travis-ci.org/sjudeng/janusgraph/builds/282098716. All errors are consistently reproduced (Travis attempted three times and the same error occurred each time).

With 3.11.0 and 3.0.14 there are three failures in CQLStoreTest: testDefaultCFCompressor, testCustomCFCompressor and testDisableCFCompressor.

```
Tests run: 33, Failures: 3, Errors: 0, Skipped: 0, Time elapsed: 648.132 sec <<< FAILURE! - in org.janusgraph.diskstorage.cql.CQLStoreTest
testDefaultCFCompressor(org.janusgraph.diskstorage.cql.CQLStoreTest)  Time elapsed: 0.22 sec  <<< FAILURE!
java.lang.AssertionError: expected:<{sstable_compression=org.apache.cassandra.io.compress.LZ4Compressor, chunk_length_kb=64}> but was:<{chunk_length_in_kb=64, class=org.apache.cassandra.io.compress.LZ4Compressor}>
...

testCustomCFCompressor(org.janusgraph.diskstorage.cql.CQLStoreTest)  Time elapsed: 0.223 sec  <<< FAILURE!
java.lang.AssertionError: expected:<{sstable_compression=org.apache.cassandra.io.compress.DeflateCompressor, chunk_length_kb=128}> but was:<{chunk_length_in_kb=128, class=org.apache.cassandra.io.compress.DeflateCompressor}>
...

testDisableCFCompressor(org.janusgraph.diskstorage.cql.CQLStoreTest)  Time elapsed: 0.249 sec  <<< FAILURE!
java.lang.AssertionError: expected:<{}> but was:<{enabled=false}>
...
```

With 2.10.14 there is an error in CQLLogTest: testFuzzMessagesSerial.

```
Tests run: 11, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 80.187 sec <<< FAILURE! - in org.janusgraph.diskstorage.cql.CQLLogTest
testFuzzMessagesSerial(org.janusgraph.diskstorage.cql.CQLLogTest)  Time elapsed: 31.813 sec  <<< FAILURE!
java.lang.AssertionError: Did not read expected number of messages before timeout was reached (latch count is 32)
	at org.janusgraph.diskstorage.log.LogTest$LatchMessageReader.await(LogTest.java:325)
	at org.janusgraph.diskstorage.log.LogTest.testFuzzMessagesSerial(LogTest.java:212)
...
```

**Comment by sjudeng** [comment]
Duplicate of #585
