### ISSUE TITLE
ES: useMultitypeIndex is not set to true on migrated JanusGraph instance

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#591]
Testing out a migration from JanusGraph 0.1.1 to JanusGraph 0.2.0 with Elasticsearch 1.5.1, ran into this when opening up the graph:

```
java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.es.ElasticSearchIndex
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:69)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:477)
	at org.janusgraph.diskstorage.Backend.getIndexes(Backend.java:464)
	at org.janusgraph.diskstorage.Backend.<init>(Backend.java:149)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.getBackend(GraphDatabaseConfiguration.java:1897)
	at org.janusgraph.graphdb.database.StandardJanusGraph.<init>(StandardJanusGraph.java:136)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:164)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:133)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:80)
	at org.janusgraph.core.JanusGraphFactory$open.call(Unknown Source)
	... more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
	... 54 more
Caused by: java.lang.IllegalArgumentException: The key 'root.index.elasticsearch.use-deprecated-multitype-index' cannot be false when existing index contains multiple types.
	at com.google.common.base.Preconditions.checkArgument(Preconditions.java:122)
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.<init>(ElasticSearchIndex.java:235)
	... 59 more
```

For a migrated graph, [`useMultitypeIndex`](https://github.com/JanusGraph/janusgraph/blame/master/janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java#L202) should be set to true.

**Comment by pluradj** [comment]
[USE_DEPRECATED_MULTITYPE_INDEX](https://github.com/JanusGraph/janusgraph/blame/master/janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java#L156) is set as `GLOBAL_OFFLINE` and defaults to `false`, which doesn't give a chance to override via properties when making the connection.

**Comment by pluradj** [comment]
@davidclement90 is this something you can take a stab at? thanks.
