### ISSUE TITLE
cannot configure dynamic_templates in elasticsearch 5.x?

### ISSUE THREAD

**Issue by CJSoldier** [JanusGraph/janusgraph#653]
I'm trying to custom elasticsearch 5.x _all field using copy_to.
I created the janusgraph_vertices index ahead. Here is my elasticsearch mappings:

```
curl -XPUT http://localhost:9200/janusgraph_vertices -d '
{
  "settings": {
    "number_of_shards": 1,
    "index": {
      "analysis": {
        "analyzer": {
          "default": {
            "type": "smartcn"
          }
        }
      },
      "max_result_window": "1000000"
    }
  },
  "mappings": {
    "vertices": {
      "properties":{
        "full_name": {
            "type": "text",
            "store":false
        },
        "type":{
            "type":"keyword"
        }
      },
      "dynamic_templates": [
        {
          "exclude_taskId_permission": {
            "match_pattern": "regex",
            "match": "taskId_.+|permission_.+",
            "mapping": {
              "type": "text"
            }
          }
        },
        {
          "custom_all_field": {
            "match_mapping_type":"*",
            "mapping": {
              "type": "{dynamic_type}",
              "copy_to": "full_name"
            }
          }
        }
      ]
    }
  }
}
';
```

I want to copy all fields to full_name field except field name that starts with "taskId_" or "permission_".

In Java code, I added this parameter:  

`index.search.elasticsearch.create.use-external-mappings=true`

When I build mixed index, I got this error.

```
Caused by: org.apache.tinkerpop.shaded.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "dynamic_templates" (class org.janusgraph.diskstorage.es.rest.RestIndexMappings$RestIndexMapping), not marked as ignorable (one known property: "properties"])
 at [Source: org.apache.http.nio.entity.ContentInputStream@60222fd8; line: 1, column: 70] (through reference chain: java.util.LinkedHashMap["janusgraph_vertices"]->org.janusgraph.diskstorage.es.rest.RestIndexMappings["mappings"]->java.util.LinkedHashMap["vertices"]->org.janusgraph.diskstorage.es.rest.RestIndexMappings$RestIndexMapping["dynamic_templates"])
	at org.apache.tinkerpop.shaded.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
	at org.apache.tinkerpop.shaded.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1485)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1463)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:517)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:362)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:101)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.std.MapDeserializer._readAndBindStringKeyMap(MapDeserializer.java:517)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:362)
	at org.apache.tinkerpop.shaded.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27)
	at org.apache.tinkerpop.shaded.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3798)
	at org.apache.tinkerpop.shaded.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2915)
	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.getMapping(RestElasticSearchClient.java:202)
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.register(ElasticSearchIndex.java:324)
	... 5 more
```

I've already tried using _all field, but it didn't work. I heard that _all will be deprecated in es6.x, so I tried copy_to with dynamic templates.

**Comment by davidclement90** [comment]
It's a bug when JanusGraph deserialize the mapping. Thanks to spot it.
