### ISSUE TITLE
hadoop-hdfs jar is missing in janusgraph 0.2.0 distribution

### ISSUE THREAD

**Issue by jerryjch** [JanusGraph/janusgraph#674]
hadoop-hdfs-2.7.2.jar is in the 0.1.0 release distribution, but not in 0.2.0.
Let's find out why and bring it back.

**Comment by blindenvy** [comment]
It's not just `hadoop-hdfs-2.7.2.jar`. There are several `hadoop-*` jars that are missing in 0.2.0 hadoop-bin release that were present in the 0.1.0 release.

**Comment by jerryjch** [comment]
it is a serious problem.  Any Graph OLAP with hadoop file based input or output formats will not work.

**Comment by jerryjch** [comment]
The fact that all the UT passed tells the hadoop-hdfs jar is available in the build and test phases, but only missing in the distribution/assembly phase.

**Comment by jerryjch** [comment]
Ok. false alarm. Graph OLAP with hdfs based input format still work fine.
The hbase-sharded jars contain the missing hdfs (and other) missing hadoop classes, in there with no shading.
But still need to figure out a more elegant way to fix this.

**Comment by jerryjch** [comment]
I have to take back the previous comment.
It does NOT work.  I missed giving the HADOOP_CONF_DIR to hadoop-gremlin. 
It was working for a local file system.
As soon as I set the hadoop conf dir of a real hadoop cluster for hadoop-gremlin, it failed:

`Exception in thread "main" org.apache.tinkerpop.gremlin.groovy.plugin.PluginInitializationException: No FileSystem for scheme: hdfs
        at org.apache.tinkerpop.gremlin.hadoop.groovy.plugin.HadoopGremlinPlugin.afterPluginTo(HadoopGremlinPlugin.java:91)
        at org.apache.tinkerpop.gremlin.groovy.plugin.AbstractGremlinPlugin.pluginTo(AbstractGremlinPlugin.java:86)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
        at org.apache.tinkerpop.gremlin.console.PluggedIn.activate(PluggedIn.groovy:58)
        at org.apache.tinkerpop.gremlin.console.Console$_closure19.doCall(Console.groovy:146)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
        at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
        at org.codehaus.groovy.runtime.metaclass.ClosureMetaClass.invokeMethod(ClosureMetaClass.java:294)
        at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1022)
        at groovy.lang.Closure.call(Closure.java:414)
        at groovy.lang.Closure.call(Closure.java:430)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2040)
        at org.codehaus.groovy.runtime.DefaultGroovyMethods.each(DefaultGroovyMethods.java:2025)
        at org.codehaus.groovy.runtime.dgm$158.doMethodInvoke(Unknown Source)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
        at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:133)
        at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:232)
        at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:478)

Caused by: java.io.IOException: No FileSystem for scheme: hdfs
        at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:2644)
        at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2651)
        at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:92)
        at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2687)
        at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2669)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:371)
        at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:170)
        at org.apache.tinkerpop.gremlin.hadoop.groovy.plugin.HadoopGremlinPlugin.afterPluginTo(HadoopGremlinPlugin.java:84)
`

**Comment by blindenvy** [comment]
Yes, this is the same issue we were seeing. We had to include the `hadoop-hdfs-2.7.2.jar` to resolve that error. But adding individual jars can be problematic. We've seen method signature issues picking up jars provided by the hadoop stack (ie. HDP uses 2.7.3) and also conflicts between these added jars and the shaded jar provided by janus.

**Comment by pluradj** [comment]
Reopening since it is not in the `0.2` branch yet
