### ISSUE TITLE
Polygon geoshape deserializtion fails on JanusGraph 0.2.0

### ISSUE THREAD

**Issue by tsipinio** [JanusGraph/janusgraph#687]
After upgrading Janusgraph to version 0.2.0 I get NullPointerException exception in deserializing json back to Geoshape object. It happens only for polygons

Here is simple test:
```scala
  val geoShapeWriter = {
    val module = new SimpleModule()
    module.addSerializer(new Geoshape.GeoshapeGsonSerializerV1d0())
    val w = new ObjectMapper()
    w.registerModule(module)
  }
  val geoShapeReader = new ObjectMapper()
  val geoShapeSerializer = new Geoshape.GeoshapeSerializer()

  val box: Geoshape = Geoshape.box(33.416420, -111.939836, 33.430085, -111.926103)
  val json = geoShapeWriter.writeValueAsString(box)
  geoShapeSerializer.convert(geoShapeReader.readValue(json, classOf[java.util.HashMap[String, AnyRef]]))
```

This code throws:
```
java.lang.NullPointerException:
[info]   at org.locationtech.spatial4j.io.GeoJSONReader.readShapeFromCoordinates(GeoJSONReader.java:304)
[info]   at org.locationtech.spatial4j.io.GeoJSONReader.readShape(GeoJSONReader.java:248)
[info]   at org.locationtech.spatial4j.io.GeoJSONReader.read(GeoJSONReader.java:48)
[info]   at org.janusgraph.core.attribute.Geoshape$GeoshapeSerializer.convertGeometry(Geoshape.java:540)
[info]   at org.janusgraph.core.attribute.Geoshape$GeoshapeSerializer.convertGeoJson(Geoshape.java:502)
[info]   at org.janusgraph.core.attribute.Geoshape$GeoshapeSerializer.convert(Geoshape.java:443)
[info]   at com.janus.test.JanusSerializationTest.$anonfun$new$3(JanusSerializationTest.scala:36)
[info]   at org.scalatest.OutcomeOf.outcomeOf(OutcomeOf.scala:85)
[info]   at org.scalatest.OutcomeOf.outcomeOf$(OutcomeOf.scala:83)
[info]   at org.scalatest.OutcomeOf$.outcomeOf(OutcomeOf.scala:104)
```

**Comment by davidclement90** [comment]
Do you have JTS in your dependencies ? It's an optional dependency required for polygon.
```

<!-- Java Topology Suite (JTS) -->
            <dependency>
                <groupId>com.vividsolutions</groupId>
                <artifactId>jts</artifactId>
                <version>1.13</version>
            </dependency>

```

**Comment by tsipinio** [comment]
I have just checked with this dependency and got the same exception

**Comment by davidclement90** [comment]
Try box.toGeoJson() instead of geoShapeWriter.writeValueAsString(box)

**Comment by tsipinio** [comment]
I tried. Got the same error
```scala
  val json = box.toGeoJson
   val g = geoShapeSerializer.convert(geoShapeReader.readValue(json, classOf[java.util.HashMap[String, AnyRef]]))
```

```
java.lang.NullPointerException
	at org.locationtech.spatial4j.io.GeoJSONReader.readShapeFromCoordinates(GeoJSONReader.java:304)
	at org.locationtech.spatial4j.io.GeoJSONReader.readShape(GeoJSONReader.java:248)
	at org.locationtech.spatial4j.io.GeoJSONReader.read(GeoJSONReader.java:48)
	at org.janusgraph.core.attribute.Geoshape$GeoshapeSerializer.convertGeometry(Geoshape.java:540)
	at org.janusgraph.core.attribute.Geoshape$GeoshapeSerializer.convertGeoJson(Geoshape.java:502)
	at org.janusgraph.core.attribute.Geoshape$GeoshapeSerializer.convert(Geoshape.java:443)
	at com. janus.test.JanusSerializationTest.$anonfun$new$3(JanusSerializationTest.scala:49)
```

**Comment by davidclement90** [comment]
Something is wrong with your classpath, do you have jackson libs in your classpath or do you overwrite a tinkerpop or janusgraph lib ?

Because this Java code is working : 

```
import java.io.IOException;
import java.util.Map;

import org.apache.tinkerpop.shaded.jackson.databind.ObjectMapper;
import org.apache.tinkerpop.shaded.jackson.databind.module.SimpleModule;
import org.janusgraph.core.attribute.Geoshape;
import org.janusgraph.core.attribute.Geoshape.GeoshapeSerializer;

public class Main {

    public static void main(String[] args) throws IOException {
        final ObjectMapper geoShapeReader = new ObjectMapper();
        final GeoshapeSerializer geoShapeSerializer = new Geoshape.GeoshapeSerializer();
        final Geoshape box = Geoshape.box(33.42,-111.93, 33.43, -111.92);
        final ObjectMapper geoShapeWriter = new ObjectMapper();
        final SimpleModule module = new SimpleModule();
        module.addSerializer(new Geoshape.GeoshapeGsonSerializerV1d0());
        geoShapeWriter.registerModule(module);
        System.out.println(box.toGeoJson());
        System.out.println(geoShapeSerializer.convert(geoShapeReader.readValue(box.toGeoJson(), Map.class)));
        System.out.println(geoShapeSerializer.convert(geoShapeReader.readValue(geoShapeWriter.writeValueAsString(box), Map.class)));
    }
}
```
And give this in sysout 
```
{"type":"Polygon","coordinates": [[[-111.93,33.42],[-111.93,33.43],[-111.92,33.43],[-111.92,33.42],[-111.93,33.42]]]}
ENVELOPE (-111.93, -111.92, 33.43, 33.42)
ENVELOPE (-111.93, -111.92, 33.43, 33.42)
```
With these dependencies 
```
    <dependency>
      <groupId>org.janusgraph</groupId>
      <artifactId>janusgraph-core</artifactId>
      <version>0.2.0</version>
    </dependency>
    <dependency>
      <groupId>com.vividsolutions</groupId>
      <artifactId>jts</artifactId>
      <version>1.13</version>
    </dependency>
```

**Comment by tsipinio** [comment]
Sorry for long delay. I found the issue. Thank you for help
