### ISSUE TITLE
Various Gremlin query patterns throw NPE when query.batch=true

### ISSUE THREAD

**Issue by twilmes** [JanusGraph/janusgraph#71]
These queries fail when running with `query.batch=true`.  

Here are a few simple examples:
- ` g.V().has('id', 1).emit().repeat(out('knows'))`
- `g.V().match(__.as('a').out().as('b'))`

Right now the TinkerPop test suite is not executed with `query.batch` enabled so I believe this should be enabled first under this issue.  With that running, we'll have a better idea of the full scope of `query.batch` issues and can address the problem.

```groovy
gremlin> graph = JanusGraphFactory.open('conf/janusgraph-cassandra.properties')
==>standardjanusgraph[cassandrathrift:[127.0.0.1]]
gremlin> g = graph.traversal()
==>graphtraversalsource[standardjanusgraph[cassandrathrift:[127.0.0.1]], standard]
gremlin> v1 = graph.addVertex('id', 1)
==>v[4240]
gremlin> v2 = graph.addVertex('id', 2)
==>v[4096]
gremlin> v1.addEdge('knows', v2)
==>e[176-39s-1lh-35s][4240-knows->4096]
gremlin> g.tx().commit()
==>null
gremlin> g.V().has('id', 1).emit().repeat(out('knows'))
16:24:29 WARN  org.janusgraph.graphdb.transaction.StandardJanusGraphTx  - Query requires iterating over all vertices [(id = 1)]. For better performance, use indexes
==>v[4240]
java.lang.NullPointerException
Display stack trace? [yN] y
java.lang.NullPointerException
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphVertexStep.flatMap(JanusGraphVertexStep.java:109)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:47)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphVertexStep.processNextStart(JanusGraphVertexStep.java:102)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:140)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:54)
	at org.apache.tinkerpop.gremlin.process.traversal.step.branch.RepeatStep$RepeatEndStep.standardAlgorithm(RepeatStep.java:251)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ComputerAwareStep.processNextStart(ComputerAwareStep.java:47)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:140)
	at org.apache.tinkerpop.gremlin.process.traversal.step.branch.RepeatStep.standardAlgorithm(RepeatStep.java:162)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ComputerAwareStep.processNextStart(ComputerAwareStep.java:47)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:140)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:147)
	at org.apache.tinkerpop.gremlin.console.Console$_closure3.doCall(Console.groovy:182)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:93)
```

```groovy
gremlin> g.V().match(__.as('a').out().as('b'))
16:28:46 WARN  org.janusgraph.graphdb.transaction.StandardJanusGraphTx  - Query requires iterating over all vertices [()]. For better performance, use indexes
==>[a:v[4240], b:v[4096]]
java.lang.NullPointerException
Display stack trace? [yN] y
java.lang.NullPointerException
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphVertexStep.flatMap(JanusGraphVertexStep.java:109)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.FlatMapStep.processNextStart(FlatMapStep.java:47)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphVertexStep.processNextStart(JanusGraphVertexStep.java:102)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:140)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ExpandableStepIterator.next(ExpandableStepIterator.java:54)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.MatchStep$MatchEndStep.processNextStart(MatchStep.java:460)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:140)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:147)
	at org.apache.tinkerpop.gremlin.process.traversal.step.map.MatchStep.standardAlgorithm(MatchStep.java:313)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.ComputerAwareStep.processNextStart(ComputerAwareStep.java:47)
	at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.hasNext(AbstractStep.java:140)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:147)
	at org.apache.tinkerpop.gremlin.console.Console$_closure3.doCall(Console.groovy:182)
```

**Comment by monali01** [comment]
Are there any updates on this issue?

**Comment by pencal** [comment]
It looks like I just run into the same issue too.

**Comment by pencal** [comment]
Been studying this the whole day, here is what i found - the NPE manifests in JanusGraphPropertiesStep.java and JanusGraphVertexStep.java if query.batch is set to true. As suggested, I can reliably reproduce the NPE if I add **.set(USE_MULTIQUERY, true)**
in StorageSetup.java:71 

The problems seem to be related to the fact that in both JanusGraphPropertiesStep.java and JanusGraphVertexStep.java, the multiQueryResults are only updated when it is not initialized. I was able to fix the problem JanusGraphPropertiesStep.java. Still need to understand how the core works better to fix JanusGraphVertexStep.java

**Comment by pluradj** [comment]
@twilmes Did you submit a PR for this?

**Comment by twilmes** [comment]
@pluradj I had not yet but I just put in #1000 to address this.
