### ISSUE TITLE
Elasticsearch backend fails to add value to list property if that property doesn't already exist

### ISSUE THREAD

**Issue by severin83** [JanusGraph/janusgraph#718]
If you have an indexed property with list or set cardinality (in elasticsearch) and you create a new vertex without assigning any value to that property during the creation, then adding a value to that property lateron will fail on commit, because the elasticsearch script to add the property value causes an error (NullReferenceException) in elasticsearch.

The elasticsearch painless script produced looks like this:
`ctx._source[\"name\"].add(\"FOO\");`

It should make a null-check if that property doesn't already exist on the vertex, like so:
`if(ctx._source[\"name\"] == null) ctx._source[\"name\"] = []; ctx._source[\"name\"].add(\"FOO\");`

Note, that the "upsert" statement in the elasticsearch query doesn't apply in this case, because it gets used only if the document (i.e. vertex) doesn't already exist.

**Comment by davidclement90** [comment]
Do you have the log with the error ?
For me upsert statement will be apply in your example, add on an element which exists : ([link](https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-es/src/main/java/org/janusgraph/diskstorage/es/ElasticSearchIndex.java#L573))

**Comment by severin83** [comment]
Here's how to reproduce the error:
I'm using Janusgraph 0.2.0 with berkeley db and the bundled version of elasticsearch in this example.

```
mgmt = graph.openManagement()
titleKey = mgmt.makePropertyKey('title').dataType(String.class).cardinality(LIST).make()
nameKey = mgmt.makePropertyKey('name').dataType(String.class).cardinality(LIST).make()
mgmt.buildIndex('searchIdx', Vertex.class).addKey(titleKey, Mapping.STRING.asParameter()).addKey(nameKey, Mapping.STRING.asParameter()).buildMixedIndex('search')
mgmt.commit()
graph.tx().commit()
v = graph.addVertex('title', 'FirstVertex')
graph.tx().commit()
v.property('name', 'VertexName')

graph.tx().commit()
```

the gremlin console gives me this error:

```
09:22:46 ERROR org.janusgraph.diskstorage.es.rest.RestElasticSearchClient  - Failed to execute ES query: {type=illegal_argument_exception, reason=failed to execute script, caused_by={type=script_exception, reason=runtime error, script_stack=[ctx._source["name"].add("VertexName");,                    ^---- HERE], script=ctx._source["name"].add("VertexName");, lang=painless, caused_by={type=null_pointer_exception, reason=null}}}
09:22:46 ERROR org.janusgraph.diskstorage.es.ElasticSearchIndex  - Failed to execute bulk Elasticsearch mutation
java.io.IOException: Failure(s) in Elasicsearch bulk request: [{type=illegal_argument_exception, reason=failed to execute script, caused_by={type=script_exception, reason=runtime error, script_stack=[ctx._source["name"].add("VertexName");,                    ^---- HERE], script=ctx._source["name"].add("VertexName");, lang=painless, caused_by={type=null_pointer_exception, reason=null}}}]

```

And this is the error in the elasticsearch output:

```
[2017-11-20T09:22:46,648][DEBUG][o.e.a.b.TransportShardBulkAction] [02U0yu4] [janusgraph_searchidx][2] failed to execute bulk item (update) BulkShardRequest [[janusgraph_searchidx][2]] containing [org.elasticsearch.action.update.UpdateRequest@21f63a26]
java.lang.IllegalArgumentException: failed to execute script
        at org.elasticsearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:266) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:202) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.action.update.UpdateHelper.prepare(UpdateHelper.java:82) ~[elasticsearch-5.6.2.jar:5.6.2]
        at org.elasticsearch.action.bulk.TransportShardBulkAction.executeUpdateRequest(TransportShardBulkAction.java:277) 
[…]
Caused by: org.elasticsearch.script.ScriptException: runtime error
        at org.elasticsearch.painless.PainlessScript.convertToScriptException(PainlessScript.java:101) ~[?:?]
        at org.elasticsearch.painless.PainlessScript$Script.execute(ctx._source["name"].add("VertexName");:20) ~[?:?]
        at org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:133) ~[?:?]
        at org.elasticsearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:261) ~[elasticsearch-5.6.2.jar:5.6.2]
        ... 28 more
Caused by: java.lang.NullPointerException
        at org.elasticsearch.painless.DefBootstrap$PIC.fallback(DefBootstrap.java:202) ~[?:?]
        at org.elasticsearch.painless.PainlessScript$Script.execute(ctx._source["name"].add("VertexName");:20) ~[?:?]
        at org.elasticsearch.painless.ScriptImpl.run(ScriptImpl.java:133) ~[?:?]
        at org.elasticsearch.action.update.UpdateHelper.executeScript(UpdateHelper.java:261) ~[elasticsearch-5.6.2.jar:5.6.2]
        ... 28 more

```

**Comment by CJSoldier** [comment]
Hi davidclement90, I got the same error. I'm using janusgraph 0.2.1 with ES 5.6.
I can reproduce it this way:

Build two indexes at the same time, one has cardinality SINGLE, the other has cardinality LIST.
Assign a value to only the single property of a new vertex.
Update the vertex later by adding a value to the list property.

```
JanusGraphManagement mgmt = graph.openManagement();
String personEmailListStr = "Person_emailList";
if (!mgmt.containsGraphIndex(personEmailListStr)) {
    PropertyKey personEmailListPK = mgmt.makePropertyKey(personEmailListStr).dataType(String.class).cardinality(Cardinality.LIST).make();
    mgmt.buildIndex(personEmailListStr, Vertex.class).addKey(personEmailListPK).buildCompositeIndex();
    buildESIndex(mgmt, personEmailListPK, Parameter.of("Cardinality", "LIST"));
}

String personNameStr = "Person_username";
if (!mgmt.containsGraphIndex(personNameStr)) {
    PropertyKey personName = mgmt.makePropertyKey(personNameStr).dataType(String.class).cardinality(Cardinality.SINGLE).make();
    mgmt.buildIndex(personNameStr, Vertex.class).addKey(personName).buildCompositeIndex();
    buildESIndex(mgmt, personName, Parameter.of("Cardinality", "SINGLE"));
}

if (mgmt != null && mgmt.isOpen()) {
    mgmt.commit();
}

JanusGraphTransaction tx = graph.newTransaction();
JanusGraphVertex vertex1 = tx.addVertex(T.label, "Person");
vertex1.property("Person_username", "name1");
long id = vertex1.longId();
System.out.println("id="+id);
tx.commit();

tx = graph.newTransaction();
JanusGraphVertex vertex2 = tx.getVertex(id);
vertex2.property("Person_emailList", "aa@qq.com");
vertex2.property("Person_emailList", "bb@qq.com");
tx.commit();
```

Here is the error log:

```
java.io.IOException: Failure(s) in Elasicsearch bulk request: [{type=illegal_argument_exception, reason=failed to execute script, caused_by={type=script_exception, reason=runtime error, script_stack=[ctx._source["Person_emailList"].add("bb@qq.com");,                                ^---- HERE], script=ctx._source["Person_emailList"].add("bb@qq.com");ctx._source["Person_emailList"].add("aa@qq.com");, lang=painless, caused_by={type=null_pointer_exception, reason=null}}}]
	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.bulkRequest(RestElasticSearchClient.java:265)
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.mutate(ElasticSearchIndex.java:612)
	at org.janusgraph.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:160)
	at org.janusgraph.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:157)
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:69)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:55)
	at org.janusgraph.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:157)
	at org.janusgraph.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:138)
	at org.janusgraph.diskstorage.BackendTransaction.commitIndexes(BackendTransaction.java:141)
	at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:751)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1374)
	at org.janusgraph.diskstorage.es.TitanHelperOverview33.main(TitanHelperOverview33.java:83)
19:31:24,555 ERROR StandardJanusGraph:755 - Error while commiting index mutations for transaction [3] on index: search
org.janusgraph.core.JanusGraphException: Could not execute operation due to backend exception
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:57)
	at org.janusgraph.diskstorage.indexing.IndexTransaction.flushInternal(IndexTransaction.java:157)
	at org.janusgraph.diskstorage.indexing.IndexTransaction.commit(IndexTransaction.java:138)
	at org.janusgraph.diskstorage.BackendTransaction.commitIndexes(BackendTransaction.java:141)
	at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:751)
	at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1374)
	at org.janusgraph.diskstorage.es.TitanHelperOverview33.main(TitanHelperOverview33.java:83)
Caused by: org.janusgraph.diskstorage.PermanentBackendException: Unknown exception while executing index operation
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.convert(ElasticSearchIndex.java:308)
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.mutate(ElasticSearchIndex.java:616)
	at org.janusgraph.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:160)
	at org.janusgraph.diskstorage.indexing.IndexTransaction$1.call(IndexTransaction.java:157)
	at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:69)
	at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:55)
	... 6 more
Caused by: java.io.IOException: Failure(s) in Elasicsearch bulk request: [{type=illegal_argument_exception, reason=failed to execute script, caused_by={type=script_exception, reason=runtime error, script_stack=[ctx._source["Person_emailList"].add("bb@qq.com");,                                ^---- HERE], script=ctx._source["Person_emailList"].add("bb@qq.com");ctx._source["Person_emailList"].add("aa@qq.com");, lang=painless, caused_by={type=null_pointer_exception, reason=null}}}]
	at org.janusgraph.diskstorage.es.rest.RestElasticSearchClient.bulkRequest(RestElasticSearchClient.java:265)
	at org.janusgraph.diskstorage.es.ElasticSearchIndex.mutate(ElasticSearchIndex.java:612)
	... 10 more
```

I've also tried to build only one index that has cardinality LIST. It worked well even if I update property the second time.

**Comment by davidclement90** [comment]
We have the same bug with Solr but I do not know how to fix it ?
The problem came from https://github.com/JanusGraph/janusgraph/blob/master/janusgraph-solr/src/main/java/org/janusgraph/diskstorage/solr/SolrIndex.java#L394 

@sjudeng or @amcp  some idea to fix it ?
