### ISSUE TITLE
Allow user to configure CQL PoolingOptions

### ISSUE THREAD

**Issue by yhwang** [JanusGraph/janusgraph#775]
When using CQL to connect to Cassandra backend storage, the default value for `connection per host` is 1 and `max request per connection` is 1024 (for `ProtocolVersion#V3`). These values may be sufficient for small number of concurrent threads. But for larger concurrent threads, it's easy to reach the limitation and get the exception. It would be good to provide the capability to adjust the `connection per host` and `max request per connection` values for CQL PoolingOptions.

Here is the reference for the [CQL Pool size](http://docs.datastax.com/en/developer/java-driver/2.1/manual/pooling) and [Javadoc](http://docs.datastax.com/en/drivers/java/2.1/com/datastax/driver/core/PoolingOptions.html)

**Comment by pluradj** [comment]
Nice find. Could you add an example of the exception/stack trace you hit when the error occurs? Thanks.

**Comment by yhwang** [comment]
@pluradj here is the exception:

```
14:17:39 INFO  org.janusgraph.diskstorage.util.BackendOperation - Temporary exception during backend operation [CacheMutation]. Attempting backoff retry.
org.janusgraph.diskstorage.TemporaryBackendException: Temporary failure in storage backend
        at io.vavr.API$Match$Case0.apply(API.java:3174) ~[vavr-0.9.0.jar:na]
        at io.vavr.API$Match.of(API.java:3137) ~[vavr-0.9.0.jar:na]
        at org.janusgraph.diskstorage.cql.CQLKeyColumnValueStore.lambda$static$0(CQLKeyColumnValueStore.java:120) ~[janusgraph-cql-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.cql.CQLStoreManager.mutateManyUnlogged(CQLStoreManager.java:427) ~[janusgraph-cql-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.cql.CQLStoreManager.mutateMany(CQLStoreManager.java:358) ~[janusgraph-cql-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.locking.consistentkey.ExpectedValueCheckingStoreManager.mutateMany(ExpectedValueCheckingStoreManager.java:79) ~[janusgraph-core-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:98) ~[janusgraph-core-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction$1.call(CacheTransaction.java:95) ~[janusgraph-core-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68) [janusgraph-core-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54) [janusgraph-core-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.persist(CacheTransaction.java:95) [janusgraph-core-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.flushInternal(CacheTransaction.java:143) [janusgraph-core-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.keycolumnvalue.cache.CacheTransaction.commit(CacheTransaction.java:200) [janusgraph-core-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.diskstorage.BackendTransaction.commitStorage(BackendTransaction.java:134) [janusgraph-core-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.graphdb.database.StandardJanusGraph.commit(StandardJanusGraph.java:737) [janusgraph-core-0.3.0-SNAPSHOT.jar:na]
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.commit(StandardJanusGraphTx.java:1374) [janusgraph-core-0.3.0-SNAPSHOT.jar:na]
        at com.ibm.janusgraph.utils.importer.vertex.VertexLoaderWorker.acceptRecord(VertexLoaderWorker.java:99) [janusgraph-utils-0.0.1-SNAPSHOT.jar:na]
        at com.ibm.janusgraph.utils.importer.vertex.VertexLoaderWorker.run(VertexLoaderWorker.java:121) [janusgraph-utils-0.0.1-SNAPSHOT.jar:na]
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [na:1.8.0_151]
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_151]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_151]
        at java.lang.Thread.run(Thread.java:748) [na:1.8.0_151]
Caused by: java.util.concurrent.ExecutionException: com.datastax.driver.core.exceptions.NoHostAvailableException: All host(s) tried for query failed (tried: /127.0.0.1:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [/127.0.0.1] Pool is busy (no available connection and the queue has reached its max size 256)), /127.0.0.1:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [/127.0.0.1] Pool is busy (no available connection and the queue has reached its max size 256)), /127.0.0.1:9042 (com.datastax.driver.core.exceptions.BusyPoolException: [/127.0.0.1] Pool is busy (no available connection and the queue has reached its max size 256)))
        at com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286) ~[guava-18.0.jar:na]
        at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116) ~[guava-18.0.jar:na]
        at io.vavr.control.Try.of(Try.java:62) ~[vavr-0.9.0.jar:na]
        at io.vavr.concurrent.FutureImpl.lambda$run$2(FutureImpl.java:199) ~[vavr-0.9.0.jar:na]
        ... 5 common frames omitted
```

**Comment by yhwang** [comment]
Since the PR #776  is landed, this could be closed. If there is any suggestion to improve the CQL pool configuration, I can work on it.
