### ISSUE TITLE
Update 0.2 to TinkerPop 3.2.7

### ISSUE THREAD

**Issue by robertdale** [JanusGraph/janusgraph#844]
- [x] Release TinkerPop 3.2.7
- [x] Pass TinkerPop tests
- [x] Fix ProfileTest
- [x] Fix HasTest
- [ ] Update docs

**Comment by robertdale** [comment]
Announcement:  https://groups.google.com/d/msg/gremlin-users/7gqHRd50nKQ/4QHCmsIhBwAJ

**Comment by robertdale** [comment]
```
export GREMLIN_TESTS='org.apache.tinkerpop.gremlin.process.traversal.step.filter.HasTest$Traversals,org.apache.tinkerpop.gremlin.process.traversal.step.filter.GroovyHasTest$Traversals,org.apache.tinkerpop.gremlin.structure.PropertyTest'

mvn clean install -Dtest.skip.tp=false -DskipTests=true -pl janusgraph-core,janusgraph-test -Dmaven.javadoc.skip=true

g_V_hasIdXemptyX_count(org.apache.tinkerpop.gremlin.process.traversal.step.filter.HasTest$Traversals)  Time elapsed: 0.294 sec  <<< ERROR!
java.lang.NullPointerException: null
	at java.util.Arrays.stream(Arrays.java:5004)
	at org.janusgraph.graphdb.tinkerpop.optimize.HasStepFolder.lambda$foldInIds$2(HasStepFolder.java:125)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at org.janusgraph.graphdb.tinkerpop.optimize.HasStepFolder.foldInIds(HasStepFolder.java:112)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStepStrategy.lambda$apply$1(JanusGraphStepStrategy.java:49)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStepStrategy.apply(JanusGraphStepStrategy.java:44)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversalStrategies.applyStrategies(DefaultTraversalStrategies.java:86)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.applyStrategies(DefaultTraversal.java:119)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:191)
	at org.apache.tinkerpop.gremlin.AbstractGremlinTest.printTraversalForm(AbstractGremlinTest.java:254)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.HasTest.g_V_hasIdXemptyX_count(HasTest.java:465)

g_V_hasIdXwithinXemptyXX_count(org.apache.tinkerpop.gremlin.process.traversal.step.filter.HasTest$Traversals)  Time elapsed: 0.244 sec  <<< ERROR!
java.lang.NullPointerException: null
	at java.util.Arrays.stream(Arrays.java:5004)
	at org.janusgraph.graphdb.tinkerpop.optimize.HasStepFolder.lambda$foldInIds$2(HasStepFolder.java:125)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at java.util.Collections$UnmodifiableCollection.forEach(Collections.java:1080)
	at org.janusgraph.graphdb.tinkerpop.optimize.HasStepFolder.foldInIds(HasStepFolder.java:112)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStepStrategy.lambda$apply$1(JanusGraphStepStrategy.java:49)
	at java.util.ArrayList.forEach(ArrayList.java:1255)
	at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStepStrategy.apply(JanusGraphStepStrategy.java:44)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversalStrategies.applyStrategies(DefaultTraversalStrategies.java:86)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.applyStrategies(DefaultTraversal.java:119)
	at org.apache.tinkerpop.gremlin.process.traversal.util.DefaultTraversal.hasNext(DefaultTraversal.java:191)
	at org.apache.tinkerpop.gremlin.AbstractGremlinTest.printTraversalForm(AbstractGremlinTest.java:254)
	at org.apache.tinkerpop.gremlin.process.traversal.step.filter.HasTest.g_V_hasIdXwithinXemptyXX_count(HasTest.java:473)
```
