### ISSUE TITLE
Bind dynamically created graphs to the gremlin executor's global bindings.

### ISSUE THREAD

**Issue by dpitera** [JanusGraph/janusgraph#883]
Full discussion of why this is important and a general plan of attack can be found [in this TinkerPop issue](https://issues.apache.org/jira/browse/TINKERPOP-1839), and it turns out we can host the solution purely at the JanusGraph level without directly making any changes to TinkerPop's lower level server components.

TLDR of that issue: 

With JanusGraph's notion of dynamic graphs, there is no way to make use of the [withRemote()](http://tinkerpop.apache.org/docs/current/reference/#connecting-via-remotegraph) functionality or make use of language clients demanding the traversal reference be bound to a variable.

Therefore, we need a way to dynamically modify the global bindings on the gremlin script engine without having to restart the server.

**Comment by paul-k-civitas** [comment]
Hey @dpitera, a project I'm working on will need this feature, so I'm developing against a locally-built snapshot based off of the latest commit of master (commit `1fabde7e04f798f33a5b3fb6f45a12a20b6c68ff`). I'm trying to verify that I can use the `GraphTraversalSource.withRemote()` functionality against a graph that was created dynamically in a previous client connection. I'm running the distributed Gremlin Server locally, and testing things via the Gremlin Console; I've done everything that the documentation suggests, and it appears to work fine. However, once the remote traversal source is created, if I try to actually execute a query against it, I get an exception thrown; the following script (executed on the Gremlin Console against a locally-running, clean Gremlin Server) illustrates what's happening:

```
gremlin> :remote connect tinkerpop.server conf/remote.yaml session
==>Configured localhost/127.0.0.1:8182-[d2601483-b7d4-4268-880f-ff681a42e246]
gremlin> :remote console
==>All scripts will now be sent to Gremlin Server - [localhost/127.0.0.1:8182]-[d2601483-b7d4-4268-880f-ff681a42e246] - type ':remote console' to return to local mode
gremlin> 
gremlin> map = new HashMap<String, Object>()
gremlin> map.put("storage.backend", "cql")
==>null
gremlin> map.put("storage.hostname", "127.0.0.1")
==>null
gremlin> ConfiguredGraphFactory.createTemplateConfiguration(new MapConfiguration(map))
==>null
gremlin> 
gremlin> graphName = "janus3"
==>janus3
gremlin> ConfiguredGraphFactory.create(graphName)
==>standardjanusgraph[cql:[127.0.0.1]]
gremlin> 
gremlin> :remote close
==>Removed - Gremlin Server - [localhost/127.0.0.1:8182]-[d2601483-b7d4-4268-880f-ff681a42e246]
gremlin> Thread.sleep(25000)
==>null
gremlin> :remote connect tinkerpop.server conf/remote.yaml
==>Configured localhost/127.0.0.1:8182
gremlin> :remote console
==>All scripts will now be sent to Gremlin Server - [localhost/127.0.0.1:8182] - type ':remote console' to return to local mode
gremlin> 
gremlin> ConfiguredGraphFactory.getGraphNames()
==>janus3
gremlin> janus3
==>standardjanusgraph[cql:[127.0.0.1]]
gremlin> janus3_traversal
==>graphtraversalsource[standardjanusgraph[cql:[127.0.0.1]], standard]
gremlin> 
gremlin> cluster = org.apache.tinkerpop.gremlin.driver.Cluster.open('conf/remote-objects.yaml'); \
......1> graphObj = EmptyGraph.instance(); \
......2> traversalObj = graphObj.traversal().withRemote(org.apache.tinkerpop.gremlin.driver.remote.DriverRemoteConnection.using(cluster, "janus3_traversal")); \
......3> traversalObj.V().count();
The traversal source [janus3_traversal] for alias [g] is not configured on the server.
Type ':help' or ':h' for help.
Display stack trace? [yN]y
org.apache.tinkerpop.gremlin.jsr223.console.RemoteException: The traversal source [janus3_traversal] for alias [g] is not configured on the server.
	at org.apache.tinkerpop.gremlin.console.jsr223.DriverRemoteAcceptor.submit(DriverRemoteAcceptor.java:178)
	at org.apache.tinkerpop.gremlin.console.GremlinGroovysh.execute(GremlinGroovysh.groovy:99)
	at org.codehaus.groovy.tools.shell.Shell.leftShift(Shell.groovy:122)
	at org.codehaus.groovy.tools.shell.ShellRunner.work(ShellRunner.groovy:95)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$work(InteractiveShellRunner.groovy)
	at sun.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:165)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.work(InteractiveShellRunner.groovy:130)
	at org.codehaus.groovy.tools.shell.ShellRunner.run(ShellRunner.groovy:59)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.super$2$run(InteractiveShellRunner.groovy)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.groovy.reflection.CachedMethod.invoke(CachedMethod.java:98)
	at groovy.lang.MetaMethod.doMethodInvoke(MetaMethod.java:325)
	at groovy.lang.MetaClassImpl.invokeMethod(MetaClassImpl.java:1225)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuperN(ScriptBytecodeAdapter.java:145)
	at org.codehaus.groovy.runtime.ScriptBytecodeAdapter.invokeMethodOnSuper0(ScriptBytecodeAdapter.java:165)
	at org.codehaus.groovy.tools.shell.InteractiveShellRunner.run(InteractiveShellRunner.groovy:89)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at org.apache.tinkerpop.gremlin.console.Console.<init>(Console.groovy:146)
	at org.codehaus.groovy.vmplugin.v7.IndyInterface.selectMethod(IndyInterface.java:236)
	at org.apache.tinkerpop.gremlin.console.Console.main(Console.groovy:453)
```

I'm also trying to connect to a dynamically-created graph using the Java API, and I get this error thrown, which may have a similar cause:
```java
Client client = Cluster.open().connect().alias("janus3_traversal");
client.submit("g.V().count()").one().getLong();
```
Causes the following error on the server (a similar one is thrown in the Java client application code):
```
84672 [gremlin-server-worker-1] WARN  org.apache.tinkerpop.gremlin.server.handler.OpSelectorHandler  - The traversal source [janus3_traversal] for alias [g] is not configured on the server.
org.apache.tinkerpop.gremlin.server.op.OpProcessorException: The traversal source [janus3_traversal] for alias [g] is not configured on the server.
        at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.validateTraversalSourceAlias(TraversalOpProcessor.java:233)
        at org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor.select(TraversalOpProcessor.java:159)
        at org.apache.tinkerpop.gremlin.server.handler.OpSelectorHandler.decode(OpSelectorHandler.java:88)
        at org.apache.tinkerpop.gremlin.server.handler.OpSelectorHandler.decode(OpSelectorHandler.java:48)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.codec.http.websocketx.WebSocketServerProtocolHandler$1.channelRead(WebSocketServerProtocolHandler.java:159)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:312)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:335)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1304)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:356)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:342)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:921)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:135)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:646)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:581)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:460)
        at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
        at java.lang.Thread.run(Thread.java:745)
```

I have no experience modifying or committing to the JanusGraph project, but if there's anything I can do to help get this feature fully functional and tested, please let me know.

**Comment by dpitera** [comment]
I _believe_ the feature is fully functional and tested (i.e. we wouldn't have merged it without doing so). However there of course can be bugs!

Having said that, the traversal reference does indeed seem to be bound on your cluster. However this is the case above, for sure, when the cluster connected to is defined by `conf/remote.yaml`. The cluster API you are using to connect the `withRemote` to is however defined by `conf/remote-objects.yaml` : `gremlin> cluster = org.apache.tinkerpop.gremlin.driver.Cluster.open('conf/remote-objects.yaml');`. My piece of advice is to ensure you are using these configuration files correctly. If the traversal reference is bound on the server, which we see it is, then this should work no problem if it is being sent to said server.

**Comment by pluradj** [comment]
@paul-k-civitas @dpitera if your recent disucssion is a new bug, could you please open a new issue to track it. thanks.

**Comment by jerlendds** [comment]
This is the latest issue I've been running into, I'm now able to successfully create graphs dynamically but they're not bound and impossible to access from an application making the dynamic graphs functionally useless. I've built the entire janusgraph project a few times and am trying to investigate the issue but I don't typically work in Java.


`janusgraph.properties`
```

gremlin.graph=org.janusgraph.core.JanusGraphFactory

storage.backend=cql
storage.hostname=sdb:9042
storage.directory=/var/lib/janusgraph/data
storage.cql.keyspace=janusgraph

index.search.backend=elasticsearch
index.search.hostname=index:9200
index.search.directory=/var/lib/janusgraph/index
```

`janusgraph-dynamic.properties`
```
gremlin.graph=org.janusgraph.core.ConfiguredGraphFactory
graph.graphname=project

storage.backend=cql
storage.hostname=sdb:9042
storage.directory=/var/lib/janusgraph/data
# storage.cql.keyspace=ConfigurationManagementGraph

index.search.backend=elasticsearch
index.search.hostname=index:9200
index.search.directory=/var/lib/janusgraph/index

```


`janusgraph-server.yaml`
```yaml

host: 0.0.0.0
port: 8182
evaluationTimeout: 30000
channelizer: org.apache.tinkerpop.gremlin.server.channel.WebSocketChannelizer
graphManager: org.janusgraph.graphdb.management.JanusGraphManager
graphs: {
  ConfigurationManagementGraph: /etc/opt/janusgraph/janusgraph-dynamic.properties,
  graph: /etc/opt/janusgraph/janusgraph-dynamic.properties # /etc/opt/janusgraph/janusgraph.properties
}
scriptEngines: {
  gremlin-groovy: {
    plugins: {
      org.janusgraph.graphdb.tinkerpop.plugin.JanusGraphGremlinPlugin: {},
      org.apache.tinkerpop.gremlin.server.jsr223.GremlinServerGremlinPlugin: {},
      org.apache.tinkerpop.gremlin.tinkergraph.jsr223.TinkerGraphGremlinPlugin: {},
      org.apache.tinkerpop.gremlin.jsr223.ImportGremlinPlugin: {
        classImports: [java.lang.Math],
        methodImports: [java.lang.Math#*]
      },
      org.apache.tinkerpop.gremlin.jsr223.ScriptFileGremlinPlugin: {
        files: [scripts/empty-sample.groovy]
      }
    }
  }
}
processors: [
  {
    className: org.apache.tinkerpop.gremlin.server.op.session.SessionOpProcessor,
    config: { 
      sessionTimeout: 28800000
    }
  },
  {
    className: org.apache.tinkerpop.gremlin.server.op.traversal.TraversalOpProcessor,
    config: {
      cacheExpirationTime: 600000,
      cacheMaxSize: 1000
    }
  }
]
metrics: {
  consoleReporter: {
    enabled: true,
    interval: 180000
  },
  csvReporter: {
    enabled: true,
    interval: 180000,
    fileName: /tmp/gremlin-server-metrics.csv
  },
  jmxReporter: { 
    enabled: true
  },
  slf4jReporter: {
    enabled: true,
    interval: 180000
  },
  graphiteReporter: {
    enabled: false,
    interval: 180000
  }
}
maxInitialLineLength: 4096
maxHeaderSize: 8192
maxChunkSize: 8192
maxContentLength: 65536
maxAccumulationBufferComponents: 1024
resultIterationBatchSize: 64
writeBufferLowWaterMark: 32768
writeBufferHighWaterMark: 65536
threadPoolWorker: 1
gremlinPool: 8

serializers:
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphBinaryMessageSerializerV1, config: { serializeResultToString: true }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerV3d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistry] }}
  - { className: org.apache.tinkerpop.gremlin.driver.ser.GraphSONMessageSerializerGremlinV1d0, config: { ioRegistries: [org.janusgraph.graphdb.tinkerpop.JanusGraphIoRegistryV1d0] }}
  

```
