### ISSUE TITLE
OLAP failed on remote spark but success on local mode

### ISSUE THREAD

**Issue by Luminginx** [JanusGraph/janusgraph#904]
I use SparkGraphComputer to count my janusgraph which uesd HBase 1.2.6 and Hadoop2.6.0-cdh5.7.0 .
When I use local[2] as the path to spark.master,it works. Then I use spark://hbp202:7078(it's another machine), show error:
>2018-01-23 14:19:00,717 INFO  [Executor task launch worker-0] executor.Executor: Running task 0.0 in stage 0.0 (TID 0)
2018-01-23 14:19:00,793 ERROR [Executor task launch worker-0] util.Utils: Exception encountered
java.lang.RuntimeException: readObject can't find class org.apache.hadoop.hbase.mapreduce.TableSplit
	at org.apache.hadoop.io.ObjectWritable.loadClass(ObjectWritable.java:377)
	at org.apache.hadoop.io.ObjectWritable.readObject(ObjectWritable.java:228)
	at org.apache.hadoop.io.ObjectWritable.readFields(ObjectWritable.java:77)
	at org.apache.spark.SerializableWritable$$anonfun$readObject$1.apply$mcV$sp(SerializableWritable.scala:45)
	at org.apache.spark.SerializableWritable$$anonfun$readObject$1.apply(SerializableWritable.scala:41)
	at org.apache.spark.SerializableWritable$$anonfun$readObject$1.apply(SerializableWritable.scala:41)
	at org.apache.spark.util.Utils$.tryOrIOException(Utils.scala:1269)
	at org.apache.spark.SerializableWritable.readObject(SerializableWritable.scala:41)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at java.io.ObjectStreamClass.invokeReadObject(ObjectStreamClass.java:1017)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1893)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.defaultReadFields(ObjectInputStream.java:1990)
	at java.io.ObjectInputStream.readSerialData(ObjectInputStream.java:1915)
	at java.io.ObjectInputStream.readOrdinaryObject(ObjectInputStream.java:1798)
	at java.io.ObjectInputStream.readObject0(ObjectInputStream.java:1350)
	at java.io.ObjectInputStream.readObject(ObjectInputStream.java:370)
	at org.apache.spark.serializer.JavaDeserializationStream.readObject(JavaSerializer.scala:75)
	at org.apache.spark.serializer.JavaSerializerInstance.deserialize(JavaSerializer.scala:114)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:258)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.hbase.mapreduce.TableSplit not found
	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2105)
	at org.apache.hadoop.io.ObjectWritable.loadClass(ObjectWritable.java:373)
	... 30 more

I use janusgraph 0.2.0, spark 2.1.0 and scala 2.11.11, and update the tinkerpop version to 3.3.1 to fix spark.
The following is my properties file.

>\#
\# Hadoop Graph Configuration
\#
gremlin.graph=org.apache.tinkerpop.gremlin.hadoop.structure.HadoopGraph
gremlin.hadoop.graphInputFormat=org.janusgraph.hadoop.formats.hbase.HBaseInputFormat
gremlin.hadoop.graphOutputFormat=org.apache.tinkerpop.gremlin.hadoop.structure.io.gryo.GryoOutputFormat
gremlin.hadoop.memoryOutputFormat=org.apache.hadoop.mapreduce.lib.output.SequenceFileOutputFormat  
gremlin.hadoop.jarsInDistributedCache=true
gremlin.hadoop.inputLocation=none
gremlin.hadoop.outputLocation=output
\#
\# JanusGraph HBase InputFormat configuration
\#
janusgraphmr.ioformat.conf.storage.backend=hbase
janusgraphmr.ioformat.conf.storage.hostname=hbp202
janusgraphmr.ioformat.conf.storage.hbase.keyspace=janusgraph
storage.hbase.keyspace=janusgraph
\#
\# SparkGraphComputer Configuration
\#
\#spark.master=local[2]    #success
spark.master=spark://hbp202:7078    #failed
spark.serializer=org.apache.spark.serializer.KryoSerializer
spark.executor.memory=10g
gremlin.spark.persistContext=true
gremlin.hadoop.defaultGraphComputer=org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputer
gremlin.spark.graphStorageLevel=MEMORY_AND_DISK

What is the general question, are different configuration parameters required under different modes?

**Comment by robertdale** [comment]
My guess is that the jars don't exist where they need to.  JanusGraph appears to be missing the `init-tp-spark.sh` script from the TinkerPop distribution.  Can you download [apache-tinkerpop-gremlin-console-3.2.6](https://archive.apache.org/dist/tinkerpop/3.2.6/apache-tinkerpop-gremlin-console-3.2.6-bin.zip) and follow the [SparkGraphComputer](http://tinkerpop.apache.org/docs/3.2.6/reference/#sparkgraphcomputer) instructions specifically with `init-tp-spark.sh` and see if that works for you?

**Comment by Luminginx** [comment]
@robertdale Thank you very much for your advice. After I set the variables and libs according to the script, the final program is normal. But it's a shame to restart spark. Is it necessary to use spark in janusgraph? Is there a parameter or method like the setjar to send my jar package remotely?
