### ISSUE TITLE
Cassandra Privilege "Create on All Keyspaces"

### ISSUE THREAD

**Issue by larsbremer** [JanusGraph/janusgraph#933]
Janusgraph requires the “create” privilege on all keyspaces even if a keyspace was created already. From my understanding this privilege is only used to create the keyspace. If the keyspace was created manually, the privilege is not needed.

Looking into the Janusgraph code the issue appears to be the following lines in the CQLStoreManager.java:266
`s.execute(createKeyspace(keyspaceName).ifNotExists().with().replication(replication));`

This is the stacktrace I get:
```
Exception in thread "main" java.lang.IllegalArgumentException: Could not instantiate implementation: org.janusgraph.diskstorage.cql.CQLStoreManager
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:69)
	at org.janusgraph.diskstorage.Backend.getImplementationClass(Backend.java:477)
	at org.janusgraph.diskstorage.Backend.getStorageManager(Backend.java:409)
	at org.janusgraph.graphdb.configuration.GraphDatabaseConfiguration.<init>(GraphDatabaseConfiguration.java:1376)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:164)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:133)
	at org.janusgraph.core.JanusGraphFactory.open(JanusGraphFactory.java:123)
	at org.janusgraph.core.JanusGraphFactory$Builder.open(JanusGraphFactory.java:264)
	at com.ibm.mdm.janusgraph.performance.connection.JanusGraphConnectionEmbedded.createGraph(JanusGraphConnectionEmbedded.java:36)
	at com.ibm.mdm.janusgraph.performance.connection.JanusGraphConnectionEmbedded.<init>(JanusGraphConnectionEmbedded.java:18)
	at com.ibm.mdm.janusgraph.performance.connection.JanusGraphConnectionEmbedded.getInstance(JanusGraphConnectionEmbedded.java:23)
	at com.ibm.mdm.janusgraph.performance.connection.JanusGraphConnectionFactory.getGraphConnection(JanusGraphConnectionFactory.java:16)
	at com.ibm.mdm.janusgraph.performance.JanusGraphApp.executeTests(JanusGraphApp.java:42)
	at com.ibm.mdm.janusgraph.performance.JanusGraphApp.main(JanusGraphApp.java:30)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.janusgraph.util.system.ConfigurationUtil.instantiate(ConfigurationUtil.java:58)
	... 13 more
Caused by: com.datastax.driver.core.exceptions.UnauthorizedException: User lars has no CREATE permission on <all keyspaces> or any of its parents
	at com.datastax.driver.core.exceptions.UnauthorizedException.copy(UnauthorizedException.java:59)
	at com.datastax.driver.core.exceptions.UnauthorizedException.copy(UnauthorizedException.java:25)
	at com.datastax.driver.core.DriverThrowables.propagateCause(DriverThrowables.java:37)
	at com.datastax.driver.core.DefaultResultSetFuture.getUninterruptibly(DefaultResultSetFuture.java:245)
	at com.datastax.driver.core.AbstractSession.execute(AbstractSession.java:68)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.initializeSession(CQLStoreManager.java:266)
	at org.janusgraph.diskstorage.cql.CQLStoreManager.<init>(CQLStoreManager.java:149)
	... 18 more
Caused by: com.datastax.driver.core.exceptions.UnauthorizedException: User lars has no CREATE permission on <all keyspaces> or any of its parents
	at com.datastax.driver.core.Responses$Error.asException(Responses.java:134)
	at com.datastax.driver.core.DefaultResultSetFuture.onSet(DefaultResultSetFuture.java:179)
	at com.datastax.driver.core.RequestHandler.setFinalResult(RequestHandler.java:177)
	at com.datastax.driver.core.RequestHandler.access$2500(RequestHandler.java:46)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.setFinalResult(RequestHandler.java:799)
	at com.datastax.driver.core.RequestHandler$SpeculativeExecution.onSet(RequestHandler.java:633)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:1070)
	at com.datastax.driver.core.Connection$Dispatcher.channelRead0(Connection.java:993)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:287)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by pluradj** [comment]
`CQLStoreManager` could do a lookup to see if the keyspace exists before attempting to create the keyspace. It would also need read access to `system.schema_keyspaces` table.

```
SELECT keyspace_name FROM system.schema_keyspaces WHERE keyspace_name = 'keyspaceName';
```

**Comment by TitiHl** [comment]
Hi, 

I am seeing the same issue when using 'cql' as storage.backend. Is there a fix or workaround for this? for some reason I cannot use 'cassandrathrift' to connect the remote Cassandra backend.

Thanks,
Alex

**Comment by TitiHl** [comment]
Hi @pluradj do you know are we getting the fix for this any soon as it is kind of blocking us to use keyspaces in development, or any workaround for this issue?
Thanks.

**Comment by TitiHl** [comment]
role  | username | resource            | permission
------+----------+---------------------+------------
janus | janus    | <keyspace ks_janus> |     CREATE
janus | janus    | <keyspace ks_janus> |      ALTER
janus | janus    | <keyspace ks_janus> |       DROP
janus | janus    | <keyspace ks_janus> |     SELECT
janus | janus    | <keyspace ks_janus> |     MODIFY
janus | janus    | <keyspace ks_janus> |  AUTHORIZE

**Comment by ankurgoelhc** [comment]
Hi @pluradj , we are using cassandra 3, which doesn't have system.schema_keyspaces, instead it has system_schema. After giving read access on all tables it still giving same exception.

**Comment by pluradj** [comment]
@TitiHl is investigating a fix for this. We'll need a code fix because the `create if not exists` flow requires the security check. The fix should be something along the lines of checking if the keyspace exists before attempting to create. If we can check permissions too, that could provide a more informative error message.

**Comment by pluradj** [comment]
@ankurgoelhc if you are able to change the permissions for the graph user, you'd need to issue something like this to give the graph user permission to create its own keyspace if not exists:

```
CREATE ROLE graphuser WITH LOGIN = true AND SUPERUSER = false AND PASSWORD = 'gremlin';
GRANT CREATE ON ALL KEYSPACES TO graphuser;
```

`graphuser` would be allowed to create a new keyspace in Cassandra when it connects, plus `graphuser` would have all permissions on the newly created keyspace.

The original poster is not able to change this permission. In that scenario, the keyspace would be created by the Cassandra administrator, and the graph user would need to get specific permissions granted afterwards:

```
GRANT ALL PERMISSIONS ON KEYSPACE janusgraph TO graphuser;
LIST ALL OF graphuser;
```

Thanks for the heads up on the `system_schema` differences between Cassandra 2 and 3. The code checking should account for this.
