### ISSUE TITLE
SASL authentication failed. The most likely cause is missing or invalid credentials.

### ISSUE THREAD

**Issue by FSixteen** [JanusGraph/janusgraph#966]
We hope to get your help. 
We hope to get your help. 
Here's what we are doing and the error we are seeing:

## action
#./bin/gremlin-server.sh ./conf/gremlin-server/gremlin-server-janusgraph.yaml

## Error Message
`2195 [hconnection-0xf316aeb-shared--pool1-t1] WARN  org.apache.hadoop.hbase.ipc.RpcClientImpl  - Exception encountered while connecting to the server : javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
2196 [hconnection-0xf316aeb-shared--pool1-t1] ERROR org.apache.hadoop.hbase.ipc.RpcClientImpl  - SASL authentication failed. The most likely cause is missing or invalid credentials. Consider 'kinit'.
javax.security.sasl.SaslException: GSS initiate failed [Caused by GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)]
	at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:211)
	at org.apache.hadoop.hbase.security.HBaseSaslRpcClient.saslConnect(HBaseSaslRpcClient.java:179)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupSaslConnection(RpcClientImpl.java:617)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.access$700(RpcClientImpl.java:162)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection$2.run(RpcClientImpl.java:743)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection$2.run(RpcClientImpl.java:740)
	at java.security.AccessController.doPrivileged(Native Method)
	at javax.security.auth.Subject.doAs(Subject.java:422)
	at org.apache.hadoop.security.UserGroupInformation.doAs(UserGroupInformation.java:1657)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.setupIOstreams(RpcClientImpl.java:740)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.writeRequest(RpcClientImpl.java:906)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl$Connection.tracedWriteRequest(RpcClientImpl.java:873)
	at org.apache.hadoop.hbase.ipc.RpcClientImpl.call(RpcClientImpl.java:1241)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient.callBlockingMethod(AbstractRpcClient.java:227)
	at org.apache.hadoop.hbase.ipc.AbstractRpcClient$BlockingRpcChannelImplementation.callBlockingMethod(AbstractRpcClient.java:336)
	at org.apache.hadoop.hbase.protobuf.generated.ClientProtos$ClientService$BlockingStub.scan(ClientProtos.java:34094)
	at org.apache.hadoop.hbase.client.ScannerCallable.openScanner(ScannerCallable.java:400)
	at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:204)
	at org.apache.hadoop.hbase.client.ScannerCallable.call(ScannerCallable.java:65)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithoutRetries(RpcRetryingCaller.java:210)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:364)
	at org.apache.hadoop.hbase.client.ScannerCallableWithReplicas$RetryingRPC.call(ScannerCallableWithReplicas.java:338)
	at org.apache.hadoop.hbase.client.RpcRetryingCaller.callWithRetries(RpcRetryingCaller.java:136)
	at org.apache.hadoop.hbase.client.ResultBoundedCompletionService$QueueingFuture.run(ResultBoundedCompletionService.java:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: GSSException: No valid credentials provided (Mechanism level: Failed to find any Kerberos tgt)
	at sun.security.jgss.krb5.Krb5InitCredential.getInstance(Krb5InitCredential.java:147)
	at sun.security.jgss.krb5.Krb5MechFactory.getCredentialElement(Krb5MechFactory.java:122)
	at sun.security.jgss.krb5.Krb5MechFactory.getMechanismContext(Krb5MechFactory.java:187)
	at sun.security.jgss.GSSManagerImpl.getMechanismContext(GSSManagerImpl.java:224)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:212)
	at sun.security.jgss.GSSContextImpl.initSecContext(GSSContextImpl.java:179)
	at com.sun.security.sasl.gsskerb.GssKrb5Client.evaluateChallenge(GssKrb5Client.java:192)
	... 26 more
`

### cat ./conf/gremlin-server/socket-janusgraph-hbase-server.properties 
graph.set-vertex-id=true
gremlin.graph=org.janusgraph.core.JanusGraphFactory
storage.backend=hbase
#deliberately change
storage.hostname=host1,host2
storage.hbase.table=GatXtcJssGlsj:janusgraph

cache.db-cache=true
cache.db-cache-clean-wait=20
cache.db-cache-time=180000
cache.db-cache-size=0.5
index.search.backend=elasticsearch
index.search.hostname=host1,host2
index.search.port=9200
index.search.elasticsearch.client-only=false

java.security.krb5.conf=/etc/security/krb5.conf
java.security.auth.login.config=/etc/hbase/conf/hbase_client_jaas.conf
zookeeper.sasl.client=true
storage.hbase.ext.hbase.master.kerberos.principal=hbase/_HOST@BIGDATA
storage.hbase.ext.hbase.regionserver.kerberos.principal=hbase/_HOST@BIGDATA
storage.hbase.ext.hbase.security.authentication=kerberos
storage.hbase.ext.hadoop.security.authentication=kerberos
storage.hbase.ext.hbase.security.authorization=true
storage.hbase.ext.hbase.thrift.kerberos.principal=HTTP/_HOST@BIGDATA
storage.hbase.ext.hbase.zookeeper.property.clientPort=2181
storage.hbase.ext.hbase.zookeeper.quorum=host1,host2
storage.hbase.ext.zookeeper.znode.parent=/hbase-secure

### cat /etc/krb5.conf
[libdefaults]
  renew_lifetime = 3000d
  forwardable = true
  default_realm = BIGDATA
  ticket_lifetime = 3000d
  dns_lookup_realm = false
  dns_lookup_kdc = false
  default_ccache_name = /tmp/krb5cc_%{uid}
  #default_tgs_enctypes = aes des3-cbc-sha1 rc4 des-cbc-md5
  #default_tkt_enctypes = aes des3-cbc-sha1 rc4 des-cbc-md5
[domain_realm]
  .bigdata = BIGDATA
[logging]
  default = FILE:/var/log/krb5kdc.log
  admin_server = FILE:/var/log/kadmind.log
  kdc = FILE:/var/log/krb5kdc.log
[realms]
  BIGDATA = {
    admin_server = host1
    kdc = host1
    kdc = host2
  }

### cat /etc/hbase/conf/hbase_client_jaas.conf 
Client {
com.sun.security.auth.module.Krb5LoginModule required
useKeyTab=false
useTicketCache=true;
};

### klist
Ticket cache: FILE:/tmp/krb5cc_0
Default principal: GatXtcJssGlsj/bigdata@BIGDATA

Valid starting     Expires            Service principal
03/27/18 14:58:00  06/12/26 11:59:54  krbtgt/BIGDATA@BIGDATA
	renew until 06/12/26 11:59:54

## Other Notes
hbase 1.1.2
dataspace 1.0.2
kerberos 1.10.3
...

**Comment by myitroad** [comment]
Try get or update tgt at your janusgraph machine. Example as follows:
```
# klist -k /etc/security/keytabs/superadmin-master.keytab
Keytab name: FILE:/etc/security/keytabs/superadmin-master.keytab
KVNO Principal
---- --------------------------------------------------------------------------
  1 superadmin-master@YOUR.HOST
kinit -kt  /etc/security/keytabs/superadmin-master.keytab superadmin-master@YOUR.HOST
```

**Comment by blindenvy** [comment]
@FSixteen did you get Janus working against a kerberized hadoop cluster? If so can you please share what the solution was. Thanks in advance.

**Comment by chupman** [comment]
To prevent confusion we have recently added a default template for new issues containing the guidelines as to what belongs in issues. Usage, configuration, and general questions should be asked in [gitter](https://gitter.im/JanusGraph/janusgraph), [stackoverflow](https://stackoverflow.com/questions/tagged/janusgraph), or the [janusgraph-users google group](https://groups.google.com/forum/#!forum/janusgraph-users). Github issues are for reporting bugs, requesting new features, and tracking the development of JanusGraph. If your issue is still outstanding please consult one of the communities mentioned. If you still feel like your issue belongs here and was closed in error please feel free to repoen it.
