### ISSUE TITLE
org.apache.thrift.TApplicationException: Internal server error: Operation timed out for janusgraph.graphindex - received only 0 responses from 1 CL=QUORUM

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#967]
*Installation details*
Storage backend: ScyllaDB 2.0
index backend: Elsticsearch 6.0
Cluster size: 1
OS: CentOS
Platform: VM
Hardware: cores=1 memory= 2GB
Disks: 1 HDD

*Vertices details*
I have 1 vertex label `location` and properties: `name`:`String`, `latitude`:`Double`, `longitude`:`Double`, `location_type`:`Short`, `location_id`:`Integer`.

I have next data in JanusGraph:
7 vertices with label `location` and `location_type = 0` 
About 250 vertices with label `location` and `location_type = 1` 
About 370,000 vertices with label `location` and `location_type = 2` 
About 5,000,000 vertices with label `location` and `location_type = 3` 

I have next indexes:
```
PropertyKey locationId = mgmt.getPropertyKey("location_id");
PropertyKey locationType = mgmt.getPropertyKey("location_type");
VertexLabel locationVertexLabel =  mgmt.getVertexLabel("location");

mgmt.buildIndex("location_type_index", Vertex.class).addKey(locationType)
                .indexOnly(locationVertexLabel).buildCompositeIndex();

mgmt.buildIndex("location_id_index", Vertex.class).addKey(locationId)
                .indexOnly(locationVertexLabel).buildCompositeIndex();
```

I have next method to get locations by type:
```
private Set<Vertex> getLocations(short location_type){
    Set<Vertex> locations = graph.traversal().V()
            .hasLabel("location")
            .has("location_type", location_type)
            .limit(5)
            .toSet();
    return locations;
}
```
If I try to get locations with type 0 or 1 or 2 then it works OK because there are no too many vertices of such types. But when I try to get 5 vertices of type 3 then I get this exception:

```
"2018-03-27 15:29:44 - com.netflix.astyanax.connectionpool.exceptions.ThriftStateException: ThriftStateException: [host=10.10.10.50(10.10.10.50):9160, latency=5000(5000), attempts=1]org.apache.thrift.TApplicationException: Internal server error: Operation timed out for janusgraph.graphindex - received only 0 responses from 1 CL=QUORUM.
"com.netflix.astyanax.connectionpool.exceptions.ThriftStateException: ThriftStateException: [host=10.10.10.50(10.10.10.50):9160, latency=5000(5000), attempts=1]org.apache.thrift.TApplicationException: Internal server error: Operation timed out for janusgraph.graphindex - received only 0 responses from 1 CL=QUORUM.
        at com.netflix.astyanax.thrift.ThriftConverter.ToConnectionPoolException(ThriftConverter.java:177)
        at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:65)
        at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$1$2.execute(ThriftColumnFamilyQueryImpl.java:196)
        at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$1$2.execute(ThriftColumnFamilyQueryImpl.java:188)
        at com.netflix.astyanax.thrift.ThriftSyncConnectionFactoryImpl$ThriftConnection.execute(ThriftSyncConnectionFactoryImpl.java:153)
        at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:119)
        at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:352)
        at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$1.execute(ThriftColumnFamilyQueryImpl.java:186)
        at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:206)
        at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:115)
        at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getSlice(AstyanaxKeyColumnValueStore.java:104)
        at org.janusgraph.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:77)
        at org.janusgraph.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:77)
        at org.janusgraph.diskstorage.BackendTransaction$5.call(BackendTransaction.java:399)
        at org.janusgraph.diskstorage.BackendTransaction$5.call(BackendTransaction.java:396)
        at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:69)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:55)
        at org.janusgraph.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:470)
        at org.janusgraph.diskstorage.BackendTransaction.indexQuery(BackendTransaction.java:396)
        at org.janusgraph.graphdb.query.graph.MultiKeySliceQuery.execute(MultiKeySliceQuery.java:51)
        at org.janusgraph.graphdb.database.IndexSerializer.query(IndexSerializer.java:530)
        at org.janusgraph.graphdb.util.SubqueryIterator.<init>(SubqueryIterator.java:66)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$6.execute(StandardJanusGraphTx.java:1281)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx$6.execute(StandardJanusGraphTx.java:1150)
        at org.janusgraph.graphdb.query.QueryProcessor$LimitAdjustingIterator.getNewIterator(QueryProcessor.java:209)
        at org.janusgraph.graphdb.query.LimitAdjustingIterator.hasNext(LimitAdjustingIterator.java:68)
        at org.janusgraph.graphdb.query.ResultSetIterator.nextInternal(ResultSetIterator.java:54)
        at org.janusgraph.graphdb.query.ResultSetIterator.<init>(ResultSetIterator.java:44)
        at org.janusgraph.graphdb.query.QueryProcessor.iterator(QueryProcessor.java:68)
        at com.google.common.collect.Iterables$5.iterator(Iterables.java:617)
        at org.janusgraph.graphdb.tinkerpop.optimize.JanusGraphStep.lambda$new$0(JanusGraphStep.java:69)
        at org.apache.tinkerpop.gremlin.process.traversal.step.map.GraphStep.processNextStart(GraphStep.java:139)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:128)
        at org.apache.tinkerpop.gremlin.process.traversal.step.util.AbstractStep.next(AbstractStep.java:38)
        at org.apache.tinkerpop.gremlin.process.traversal.Traversal.fill(Traversal.java:177)
        at org.apache.tinkerpop.gremlin.process.traversal.Traversal.toSet(Traversal.java:124)
        at com.jblur.contest.location.dao.impl.JBCJanusgraphLocationDao.getAllLocations(JBCJanusgraphLocationDao.java:111)
        at com.jblur.contest.location.service.impl.JBCGeonamesLocationsLoaderService.saveOrUpdateAllLocations(JBCGeonamesLocationsLoaderService.java:126)
        at com.jblur.contest.location.service.impl.JBCGeonamesLocationsLoaderService.reinitializeWholeDatabase(JBCGeonamesLocationsLoaderService.java:296)
        at com.jblur.contest.location.controller.LocationsUpdateController.reportCurrentTime(LocationsUpdateController.java:51)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:65)
        at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.TApplicationException: Internal server error: Operation timed out for janusgraph.graphindex - received only 0 responses from 1 CL=QUORUM.
        at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
        at org.apache.cassandra.thrift.Cassandra$Client.recv_get_slice(Cassandra.java:671)
        at org.apache.cassandra.thrift.Cassandra$Client.get_slice(Cassandra.java:655)
        at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$1$2.internalExecute(ThriftColumnFamilyQueryImpl.java:201)
        at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$1$2.internalExecute(ThriftColumnFamilyQueryImpl.java:188)
        at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:60)
        ... 51 common frames omitted
```

In ScyllaDB I see next errors:
```
Mar 27 15:29:05 testvm scylla[2201]:  [shard 0] storage_proxy - Exception when communicating with 10.10.10.50: std::bad_alloc
Mar 27 15:29:10 testvm scylla[2201]:  [shard 0] batchlog_manager - Exception in batch replay: exceptions::read_timeout_exception (Operation timed out for system.batchlog - received only 0 responses from 1 CL=ONE.)
Mar 27 15:29:39 testvm scylla[2201]:  [shard 0] storage_proxy - Exception when communicating with 10.10.10.50: std::bad_alloc
``` 

Also, if I try to get any location by ID then it also works perfectly.

What could it be?
Regards

**Comment by porunov** [comment]
I've updated ScyllaDB to version 2.1.1 and the issue is gone now.
