### ISSUE TITLE
enhance Cassandra3 OLAP to work without Thrift

### ISSUE THREAD

**Issue by pluradj** [JanusGraph/janusgraph#985]
SparkGraphComputer jobs against the `cql` backend still require Thrift to be running. Here is the error stack trace:

```
gremlin> graph = GraphFactory.open('conf/hadoop-graph/read-cassandra-3.properties')
==>hadoopgraph[cassandra3inputformat->gryooutputformat]
gremlin> g = graph.traversal().withComputer(SparkGraphComputer)
==>graphtraversalsource[hadoopgraph[cassandra3inputformat->gryooutputformat], sparkgraphcomputer]
gremlin> g.V().count()
13:55:53 ERROR org.apache.cassandra.hadoop.ConfigHelper  - failed to connect to any initial addresses
13:55:53 ERROR org.apache.cassandra.hadoop.ConfigHelper  - 
java.io.IOException: Unable to connect to server 127.0.0.1:9160
	at org.apache.cassandra.hadoop.ConfigHelper.createConnection(ConfigHelper.java:574)
	at org.apache.cassandra.hadoop.ConfigHelper.getClientFromAddressList(ConfigHelper.java:545)
	at org.apache.cassandra.hadoop.ConfigHelper.getClientFromInputAddressList(ConfigHelper.java:529)
	at org.apache.cassandra.hadoop.AbstractColumnFamilyInputFormat.getRangeMap(AbstractColumnFamilyInputFormat.java:330)
	at org.apache.cassandra.hadoop.AbstractColumnFamilyInputFormat.getSplits(AbstractColumnFamilyInputFormat.java:125)
	at org.janusgraph.hadoop.formats.cassandra.CassandraBinaryInputFormat.getSplits(CassandraBinaryInputFormat.java:62)
	at org.janusgraph.hadoop.formats.util.GiraphInputFormat.getSplits(GiraphInputFormat.java:62)
	at org.apache.spark.rdd.NewHadoopRDD.getPartitions(NewHadoopRDD.scala:120)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.rdd.MapPartitionsRDD.getPartitions(MapPartitionsRDD.scala:35)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:239)
	at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:237)
	at scala.Option.getOrElse(Option.scala:120)
	at org.apache.spark.rdd.RDD.partitions(RDD.scala:237)
	at org.apache.spark.SparkContext.runJob(SparkContext.scala:1952)
	at org.apache.spark.rdd.RDD$$anonfun$fold$1.apply(RDD.scala:1088)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:150)
	at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:111)
	at org.apache.spark.rdd.RDD.withScope(RDD.scala:316)
	at org.apache.spark.rdd.RDD.fold(RDD.scala:1082)
	at org.apache.spark.api.java.JavaRDDLike$class.fold(JavaRDDLike.scala:399)
	at org.apache.spark.api.java.AbstractJavaRDDLike.fold(JavaRDDLike.scala:46)
	at org.apache.tinkerpop.gremlin.spark.process.computer.traversal.strategy.optimization.interceptor.SparkStarBarrierInterceptor.apply(SparkStarBarrierInterceptor.java:101)
	at org.apache.tinkerpop.gremlin.spark.process.computer.traversal.strategy.optimization.interceptor.SparkStarBarrierInterceptor.apply(SparkStarBarrierInterceptor.java:64)
	at org.apache.tinkerpop.gremlin.spark.process.computer.SparkGraphComputer.lambda$submitWithExecutor$0(SparkGraphComputer.java:260)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused (Connection refused)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:187)
	at org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
	at org.apache.cassandra.thrift.TFramedTransportFactory.openTransport(TFramedTransportFactory.java:41)
	at org.apache.cassandra.hadoop.ConfigHelper.createConnection(ConfigHelper.java:569)
	... 56 more
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at org.apache.thrift.transport.TSocket.open(TSocket.java:182)
	... 59 more
java.io.IOException: Unable to connect to server 127.0.0.1:9160
Type ':help' or ':h' for help.
Display stack trace? [yN]
```

**Comment by callajd** [comment]
Does anyone have an idea/sketch of what dev work is required to resolve this?  I might be able to take a look.

**Comment by FlorianHockmann** [comment]
In case people follow this issue but not janusgraph-dev, I started a discussion thread there on how to implement this feature:
https://groups.google.com/forum/#!topic/janusgraph-dev/7IU77lHwptw

**Comment by sauvermazeotap** [comment]
Hi JG community, 

Is any work in progress on this issue currently?

We are using scylla as JG cql backend and blocked by this issue. 

Any workarounds at the moment are appreciated

Thanks

**Comment by FlorianHockmann** [comment]
> Is any work in progress on this issue currently?

Yes, @farodin91 and I are currently working on a CQL input format for Hadoop which will enable JanusGraph to use CQL for Spark without needing Thrift anymore. We are also using Scylla ourselves and are currently testing this new input format with our production setup.
This fix should be included in JanusGraph 0.4.0.

**Comment by sauvermazeotap** [comment]
Thats fantastic @FlorianHockmann, could you please share tentative release plan for this feature. 

Also it would be great if you could point me to the pull request / branch where the feature is being developed currently.

Thanks a lot

**Comment by FlorianHockmann** [comment]
Since JanusGraph is a community-driven project, all decisions are made by the community which also includes release planning. So, I can't really predict a release date.
Having said that: I recently started [a discussion on janusgraph-dev about plans for the 0.4.0 release](https://groups.google.com/forum/#!topic/janusgraph-dev/HqfveAimktk) where these issues were suggested for that release:

- Upgrade to Cassandra 2.2 (#1398) which is a requirement for this issue as Cassandra 2.1 still used Thrift in its CQL input format.
- Upgrade to TinkerPop 3.4.0 (#1364).
- Removing support for deprecated backend versions.

And now we also have a relatively big issue to modernize our docs (see PR #1418 for a preview) that should probably also be done before the next release so we don't have to maintain two different versions of the documentation generation process.

I guess that we could be done with these issues in a few weeks and then release 0.4.0 in March or the beginning of April.

If you want to follow the progress, then I suggest that you keep an eye on these issues and follow on [janusgraph-dev](https://groups.google.com/forum/#!forum/janusgraph-dev).
If you want to help out, then you could either provide contributions for one of the issues mentioned, review pull requests or test pre-release versions. Especially for the CQL input format it would be really helpful to get feedback from users who have tried it out with bigger graphs.
You can find the branch [here](https://github.com/GDATASoftwareAG/janusgraph/commits/Issue_985_spark_via_cql) for the CQL input format.

**Comment by sauvermazeotap** [comment]
Thanks @FlorianHockmann for the information, we'd love to contribute in these areas.

cc: @shantanu422 @joydeepbroy-zeotap @rakeshsharmazeotap

**Comment by FlorianHockmann** [comment]
That's great to hear! 😄

Just make sure that you follow the process described in [CONTRIBUTING.md](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md) if you want to contribute code (or docs). Especially the contributor license agreement (CLA) is required and is best be taken care of early as the process for that can take some time.

**Comment by Jacky-Cai** [comment]
@FlorianHockmann Can you help to merge this change to 0.3 branch ?

**Comment by FlorianHockmann** [comment]
@Jacky-Cai Our approach is right now that new features go into `master` which means that they will land in the `0.4.0` release. This also applies to the pull request #1436 here.
Any reason why you couldn't upgrade to 0.4.0 when it's released?

**Comment by Jacky-Cai** [comment]
We like to deploy cassandra 3.x instead of cassanra 2.x as the 3.x is much
faster in our test.However,  the olap feature of cassandra 3.x is broken as
the thrift mode only work with cassanra 2.   Updating the db version is
always a bit deal in our firm, which I should avoid.

What is the estimate date of 0.4.0 release of janusgraph ?

If 0.4.0 is a few months away, we may prefer
1. doing extensive testing of master branch and use it in production or
2. merge the cql/olap support to 0.3.1

What is your suggestion?


Florian Hockmann <notifications@github.com> 于2019年3月2日周六 下午5:58写道：

**Comment by FlorianHockmann** [comment]
> the thrift mode only work with cassanra 2

Did you enable Thrift? In Cassandra 3, Thrift is disabled by default so you have to enable it explicitly. OLAP with Thrift should work with Cassandra 3. JanusGraph's tests also use Cassandra 3. You just need to make sure that you're using the `Cassandra3InputFormat`.

Regarding the 0.4.0 release, please see [my comment above](https://github.com/JanusGraph/janusgraph/issues/985#issuecomment-464352643) about what's missing for the 0.4.0 release and what could be a realistic release date.
If you want to help with getting 0.4.0 over the finish line sooner, then that would of course also be very much appreciated.

Merging these features to the 0.3 branch won't really help you as we will probably release the next version on the 0.3 branch together with the 0.4.0 release.

You can of course just build from `master` and use that in production. All commits on `master` have passed the test suite so it is stable in general. You would just be one the firsts to try out features that were added since 0.3.1. Testing your use cases first in a staging environment could be a good idea, but that's basically also true for any other major version upgrade.

**Comment by Jacky-Cai** [comment]
I did enable thrift and used "Cassandra3InputFormat"
the 0.3 branch's integration test uses cassandra 2.1.20 internally, which
works well.

I got the same error as this link:
https://groups.google.com/forum/?nomobile=true#!topic/janusgraph-users/6EcDGSaMia0


I got the error for the underlying cassandra-thrift driver 2.1.20 (the
dependency chain is AstyanaxStoreManager ->  astyanax-thrift 3.8.0 ->
cassandra-thrift 2.1.20 ) always return empty when work with 3.x cassandra
(I've tried 3.11.4 and 3.0.14)
the following code is in
org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxStoreManager

private void ensureColumnFamilyExists(String name) throws BackendException {
    Cluster cl = clusterContext.getClient();
    try {
        KeyspaceDefinition ksDef = cl.describeKeyspace(keySpaceName);
        boolean found = false;
        if (null != ksDef) {
            for (ColumnFamilyDefinition cfDef :
ksDef.getColumnFamilyList()) {  // astyanax-thrift driver  return
empty list when hit cassanda 3.x thrift
                found |= cfDef.getName().equals(name);
            }
        }

I've tried to upgrade 0.3 branch to cassandra-thrift drive to 3.x, but it
does not work either.

I think I should spend another day or two to fix 0.3 branch for cassandra
3.x, which might or might not be possible to support 2.x and 3.x in the
same code base.

Florian Hockmann <notifications@github.com> 于2019年3月4日周一 下午5:30写道：

**Comment by Jacky-Cai** [comment]
I believe I've found the root cause of janusgraph not working with
cassandra 3.x -- under thrift mode, it could not read column families of
tables been auto created via janusgraph's cql mode.  To get it around, we
could either created the keyspace/tables manually or create them under
thrift mode.

We should mention such potential issue in the document, probably I can make
it.


Jacky Cai <jackycai1983@gmail.com> 于2019年3月5日周二 下午10:14写道：

**Comment by FlorianHockmann** [comment]
> I believe I've found the root cause of janusgraph not working with cassandra 3.x -- under thrift mode, it could not read column families of tables been auto created via janusgraph's cql mode.

That's good to know and should be brought to the attention of users. Can you please create an issue for that?
A PR where this is explained in the docs would of course be very welcome. Just note that you need to sign a CLA for that if you haven't done that already. You can find detailed instructions on how to contribute to JanusGraph in [CONTRIBUTING.md](https://github.com/JanusGraph/janusgraph/blob/master/CONTRIBUTING.md).
