### ISSUE TITLE
Operation timed out for janusgraph.edgestore - received only 0 responses from 1 CL=QUORUM

### ISSUE THREAD

**Issue by porunov** [JanusGraph/janusgraph#997]
I've noticed that when I try to retrieve a list of vertices from the database (~10000 vertices) I am getting next error:
```
"2018-04-06 22:17:42 - com.netflix.astyanax.connectionpool.exceptions.ThriftStateException: ThriftStateException: [host=10.10.10.50(10.10.10.50):9160, latency=5016(5016), attempts=1]org.apache.thrift.TApplicationException: Internal server error: Operation timed out for janusgraph.edgestore - received only 0 responses from 1 CL=QUORUM.
"com.netflix.astyanax.connectionpool.exceptions.ThriftStateException: ThriftStateException: [host=10.10.10.50(10.10.10.50):9160, latency=5016(5016), attempts=1]org.apache.thrift.TApplicationException: Internal server error: Operation timed out for janusgraph.edgestore - received only 0 responses from 1 CL=QUORUM.
        at com.netflix.astyanax.thrift.ThriftConverter.ToConnectionPoolException(ThriftConverter.java:177)
        at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:65)
        at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOperationImpl.java:28)
        at com.netflix.astyanax.thrift.ThriftSyncConnectionFactoryImpl$ThriftConnection.execute(ThriftSyncConnectionFactoryImpl.java:153)
        at com.netflix.astyanax.connectionpool.impl.AbstractExecuteWithFailoverImpl.tryOperation(AbstractExecuteWithFailoverImpl.java:119)
        at com.netflix.astyanax.connectionpool.impl.AbstractHostPartitionConnectionPool.executeWithFailover(AbstractHostPartitionConnectionPool.java:352)
        at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4.execute(ThriftColumnFamilyQueryImpl.java:538)
        at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getNamesSlice(AstyanaxKeyColumnValueStore.java:157)
        at org.janusgraph.diskstorage.cassandra.astyanax.AstyanaxKeyColumnValueStore.getSlice(AstyanaxKeyColumnValueStore.java:108)
        at org.janusgraph.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:82)
        at org.janusgraph.diskstorage.keycolumnvalue.KCVSProxy.getSlice(KCVSProxy.java:82)
        at org.janusgraph.diskstorage.BackendTransaction$2.call(BackendTransaction.java:288)
        at org.janusgraph.diskstorage.BackendTransaction$2.call(BackendTransaction.java:285)
        at org.janusgraph.diskstorage.util.BackendOperation.executeDirect(BackendOperation.java:68)
        at org.janusgraph.diskstorage.util.BackendOperation.execute(BackendOperation.java:54)
        at org.janusgraph.diskstorage.BackendTransaction.executeRead(BackendTransaction.java:470)
        at org.janusgraph.diskstorage.BackendTransaction.edgeStoreMultiQuery(BackendTransaction.java:285)
        at org.janusgraph.graphdb.database.StandardJanusGraph.edgeMultiQuery(StandardJanusGraph.java:446)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.lambda$executeMultiQuery$5(StandardJanusGraphTx.java:1039)
        at org.janusgraph.graphdb.query.profile.QueryProfiler.profile(QueryProfiler.java:98)
        at org.janusgraph.graphdb.query.profile.QueryProfiler.profile(QueryProfiler.java:90)
        at org.janusgraph.graphdb.transaction.StandardJanusGraphTx.executeMultiQuery(StandardJanusGraphTx.java:1039)
        at org.janusgraph.graphdb.query.vertex.MultiVertexCentricQueryBuilder.execute(MultiVertexCentricQueryBuilder.java:113)
        at org.janusgraph.graphdb.query.vertex.MultiVertexCentricQueryBuilder.properties(MultiVertexCentricQueryBuilder.java:140)
        at com.jblur.contest.location.dao.impl.JBCJanusgraphLocationDao.getLocationsMap(JBCJanusgraphLocationDao.java:157)
        at com.jblur.contest.location.service.impl.JBCLocationsRetrievalThread.call(JBCLocationsRetrievalThread.java:32)
        at com.jblur.contest.location.service.impl.JBCLocationsRetrievalThread.call(JBCLocationsRetrievalThread.java:12)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: org.apache.thrift.TApplicationException: Internal server error: Operation timed out for janusgraph.edgestore - received only 0 responses from 1 CL=QUORUM.
        at org.apache.thrift.TApplicationException.read(TApplicationException.java:111)
        at org.apache.thrift.TServiceClient.receiveBase(TServiceClient.java:71)
        at org.apache.cassandra.thrift.Cassandra$Client.recv_multiget_slice(Cassandra.java:732)
        at org.apache.cassandra.thrift.Cassandra$Client.multiget_slice(Cassandra.java:716)
        at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4$1.internalExecute(ThriftColumnFamilyQueryImpl.java:544)
        at com.netflix.astyanax.thrift.ThriftColumnFamilyQueryImpl$4$1.internalExecute(ThriftColumnFamilyQueryImpl.java:541)
        at com.netflix.astyanax.thrift.AbstractOperationImpl.execute(AbstractOpera
```

If I try a smaller count then it is OK. Also, if I try to run 10 threads where each retrieves 2000 vertices from the database concurrently then I also get this error because the retrieval is getting very slow.
I've noticed that I am getting maximum speed when there is only 1 thread which works with JanusGraph. If I use 2 threads then speed is decreasing more than 2 times and so on.

I do understand that this error shows read operation timeout, but it isn't configurable. These parameters don't work for me:
```
storage.connection-timeout=240000
storage.read-time=240000
storage.write-time=240000
```
My storage backend is: ScyllaDB 2.1.1
Index backend: Elasticsearch 6.2.3
JanusGraph: 0.3.0-SNAPSHOT (2cc4276213471adf50a109b7cb234ca60051e136 Mar 27, 2018)

My ScyllaDB and Elasticsearch are running under development mode on a local virtual machine. Both ScyllaDB and Elasticsearch has 2 GB of RAM available. There is only one instance of ScyllaDB, one instance of Elasticsearch and one instance of an application with JanusGraph.

**Comment by porunov** [comment]
Thrift support was deprecated in 0.4.1 version of JanusGraph. Thrift is going to be completely removed in 0.6.0 version of JanusGraph due to deprecation. The PR is #1800 
I am closing this issue as an obsolete issue.
